### ISSUE TITLE
Tweak initial position of period counter tool

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#100]
Requested by @arouinfar in https://github.com/phetsims/fourier-making-waves/issues/95.

The location period counter tool is vertically centered between the Harmonics and Sum graphs, but due to the x-axis labels looks off-center. Can it instead be centered in the space between the Harmonics graph x-axis labels and the top of the Sum graph? Here's a rough approximation:

![image](https://user-images.githubusercontent.com/8419308/123735199-035dc580-d85c-11eb-8f6a-a7a16cb68f8f.png)

**Comment by pixelzoom** [comment]
Done, screenshot below.  Please verify in master. 

<img width="349" alt="screenshot_1041" src="https://user-images.githubusercontent.com/3046552/124185807-aee36180-da78-11eb-9d94-b159d42a2e4a.png">

**Comment by arouinfar** [comment]
👍🏻
