### ISSUE TITLE
How to start/stop continuous sounds that are specific to a Screen?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#101]
The Discrete screen has a checkbox/slider control for the sound associated with the Fourier series:

<img width="280" alt="screenshot_1050" src="https://user-images.githubusercontent.com/3046552/124819749-ded3ae80-df29-11eb-969e-31cb5ce47d94.png">

This is a continous sound.  And I just discovered that switching screens does NOT stop this sound.

@jbphet Does soundManager provide any support for screen-specific sounds? Or do I need to handle this myself?  If I need to handle it myself, what is the recommended pattern?

**Comment by pixelzoom** [comment]
In the above commit, I added a workaround that involves observing `phet.joist.screenProperty`, and controlling the Fourier series sound based on whether the Discrete screen is selected.  This needs to be done at the Screen level, because ScreenView and Model do not know about (and should not know about) Screen.  It also can't be wired up right away, because the model (and view) have not been constructed.  So I had to override `Screen.initializeModel`, which is documented as `@public (joist-internal)` and should therefore not be accessed or overridden outside of joist.

I also don't think this is much of a solution because it would need to be duplicated in each sim that has this need.  And that will be any sim that has a continous sound.

@jbphet is there a better way? Has this been considered in the design of UI sounds?

**Comment by jbphet** [comment]
In the early days of this library I asked about how best to support this feature, and the consensus was that in cases where a sound needed to be muted when a screen change occurred, we should associate the sound generator with a scenery Node instead of a screen.  That is supported through the `associatedViewNode` option to the `soundManager.addSoundGenerator` method.  There is an example usage in tambo's `TestingScreenView`, and you can try it out by going to the "Testing" screen in the tambo demo, selecting the "Long Sound Test", kicking off the lightning, and switching screens.  This example is _not_ a loop, but I'm fairly certain that the loop case was tested and should work.  Let me know if it doesn't.

**Comment by pixelzoom** [comment]
Awesome, `associatedViewNode` works great.  Closing.

**Comment by pixelzoom** [comment]
Reopening, there's still a problem here.  

In https://github.com/phetsims/fourier-making-waves/issues/55, we implemented "ducking" of UI sounds. When the Fourier series sound is turned on, all sounds for the 'user-interface' category are attenuated.  In DiscreteScreenView.js:

```js
    // When sound is enabled for the Fourier series, duck all user-interface sounds.
    const userInterfaceDefaultOutputLevel = soundManager.getOutputLevelForCategory( 'user-interface' );
    model.fourierSeriesSoundEnabledProperty.link( enabled => {
      const outputLevel = enabled ? 0.1 * userInterfaceDefaultOutputLevel : userInterfaceDefaultOutputLevel;
      soundManager.setOutputLevelForCategory( 'user-interface', outputLevel );
    } );
```

These steps demonstrate the problem:
1. Start the sim.
2. Go to the Discrete screen.
3. Press some UI components and note sound level.
4. Turn on sound for the Fourier series (checkbox with music notes).
5. Press some UI components and note the _decreased_ sound level.
6. Go to one of the other screens. Note that Fourier series sound stops.
7. Click some UI components and note that their sound level is still _decreased_.

@jbphet any thoughts on how to address this? Instead of `model.fourierSeriesSoundEnabledProperty`, should I be observing some Property of my FourierSoundGenerator?

**Comment by pixelzoom** [comment]
Observing FourierSoundGenerator's `fullyEnabledProperty` seems to produce the desired result:

```js
    // When the FourierSoundGenerator is enabled, duck all user-interface sounds.
    const userInterfaceDefaultOutputLevel = soundManager.getOutputLevelForCategory( 'user-interface' );
    fourierSoundGenerator.fullyEnabledProperty.link( enabled => {
      const outputLevel = enabled ? 0.1 * userInterfaceDefaultOutputLevel : userInterfaceDefaultOutputLevel;
      soundManager.setOutputLevelForCategory( 'user-interface', outputLevel );
    } );
```

But I'm read the doc, and I don't really understand `fullyEnabledProperty`, or it's partner `locallyEnabledProperty`. 

@jbphet please advise.

**Comment by pixelzoom** [comment]
I'm going to re-close this, and move this problem over to the ducking issue.
