### ISSUE TITLE
Wave Packet Width: standard deviation vs delta

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#103]
This is something that I don't understand in the Wave Packet screen, related to the Wave Packet Width controls. But I've run across it enough times in literature to be a little concerned. So I'd like @arouinfar to determine whether there's a problem here.

We are providing controls that are labeled with symbols for standard deviation: σ<sub>k</sub>, σ<sub>x</sub>, σ<sub>ω</sub>,  σ<sub>t</sub>.  

The implementation is not using standard deviation, it's using deltas: dk, dx, dω, dt.  And width is computed as `2 * dk` for space domain,  `2 * dω` for time domain. 

So we're computing delta values in the model, but labeling them as standard deviation in the view.  (Or maybe the model is actually using standard deviations, and they are incorrectly named in the code?)

I gather (possibly incorrectly) from the literature that delta is a simplified way of computing the width, not the same as standard deviation.  I'm not clear on exactly how they differ, or whether/how they may produce different results.

So... Is showing delta values labeled with standard deviation symbols a problem?  And can you help me understand how they differ?

**Comment by arouinfar** [comment]
Looking at the code and the [legacy documentation](https://drive.google.com/file/d/1lAS0ye9ceFqXYqVoWK6TsYIZn8c6Q2OK/view?pli=1), I'm fairly certain that the dk, dx, etc. values in the model are actually standard deviations so we are not incorrect in how we are labelling the user interface.

For example, let's look at this snippet from [WavePacket.js](https://github.com/phetsims/fourier-making-waves/blob/master/js/wavepacket/model/WavePacket.js#L112-L128).
```js
  /**
   * Gets the amplitude of component k, using the standard Gaussian formula:
   *
   * A(k,k0,dk) = exp[ -((k-k0)^2) / (2 * (dk^2) )  ] / (dk * sqrt( 2pi ))
   *
   * @param {number} k - component value, in radians/mm
   * @returns {number}
   * @public
   */
  getAmplitude( k ) {
    assert && assert( typeof k === 'number' );

    const k0 = this.k0Property.value;
    const dk = this.dkProperty.value;
    const kk0 = k - k0;
    return Math.exp( -( kk0 * kk0 ) / ( 2 * dk * dk ) ) / ( dk * Math.sqrt( 2 * Math.PI ) );
  }
  ```
  
 This follows the form of a [Gaussian function](https://en.wikipedia.org/wiki/Gaussian_function), so dk must be the standard deviation σ<sub>k</sub>.  Here's the general form of a Gaussian function, where σ is the standard deviation:
![image](https://user-images.githubusercontent.com/8419308/125854344-327ac523-bc69-4e2c-9d1c-4159ecfeac72.png)

**Comment by pixelzoom** [comment]
So things are incorrectly identified as deltas in the code? I should probably change that. 

And is there indeed a difference between delta and standard deviation?

**Comment by pixelzoom** [comment]
7/15/2021 design meeting @arouinfar @kathy-phet @pixelzoom 

Remaining questions/issues were moved to #105 and #106.  Closing.
