### ISSUE TITLE
Basics version?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#104]
7/15/2021 design meeting @kathy-phet @arouinfar @pixelzoom 

@arouinfar will investigate what might be in a "basics" version of this sim.  Consult with the CU faculty member who uses this sim for teaching music.

@kathy-phet said that a basics version would subtract features, not add features.

**Comment by pixelzoom** [comment]
It would be most cost-effective to do QA testing for a basics version at the same time as the full version.  If you'd like that to happen, then this decision needs to be made in the next week or two.

**Comment by arouinfar** [comment]
I talked this over a bit with Steve for #105. He typically uses the Discrete and Wave Game screens with students when teaching about Fourier transforms, regardless if he's teaching about sound or mechanics. Looking at the features on these screens, we didn't really see anything that could be subtracted away. This means a spin-off sim would be the same as using `screens=1,2`. 

Given this feedback, I don't think I would pursue a spin-off.

**Comment by pixelzoom** [comment]
Discussed at 7/29/21 standup meeting. @kathy-phet agreed, no basics version.  Closing.
