### ISSUE TITLE
Questions for subject-matter expert

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#105]
7/15/20921 design meeting @arouinfar @kathy-phet @pixelzoom 
Related to https://github.com/phetsims/fourier-making-waves/issues/103 and https://github.com/phetsims/fourier-making-waves/issues/81 and this sub-panel in the Wave Packet screen:

![screenshot_241](https://user-images.githubusercontent.com/3046552/125861421-c6df0d46-ce87-41bf-9eaf-746beca35a8b.png)

@arouinfar will consult with a subject-matter expert about the following questions:

- [ ] What should the units be for σ<sub>x</sub> and σ<sub>t</sub>, the bottom slider? m/rad and ms/rad? Or just m and ms?

- [ ] Is it OK to show "σ<sub>x</sub> = 1/σ<sub>k</sub> = {value}" for the bottom slider, or should this relationship be discovered? 

- [ ] The top slider, σ<sub>k</sub> and σ<sub>ω</sub>, is currently controlling a model Property named `dkProperty`.  We've considered renaming it to `sigmaProperty`, but that could still result in confusion with the bottom slider,  σ<sub>x</sub> and σ<sub>t</sub>.  `standardDeviationProperty` has the same problem, both sliders are a form of standard deviation.  Is there a better (more specific?) name for this Property that doesn't use the words "sigma" or "standard deviation"?

**Comment by pixelzoom** [comment]
@arouinfar You might also want to ask about the general equation for computing wave packet amplutudes, for https://github.com/phetsims/fourier-making-waves/issues/18.

**Comment by pixelzoom** [comment]
>  Is there a better (more specific?) name for this Property that doesn't use the words "sigma" or "standard deviation"?

How about `halfWidthProperty`?

**Comment by arouinfar** [comment]
I've scheduled a meeting with one content expert for Monday, and I'm still waiting to hear back from the other.

> The top slider, σ<sub>k</sub> and σ<sub>ω</sub>, is currently controlling a model Property named `dkProperty`.  We've considered renaming it to `sigmaProperty`, but that could still result in confusion with the bottom slider,  σ<sub>x</sub> and σ<sub>t</sub>.  `standardDeviationProperty` has the same problem, both sliders are a form of standard deviation.  Is there a better (more specific?) name for this Property that doesn't use the words "sigma" or "standard deviation"?  

> How about `halfWidthProperty`?

"Width" is a bit tricky when talking about Gaussians. There is no one width, as it varies with height. Depending on your field, you may be interested in the full width at half maximum (FWHM) or 1/e2 of the max (used for laser beam diameter). Regardless, the standard deviation determines how broad the distribution will be. I think the most accurate name is really `standardDeviationProperty`.

**Comment by pixelzoom** [comment]
>  I think the most accurate name is really `standardDeviationProperty`.

OK, let's assume that we use `standardDeviationProperty` for the top slider. What name do we use for the bottom slider?

**Comment by pixelzoom** [comment]
@arouinfar said:
>  ... I think the most accurate name is really `standardDeviationProperty`.

OK, let's assume that we use `standardDeviationProperty` for the top slider. What name do we use for the bottom slider? 

`standardDeviationProperty` also seems a bit too vague/general. Standard deviation of what? 

Keep in mind that we're choosing names that will appear in Studio.

**Comment by pixelzoom** [comment]
Maybe it would help to frame the Property-name issue as a Studio design issue.  Here's what the Studio tree looks like.  Provide the names and `phetioDocumentation` for the 2 missing Properties:

```
-fourierMakingWaves
  -wavePacketScreen
    -model
      -fourierSeries
        -componentSpacingProperty
      -wavePacket
        -centerProperty
        -???
        -???
```

**Comment by pixelzoom** [comment]
Over in https://github.com/phetsims/fourier-making-waves/issues/106, the model was changed so that the Studio tree would look like this:

```
-fourierMakingWaves
  -wavePacketScreen
    -model
      -fourierSeries
        -componentSpacingProperty
      -wavePacket
        -centerProperty
        -??? // σk or σw
        -widthProperty // derived
```

So there is no Property in the model for σx and σt.  That Property exists in the view as an adapter Property for that slider, and I'm not planning to instrument it for PhET-iO.  If we do decide to instrument it, it will be ood that it's in the view, and it will need to be `phetioReadOnly: true`.

**Comment by pixelzoom** [comment]
On the view side, here's what the tree currently looks like in Studio. We need names for `dkControl` and `dxControl`.

![screenshot_1097](https://user-images.githubusercontent.com/3046552/127372842-b020e52c-7589-46d3-b53b-cfd004d656fa.jpg)

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/fourier-making-waves/issues/105#issuecomment-888470217, I said:
> `standardDeviationProperty` also seems a bit too vague/general. Standard deviation of what?

But [this reference](https://www.chm.uri.edu/dfreeman/chm532/se.pdf) says:
> The parameter ∆x is often called the _standard deviation_ of the Gaussian, and the standard deviation is a measure of the width of the wave packet. 

So maybe `standardDeviation` is OK for what is current `dkProperty`, and `standardDeviationControl` for `dkControl`.

But I'm still at a loss for what to call `dxProperty` and `dxControl`, the inverse of dk.

**Comment by pixelzoom** [comment]
I'm going to go with these name changes, which will be visible in Studio:

dkProperty -> standardDeviationProperty
dkControl -> standardDeviationControl
dxProperty -> inverseStandardDeviationProperty
dxControk -> inverseStandardDeviationControl

**Comment by pixelzoom** [comment]
Rename completed.  I'm also considering undoing what I did in #106, and moving  inverseStandardDeviationProperty back into model.wavePacket.  It's very odd in Studio to have it at `view.controlPanel.wavePacketWidthLayoutBox.inverseStandardDeviationControl.inverseStandardDeviationProperty`.

**Comment by pixelzoom** [comment]
Well, now that I've done that rename, I discover that σ<sub>k</sub> is "the standard deviation of k", and σ<sub>x</sub> = 1 / σ<sub>k</sub> is "the standard deviation of x".  So all of these σ<sub>something</sub> values are standard deviations.  So how to deferentiate (by name) between σ<sub>k</sub> and σ<sub>x</sub> (in space domain) and σ<sub>ω</sub> and σ<sub>t</sub> (in time domain)?

**Comment by kathy-phet** [comment]
We should ask Mike and Steve to consult on this topic. Amy, let me know if I need to help get Mike’s attention.

**Comment by arouinfar** [comment]
I met with Steve, but didn't hear back from Mike. Steve has used this sim in the past for the Sound and Music course. He also mentioned using it in mechanics (classical and quantum) courses when Fourier transforms come up.

I'll tag for design meeting and we can decide in the check-in whether or not we need further feedback.

>  What should the units be for σ<sub>x</sub> and σ<sub>t</sub>, the bottom slider? m/rad and ms/rad? Or just m and ms?

Steve and I both find it odd to include rad in the denominator. If we are talking about displacement or time, the units that make the most sense are simply m and ms. Radians are dimensionless so it is not incorrect to exclude them here. I've added this to the Teacher Tips issue referenced above.

Steve did note that it seems odd to use ms rather than s, but we decided ms was necessary for the sound-related goals and consistency with other screens.

> Is it OK to show "σ<sub>x</sub> = 1/σ<sub>k</sub> = {value}" for the bottom slider, or should this relationship be discovered?

Steve did not see an issue with including this information, though he has not used this sim to teach specifically about the Uncertainty Principle. 

I am in favor of continuing to explicitly show the inverse relationship, as it may help students make a connection with the Uncertainty Principle.

> Well, now that I've done that rename.... I discover that σ<sub>k</sub> is "the standard deviation of k", and σ<sub>x</sub> = 1 / σ<sub>k</sub> is "the standard deviation of x".  So all of these σ<sub>something</sub> values are standard deviations, there is no "inverse standard deviation".  So how to differentiate (by name) between σ<sub>k</sub> and σ<sub>x</sub> (in space domain) and σ<sub>ω</sub> and σ<sub>t</sub> (in time domain)? 

I actually like the way things are set up in the tree. Instead of `inverseStandardDeviation`, I would call it the `conjugateStandardDeviation`. Space and momentum/wavenumber and frequency/time are conjugate pairs, and the term "conjugate" appears often in this context.

**Comment by pixelzoom** [comment]
> ... Radians are dimensionless so it is not incorrect to exclude them here.

Done. The units for conjugate standard deviation are now 'm' and 'ms.

> ... I am in favor of continuing to explicitly show the inverse relationship ...

OK, no change here.

> I actually like the way things are set up in the tree. Instead of `inverseStandardDeviation`, I would call it the `conjugateStandardDeviation`.

Done, through the code base, including tandem names.

@arouinfar please review. If there's nothing left to do here, please close.

**Comment by arouinfar** [comment]
Looks good in master, so I'll go ahead and close.
