### ISSUE TITLE
Should the Fourier series output-level slider have a non-zero minimum?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#107]
I'm wondering if the slider for the Fourier series output level should have a non-zero minimum.  The checkbox can be used to turn the sound off.  With the slider also being able to turn off the sound, you can end up with a situation where the checkbox does nothing, see screenshot below.   One would hope that the user would figure this out, but I wouldn't put money on it.  A more foolproof UI would use a very faint volume for the slider minimum (and a different minimum icon).

@arouinfar thoughts?

<img width="265" alt="screenshot_1095" src="https://user-images.githubusercontent.com/3046552/127238234-b95b280d-7580-4ce4-b7b4-601f7ecbdbf0.png">

**Comment by pixelzoom** [comment]
Here's what a non-zero minumum would look like:

<img width="273" alt="screenshot_1096" src="https://user-images.githubusercontent.com/3046552/127238527-390eacad-9411-4d63-9899-8cde86525825.png">

**Comment by pixelzoom** [comment]
In the above commits...

The slider now uses a FA5 icon that is appropriate for the range.min of `fourierSeriesSoundOutputLevelProperty`.  If the min is zero, it uses volumeOffSolidShape.js. Otherwise it uses volumeDownSolidShape.js.

In the model, I'm set the range of `fourierSeriesSoundOutputLevelProperty` to be [0.05, 1].  Keep in that perception of output level is logarthmic, so 1 will sound twice as loud as 0.1.

@arouinfar please test-drive in master.

**Comment by arouinfar** [comment]
> The checkbox can be used to turn the sound off. With the slider also being able to turn off the sound, you can end up with a situation where the checkbox does nothing, see screenshot below. One would hope that the user would figure this out, but I wouldn't put money on it. A more foolproof UI would use a very faint volume for the slider minimum (and a different minimum icon).

This is a really good point @pixelzoom, and I think it's a great idea to instead use a non-zero volume at the minimum.

> @arouinfar please test-drive in master. Let me know whether you'd like to revert to min=0, or whether you'd prefer a different min.

The current min feels good to me, so let's keep it. Thanks for taking the initiative!
