### ISSUE TITLE
Wave Packet Center slider should snap to π/4.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#108]
@arouinfar suggested making the Wave Packet Center slider snap to π/4, to make things more reproducible.  This is a change from the Java version, where that slider was continuous.

**Comment by pixelzoom** [comment]
Done in the above commit. @arouinfar please review in master, then close.

**Comment by arouinfar** [comment]
The snapping feels good to me, thanks!
