### ISSUE TITLE
Screen background colors

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#109]
In other sims, we typically use a different color background for each screen, or at least different colors for screens that are significantly different.  This sim has been using the same blue color for all 3 screens. (The Java version used a lovely gray for all 3 screens :) 

Should we use different background colors for each screen? Or maybe just a different color for the Wave Packet screen, since it's so different from the other 2 screens?

**Comment by pixelzoom** [comment]
In the above commits, I added different Properties for each screen's background color. If you want to experiment, they live in [FMWColors.js](https://github.com/phetsims/fourier-making-waves/blob/master/js/common/FMWColors.js):

```js
  // Background colors for screens.
  discreteScreenBackgroundColorProperty: new ProfileColorProperty( 'discreteScreenBackgroundColorProperty', {
    default: new Color( 236, 255, 255 )
  } ),
  waveGameScreenBackgroundColorProperty: new ProfileColorProperty( 'waveGameScreenBackgroundColorProperty', {
    default: new Color( 236, 255, 255 )
  } ),
  wavePacketScreenBackgroundColorProperty: new ProfileColorProperty( 'wavePacketScreenBackgroundColor', {
    default: new Color( 255, 250, 227 )
  } ),
```

The color for the first 2 screens is unchanges. The color for the Wave Game screen is a cornflower yellow, taken from the first screen of Equality Explorer.

@arouinfar please review in master, let me know what you'd like to change.

**Comment by arouinfar** [comment]
> In other sims, we typically use a different color background for each screen

This is generally the case for middle school math sims. I think the design motivation is that it's handy for teachers to be able to tell students to use the "green screen" or to be able to tell what screen a student is working on at a glance.

I don't see it as a critical feature for Fourier, but it is a nice touch. I agree that the third screen is more separate so it's most appropriate to change its color. The pale yellow looks good to me, and I like that it is re-used from another sim. :)
