### ISSUE TITLE
determine why amplitude range is [-1.27, 1.27] and document it

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#11]
In FourierConstants.java of the Java version, the maximum absolute amplitude is:

```js
    public static final double MAX_HARMONIC_AMPLITUDE = ( 4 / Math.PI );
```

So the range of amplitudes is [-1.27, 1.27]. 

There is unfortunately nothing is the Java code or design docs that documents why this range is significant. And it makes the sliders in the Amplitudes panel a little odd, because their min and max are not labeled:

<img width="734" alt="screenshot_677" src="https://user-images.githubusercontent.com/3046552/99014033-0dba9180-250f-11eb-9ed3-3e82fd0324fe.png">

This looks a little more odd if we move in the direction that we discussed in https://github.com/phetsims/fourier-making-waves/issues/9#issuecomment-726391745, where the amplitude sliders are not presented as a chart:

<img width="920" alt="screenshot_676" src="https://user-images.githubusercontent.com/3046552/99006391-9af5ea00-24ff-11eb-8a1f-32bd1a7f85b7.png">

It would be nice to either (a) determine why [-1.27,1.27] was chosen and document it in the HTML5 implementation, or (b) change the range to [-1,1].

**Comment by pixelzoom** [comment]
@ariel-phet @kathy-phet any insights on this one?

**Comment by pixelzoom** [comment]
Raising priority to high.  If this needs to change, it's going to affect a lot of things.  If it's not going to change, we have some UI issues to discuss.

**Comment by kathy-phet** [comment]
I will reach out to the original lead designer.

**Comment by kathy-phet** [comment]
I see the square wave uses a 1.27 preset. I wonder if that was to keep the coefficients on scale for that preset? At any rate I sent and email off to a couple of folks.

**Comment by arouinfar** [comment]
@pixelzoom I thought we figured this out when we met to discuss #18. The amplitude range is [-4/pi, 4/pi] because of the factor of pi/4 in the [Fourier series of a square wave](https://mathworld.wolfram.com/FourierSeriesSquareWave.html).  For n=1, the amplitude is 4/pi. None of the other presets contain an a harmonic with an amplitude greater than 1.00.
![image](https://user-images.githubusercontent.com/8419308/100692819-e1917400-3348-11eb-9f6c-2f96818eb208.png)

>I wonder if that was to keep the coefficients on scale for that preset?

I think so. We could probably multiply all of the amplitudes by a scale factor so the first harmonic has an amplitude of 1.00. I don't know if we actually want to do that, however. Users probably expect the data in the sim to match the the actual Fourier series of a square wave.

**Comment by kathy-phet** [comment]
Ah - that makes sense. I agree leaving it so the default range has 4/pi on scale. Thanks!

**Comment by pixelzoom** [comment]
Sorry, I have no recollection of discussing this in the context of #18.   But that makes sense, and I'll document it in the code.

1.27 may still seem like a magic number fo students (and teachers!) Do you think that we should label any of the y axes (or range for the amplitude sliders?) with 4/pi ?   Or discuss in the Teacher Tips?  Or both?

**Comment by ariel-phet** [comment]
@pixelzoom @arouinfar certainly seems mentioning in the the teacher tips. I do not however think it is worth labeling on the axis. If we were concerned at all, we could consider an "info" button as we have used in other sims to help explain the range, but otherwise I do not think it is necessary.

**Comment by pixelzoom** [comment]
> @pixelzoom @arouinfar certainly seems mentioning in the the teacher tips. 

I've added this to https://github.com/phetsims/fourier-making-waves/issues/21#issuecomment-736804960 (Teacher Tips).

**Comment by pixelzoom** [comment]
Documented in FourierSeries.js:

```js
// The amplitude range is [-4/pi, 4/pi] because of the factor of 4/pi in the Fourier series of a square wave.
// For n=1, the amplitude is 4/pi. See https://mathworld.wolfram.com/FourierSeriesSquareWave.html and
// https://github.com/phetsims/fourier-making-waves/issues/11
const MAX_ABSOLUTE_AMPLITUDE = 4 / Math.PI;
```

Closing.
