### ISSUE TITLE
How should y-axis autoscale for Amplitudes chart?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#118]
In the Java and HTML5 versions...

With these settings, the top chart shows 1 bar at 12pi:

<img width="1024" alt="screenshot_1129" src="https://user-images.githubusercontent.com/3046552/128264157-fbbbdb47-c940-4af6-b14f-1fa8d72326f7.png">

If I then move the Wave Packet Center to either 9pi or 15pi, I see no bars in the top chart. For example:

<img width="1024" alt="screenshot_1128" src="https://user-images.githubusercontent.com/3046552/128264017-e33a0809-b7f1-4fd7-ae3b-08968892f54e.png">

I don't understand this case. It occurs in both the Java and HTML5 versions.  Is this a bug? Or is there an explanation?

**Comment by pixelzoom** [comment]
Oh wait.... I do see 2 bars in the bottom screenshot, at 8pi and 10pi.  They are so small that I missed them.  I still don't understand why, but have a little more confidence that this is correct :)   

@arouinfar is this indeed correct?  Do you think it will be a problem for users?  Should we be using something other than grayscale, so that even tiny bars would be more visible?

**Comment by pixelzoom** [comment]
Ah.... I think the problem here is with the autoscaling of the y axis.  Those 2 bars that are hard to see should be made bigger by autoscaling the y axis, and that's not happening.   Self assigning to investigate.

**Comment by pixelzoom** [comment]
The y-axis scale is indeed correct -- it's scaled to the Continuous Waveform, see screenshot below.   And you can barely see the component amplitudes at 8pi and 10pi.

Should the y-axis to be scale to the maximum amplitude for whichever plots are visible?  That would mean that the chart's scale will likely change when toggling the "Continuous Waveform" checkbox. 

@arouinfar thoughts?

**Comment by pixelzoom** [comment]
In the above commit, I've changed the auto-scale behavior of the Amplitudes chart.  Test drive in master or [1.0.0-dev.37](https://phet-dev.colorado.edu/html/fourier-making-waves/1.0.0-dev.37/phet/fourier-making-waves_en_phet.html).

The good news is that the tiny amplitudes that were so difficult to see in https://github.com/phetsims/fourier-making-waves/issues/118#issue-961161859 are now clearly visible:

<img width="1089" alt="screenshot_1137" src="https://user-images.githubusercontent.com/3046552/128647188-19cf515b-1b50-4c61-aba5-d5c038d68b56.png">

The bad news is that there are now some situations where the size of the amplitude bars doesn't appear to change, but the y-axis scale is changing dramatically.  This tends to occur when there are 1 or 2 amplitudes bars (max component spacing).   To reproduce:

1. Set Component Spacing to 2pi.
2. Set Wave Packet Center (k0) to 12pi.
2. Set Wave Packet Width (std deviation) to 1.

You'll see this Amplitudes chart. Note the y-axis scale.

<img width="811" alt="screenshot_1139" src="https://user-images.githubusercontent.com/3046552/128647261-a4495105-ae42-4660-8cc4-1ca2cc4379a5.png">

Keeping your eye on the y-axis scale, slide the Wave Packet Center slider around.  You'll see setting where there is a dramatic change in the y-axis scale, and no change in the amplitude bar height.  For example, here's k0=35.3 (11.25pi):

<img width="814" alt="screenshot_1140" src="https://user-images.githubusercontent.com/3046552/128647297-da603f9c-8f0b-42e3-a094-8e359dc6467a.png">

This seems better to me than the alternative, which was not seeing the tiny amplitude bars. The auto-scaling in this screen is something that definitely needs to be highlighted in the Teach Tips, and maybe that will be sufficient.

@arouinfar please review. Let me know what you think, whether you want to change anything, etc.

**Comment by pixelzoom** [comment]
In the "to reproduce" scenario in the previous comment...  While you're dragging the Wave Packet Center (k0) slider, note that there is similar behavior for the Components and Sum charts.  That is, there are settings where the waveforms don't appear to change much (or at all) and the y-axis scale is changing dramatically. So the behavior in the Amplitudes chart is now consistent with those charts.

**Comment by pixelzoom** [comment]
Going back to the example that I described in my first comment, https://github.com/phetsims/fourier-making-waves/issues/118#issue-961161859, where I couldn't see the amplitudes at 8pi and 10pi...  Note that when you check the "Continuous Waveform" checkbox, seeing those amplitudes is still and issue -- AND the y-axis scale changes dramatically. 

To reproduce:

1. set k<sub>1</sub> = 2pi
2. set k<sub>0</sub> = 9pi
3. set σ<sub>k</sub> = 1
4. Toggle the "Continuous Waveform" checkbox on and off.

The Amplitudes chart is now auto-scaled based on which charts are visible.  And there's a huge difference in the y-axis range for the component amplitudes and the Continuous Waveform.

**Comment by pixelzoom** [comment]
Note that this issue also applies to the Sum chart.  When "Waveform Envelope" is checked, it's maximum amplitude may be greater than the sum's maximum amplitude.

To demonstrate, set to these values:

<img width="267" alt="screenshot_1156" src="https://user-images.githubusercontent.com/3046552/128769675-ccf6cdd1-8891-4d88-ac8a-19f4275ce951.png">

With "Waveform Envelope" unchecked:

<img width="815" alt="screenshot_1157" src="https://user-images.githubusercontent.com/3046552/128769701-8e226651-d1d6-4652-9b54-68e2f52b8792.png">

With "Waveform Envelope" checked, note the different y-axis scale:

<img width="819" alt="screenshot_1158" src="https://user-images.githubusercontent.com/3046552/128769729-eedb63d8-4737-47ad-ba72-53b6f672b86d.png">

**Comment by pixelzoom** [comment]
Because of changes in https://github.com/phetsims/fourier-making-waves/issues/158, we now want to always scale the Amplitudes chart to the Continuous Waveform.  Self-assigning to change this.

**Comment by pixelzoom** [comment]
Done in the above commit - the Amplitudes chart now scales to the peak amplitude of the Continuous Waveform, regardless of whether it's visible. 

@arouinfar please review in master.

**Comment by arouinfar** [comment]
Looks good, thanks!
