### ISSUE TITLE
Add an expand/collapse button to the the top chart in Wave Packet screen?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#120]
Now that the top chart has a title (see screenshot below)...  Should it have an expand/collapse button? It seems like that would be useful, for the same "predictive" reasons as the other change.  For example, hide the top chart, set the component spacing, and guess how many components you have. Or more the Wave Packet Center and guess what affect that has on the top chart.

Having an expand/collapse button and associated Property would also make it easier to hide the top chart via PhET-iO and Studio.

@arouinfar what do you think? Should we add an expand/collapse button to the top chart?  My feeling is yes.
 
<img width="1087" alt="screenshot_1135" src="https://user-images.githubusercontent.com/3046552/128617098-596b385a-8fde-4437-ac06-d4996a76bade.png">

**Comment by pixelzoom** [comment]
In the Discrete screen it wasn't appropriate to have an expand/collapse button for the top (Amplitudes) chart because the amplitudes are interactive (sliders) and that's the main thing that the student will be working with.  In the Wave Packet screen, the things that the student works with are in the control panel, the top (Amplitudes) chart is NOT interactive, and there is therefore "predictive" value in being able to collapse that chart.

Am I selling it? :)

**Comment by pixelzoom** [comment]
I've added an expand/collapse button for the top chart, see screenshot below.  @arouinfar please review in master.

<img width="1089" alt="screenshot_1136" src="https://user-images.githubusercontent.com/3046552/128646609-ab4d7f54-8c2b-41e2-af31-225c6d4fd52e.png">

**Comment by arouinfar** [comment]
You sold it @pixelzoo; I agree that it would facilitate predictive questioning. Looks good in master, closing.
