### ISSUE TITLE
Address rendering anomalies in the Components and Sum charts.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#121]
The Components (middle) chart is the pain point in the Wave Packet screen. The worst case is with k0=pi/4, where we have 97 components.  To render components smoothly, I'm currently using 1000 points per component.   So for the worst case, we have 97,000 points being computed every time you change the wave packet.

Thanks to Canvas, performance is good - though still probably an issue on Chromebooks. But this issue is not about performance, it's about how it looks.

This approach looks good in most cases, but starts to fall apart when the x-axis is zoomed way out.

Here's an example.  Start the sim, go to the Wave Packet screen, and set controls like this:

<img width="295" alt="screenshot_1144" src="https://user-images.githubusercontent.com/3046552/128756152-15a0b5fa-8381-458f-8ee4-239ba01262e9.png">

Zoom all the way in on the Components x-axis, using the "+" button.  It looks nice:

<img width="876" alt="screenshot_1145" src="https://user-images.githubusercontent.com/3046552/128756226-6169df0a-a942-4106-a799-99d88a2648d7.png">

Zoom out 2 more times. It still looks nice:

<img width="886" alt="screenshot_1146" src="https://user-images.githubusercontent.com/3046552/128756256-2f785703-4df4-44a8-b9a2-e3f026aaa398.png">
<img width="873" alt="screenshot_1147" src="https://user-images.githubusercontent.com/3046552/128756267-0947a048-777e-4d4e-9eea-5551c4c80d30.png">

Zoom out 2 more times. This is where we start to see problems. There are anomalies in the rendering of some waveforms - it looks like there are points above/below the min/max amplitude:

<img width="875" alt="screenshot_1148" src="https://user-images.githubusercontent.com/3046552/128756314-3e2c9eb2-701c-4f9a-88b9-6a8408948ec1.png">
<img width="883" alt="screenshot_1149" src="https://user-images.githubusercontent.com/3046552/128756323-f143d2d9-2ce4-4fe6-a2d5-db3901b81340.png">

Note that the y-axis scale is the same in all of the above screenshots. So there is no problem with the data sets, and the y-axis scale is consistent. The probem is that we're not sampling enough points to accurately show this many periods of the waveforms.

If I increase the number of sample points to 10,000 per component, the worst case (last screenshot above) looks noticeably better:

<img width="882" alt="screenshot_1143" src="https://user-images.githubusercontent.com/3046552/128756693-0a5093f2-3a47-4cb7-aa06-0b486e9ce031.png">
 
... but performance of the sim craters.  We cannot compute 970,000 points (97 components x 10,000 points) and make the sim feel responsive while dragging a slider. 

Options:

(1) Do nothing. Live with the anomalies when the x-axis is zoomed way out.

(2) Reduce the number of zoom levels, so that we don't see the anomalies. How far out do we really need to zoom the x axis?

(3) Investigate using scenery clipping to remove the anomalies. This would erase anything that appears above maxY or below minY. This might look OK.

(4) Investigate an entirely different way of computing and rendering data sets. Maybe always compute 1 period using 1000 points, then replicate it if we need to show multiple periods?  Such an approach would not work with the current plots provided by bamboo.  This would require rewriting a large portion of the sim, creaating sim-specific bamboo extensions,...  It would be expensive, risky, and I'd really hate to do this. 

If (1) is not an option, I think a combinaton of (2) and (3) might work. 

@arouinfar thoughts? Especially on (1) and (2)...

**Comment by pixelzoom** [comment]
> (3) Investigate using scenery clipping to remove the anomalies. This would erase anything that appears above maxY or below minY. This might look OK.

I added this in the above commit, and it's a significant improvement.  The 2 zoom levels that were a problem now look like this:

<img width="806" alt="screenshot_1151" src="https://user-images.githubusercontent.com/3046552/128763762-988e6509-1d86-4502-9a5b-311d209fb033.png">
<img width="812" alt="screenshot_1150" src="https://user-images.githubusercontent.com/3046552/128763771-896aea54-46b9-423f-877b-3c73e404da88.png">

**Comment by pixelzoom** [comment]
Note that I also applied this to the Sum chart. 

Before:

<img width="805" alt="screenshot_1153" src="https://user-images.githubusercontent.com/3046552/128764009-e2c5a79c-6cc7-43e3-9714-f7841bd2524f.png">

After:

<img width="802" alt="screenshot_1152" src="https://user-images.githubusercontent.com/3046552/128763997-2b773201-cf88-479c-b6da-d9d355899e8b.png">

**Comment by pixelzoom** [comment]
@arouinfar please review in master.  Let me know if you think we really need an x-axis zoom of [-8,8].  While there are no artifacts above/below the data set range, there are parts of the sum waveform that don't look as smooth as I'd like.  For example:

<img width="734" alt="screenshot_1155" src="https://user-images.githubusercontent.com/3046552/128764436-771ef8aa-0d39-4d97-9a7d-b428f4f22100.png">

I could live with this if [-8,8] serves a purpose.

**Comment by arouinfar** [comment]
@pixelzoom a range of [-8, 8] on the x-axis is necessary to see multiple wave packets in the Sum chart when the component spacing is pi/4. 
![image](https://user-images.githubusercontent.com/8419308/129071353-d0a70502-13e6-4057-9d48-bd34f06dfdd7.png)

I would prefer that we keep the [-8, 8] zoom level. The scenery clipping apepars to have taken care of most of the rendering issues. The charts are looking really nice in master right now, so I would leave things as-is. We can revisit if the performance is unacceptable on our lower-performing devices.

**Comment by pixelzoom** [comment]
OK, thanks. Closing this issue. We'll create new issue(s) for performance problems.
