### ISSUE TITLE
Review stringTest

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#125]
I've completed all of the standard layout test with the `stringTest` query parameter.  @arouinfar please review in master. Recommended to also run with `?dev`, so that you can verify that nothing goes outside the layoutBounds.

**Comment by arouinfar** [comment]
@pixelzoom things are generally looking good. I'm not seeing any layout issues with `stringTest=long` but `stringTest=double` reveals some issues with overlapping. It seems like the panel is being allowed to expand a bit too much and it comes into contact with the Harmonics x-axis label and zoom buttons.

<img src="https://user-images.githubusercontent.com/8419308/129066906-7e0ab161-6e38-4fa3-ba22-bf982683dd86.png" width=400>

**Comment by pixelzoom** [comment]
That's weird. How the heck could the panel be wider with shorter strings?...  Investigating.

**Comment by pixelzoom** [comment]
Adjusted in the above commits, tested with `stringTest=long` and `stringTest=double`.  @arouinfar please review in master, close if this looks OK.

**Comment by arouinfar** [comment]
👍🏻
