### ISSUE TITLE
Create a dev version for interviews and site visit.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#129]
Here are the links:

PhET: https://phet-dev.colorado.edu/html/fourier-making-waves/1.0.0-dev.40/phet/fourier-making-waves_en_phet.html

PhET-iO: https://phet-dev.colorado.edu/html/fourier-making-waves/1.0.0-dev.40/phet-io/

**Comment by kathy-phet** [comment]
Delivered for site visit!

**Comment by arouinfar** [comment]
Thanks @pixelzoom! I've been using this version for the phet-io review since bayes was down. I don't think there's anything else to do here, so closing.
