### ISSUE TITLE
Performance testing and sign-off

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#131]
This is the standard GitHub issue for performance optimization and sign-off.

**Comment by pixelzoom** [comment]
In Slack, @arouinfar reported good performance of PhET's most challenged iPad:
> Amy Rouinfar  9:57 AM
I spent ~15 minutes on our lowest supported iPad and everything was running smoothly. I have a Chromebook to test later. I’ll comment in the performance testing issue once I wrap up.
>
> Chris Malley  9:58 AM
If you know the names of the devices you’re using, please mention them in the issue.
> 
> Amy Rouinfar  9:58 AM
iPad was Hopper and Chromebook is Lovelace — I’ll include them in the issue

**Comment by arouinfar** [comment]
I did some performance testing on dev.44 on iPad (Hopper) and Lovelace (Chromebook). I did not notice any performance issues that would warrant further optimization.

On Chromebook, there was a slight reduction in quality in the appearance of the Harmonics and Sum graphs on the Discrete screen when in f(x,t) mode. The curves didn't look as crisp when they are stationary, but that could be a bit of an optical illusion or an artifact of a lower-res screen. I don't think it has any much of an impact on usability, but it was something I noticed.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/fourier-making-waves/issues/165#issuecomment-925433196, @jonathanolson reported:
>  Performance is a bit slow on Wave Packet (pi/4 spacing), is it still similar to when performance was signed off?

I replied:
> Were you testing performance with a built version? Performance of the unbuilt version is quite a bit slower, due to assertions. If you were testing with a built version, what was your test platform?
> 
> Nothing significant has changed since performance sign-off in #131.

@jonathanolson replied:
> I was testing performance with a built version.

The Wave Packet screen with pi/4 spacing is indeed the most resource-intensive setting in the sim, since it creates 97 Fourier components. @arouinfar Since you didn't explicity mentioning testing that setting, I'm reopening this issue for confirmation.   Please check that setting, and confirm that performance is acceptable.

**Comment by pixelzoom** [comment]
Top-priority please, because code review is done, and this blocks dev testing.

**Comment by pixelzoom** [comment]
@arouinfar please test performance with [1.0.0-dev.48]( https://phet-dev.colorado.edu/html/fourier-making-waves/1.0.0-dev.48/phet/fourier-making-waves_en_phet.html), which is what is in master currently, and is what @jonathanolson was most likely building.

**Comment by pixelzoom** [comment]
The other performance-critical configuration is in the _Discrete_ screen, when 11 harmonics are animating. Since I don't see explicity mention that this has been tested, @arouinfar please confirm.

To set this up:

1. Got to the _Discrete_ screen.
2. Make sure Harmonics spinner is set to 11
3. Set Waveform combo box to "wave packet" 
4. Set "Function of" combo box to "space & time"

Does the animation run smoothly? Doe it pause at all? (due to Garbage Collection of Vector2) If it does pause, is it tolerable, does it impact the UX?

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/fourier-making-waves/issues/165#issuecomment-925433196, @jonathanolson reported:
>  Performance is a bit slow on Wave Packet (pi/4 spacing), is it still similar to when performance was signed off?

I replied:
> Were you testing performance with a built version? Performance of the unbuilt version is quite a bit slower, due to assertions. If you were testing with a built version, what was your test platform?
> 
> Nothing significant has changed since performance sign-off in #131.

@jonathanolson replied:
> I was testing performance with a built version.

The configration that @jonathanolson mentions is indeed the most performance-critical configuration in the sim. There is a _lot_ of memory allocation involved - it creates 97 Fourier components, 97 plots, and 97,000 Vector2 instances. To test that configuration:

1. Go to the _Wave Packet_ screen
2. Check "Continuous Waveform" and "Waveform Envelope" checkboxes
3. Set "Component Spacing" slider to pi/4
4. Does the sim feel responsive when dragging the other sliders? If there's any "lag" or "sluggishness", is it tolerable, or does it impact the UX?

The other performance-critical configuration is in the _Discrete_ screen, when 11 harmonics are animating. To test that configuration up:

1. Go to the Discrete screen.
2. Make sure "Harmonics" spinner is set to 11
3. Set "Waveform" combo box to "wave packet"
4. Set "Function of" combo box to "space & time"
5. Does the animation run smoothly? Doe it pause at all? If it does pause, is it tolerable, or does it impact the UX?

@arouinfar Since you didn't explicity mentioning testing these configurations, I'm reopening this issue for confirmation that performance is acceptable.  Please test using [1.0.0-dev.48]( https://phet-dev.colorado.edu/html/fourier-making-waves/1.0.0-dev.48/phet/fourier-making-waves_en_phet.html), which is what is currently in master, and is what @jonathanolson was most likely building.

Top-priority please, because code review is done, and this is the sole issue that blocks dev testing.

**Comment by arouinfar** [comment]
@pixelzoom these situations are fine on my ancient Macbook in Chrome and Safari, but I won't have access to an iPad or Chromebook until I'm on campus again (likely not until sometime next week). I'm 99% sure I tested the requested configurations when I did the earlier performance testing to purposefully put the sim in a stressful situation. However, if we want to be sure, we could ask Katie to repeat the tests. I'll let you decide how to proceed.

**Comment by pixelzoom** [comment]
@KatieWoe there are 2 "performance-critical" configurations described in https://github.com/phetsims/fourier-making-waves/issues/131#issuecomment-925836048.  

A couple of requests:

(1) Please comment on whether you tested performance as part of dev-lite test https://github.com/phetsims/qa/issues/701, and whether you tested these specific configurations of the sim.

(2) Check these 2 configurations on a couple of "performance-challenged" platforms -- probably Chromebooks and iPad -- and report:  (a) is there a performance problem, and if so (b) does it impact the UX?

**Comment by pixelzoom** [comment]
@jonathanolson reports that his test platform
> Was a MacBook Pro, latest MacOS, on Chrome.

**Comment by KatieWoe** [comment]
For 1: Performance is not generally tested in a dev-lite test specifically. If issues are seen they are brought up, but it isn't specifically tested for in dev-lite.

Putting issue in issues to verify for 2.

**Comment by kathy-phet** [comment]
I checked these on two Chromebooks at home - one typical of school chromebooks, and one a bit better that I purchased 4 years ago.

For Wave Packet screen, yes it is sluggish, but it is usable. I would not invest more time in optimizing performance. 

For Discrete screen, the wave traveling is speedy with the occasional hiccup. Maybe once every 10 seconds. It does not seem like a problem at all. 

I would give it a "pass". 

@arouinfar - Do you want to unblock this?

**Comment by arouinfar** [comment]
Thanks @kathy-phet. I think we can go ahead and unblock. 

I tested again on my MacBook (same troubleshooting info as https://github.com/phetsims/fourier-making-waves/issues/131#issuecomment-925856958) with `?profiler`. The frame rate dipped into the teens on the Wave Packet screen and the slider thumbs lagged behind my cursor. However, I don't notice the lag while watching the graphs and it certainly didn't *feel* like 14 fps. 

I'll go ahead and remove this issue from the QA Pipeline. @pixelzoom please proceed with dev testing.

**Comment by KatieWoe** [comment]
Noting for https://github.com/phetsims/qa/issues/711 that the Android App had some slow performance with this sim
