### ISSUE TITLE
In space-and-time, should Period tool shows the period for zero-amplitude harmonics? 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#132]
In https://github.com/phetsims/fourier-making-waves/issues/122, @ariel-phet suggested:

> **Discrete Screen**
>...
> 4. If I am in "Function of space and time mode" and set all the amplitudes to zero, the period measurement tool still runs for every period. Not saying this is the wrong behavior, but it could potentially be confusing. Maybe do something like have the clock hand wind but have there be no color fill in this tool if that amplitude is zero? Suggesting that the period could be there but has no contribution currently?

You don't need to set all amplitudes to zero.  In space-and-time, any amplitude that has a zero slider will have a period tool (clock) that corresponds to the harmonic's period.  

My opinion: Period and amplitude are indefendent properties of a harmonic, so I don't see this as being wrong, and I wouldn't change the sim.  If it's confusing, then it's a teachable moment. And I think it would be appropriate to add something about this potential confusion to the Teacher Tips. 

@arouinfar thoughts?

**Comment by ariel-phet** [comment]
Again, just something I noticed that could be a bit confusing. Certainly fine leaving it "as is"

**Comment by arouinfar** [comment]
I agree with @pixelzoom. Let's leave it as-is.
