### ISSUE TITLE
Show/hide the Measurement tools in Wave Packet screen?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#133]
I wish that we had a way to hide the measurement tools in the Wave Packet screen, like in the first screen. I find them to be in the way, and visually distracting/annoying -- especially when the green tool grows exceptionally long, see screenshot below.  Having the tools always visible detracts from the user experience.

There's no room in the control panel, but maybe we could consider checkboxes below the associated graphs? With no text labels, but little icons of the tools?

![screenshot_264](https://user-images.githubusercontent.com/3046552/129422705-800e8a99-bc89-4e54-8bd6-781963948570.png)

**Comment by arouinfar** [comment]
I've also found it a bit annoying to always have the tools out. 

> There's no room in the control panel, but maybe we could consider checkboxes below the associated graphs? With no text labels, but little icons of the tools?

I like this idea, but I might include the λ<sub>1</sub> and k<sub>1</sub> labels. It might be too abstract without them.

**Comment by pixelzoom** [comment]
I can include the labels. But they need to change with the domain, so it's not a matter of just adding some text.

**Comment by arouinfar** [comment]
Oh right, forgot about the need for them to switch with the domain. Regardless, I think the checkbox will be more interpretable with a label.

**Comment by pixelzoom** [comment]
The checkboxes are working nicely. But I ran into problems with where to position them.  

I started by putting the yellow checkbox to the left of the "Continuous Waveform" checkbox, where it would be hidden when the  Amplitudes chart is collapsed.  It looked like this:

<img width="1088" alt="screenshot_1176" src="https://user-images.githubusercontent.com/3046552/129432780-16cb62c5-9ced-4c17-a2e3-4a7c6694277b.png">
  
Now where to put the green checkbox?  I put it to the left of the "Waveform Envelope" checkbox, like this:

<img width="1087" alt="screenshot_1177" src="https://user-images.githubusercontent.com/3046552/129432816-271ab89a-f317-4c7f-a819-e3e3d494a701.png">

This is starting to look crowded.  But there's a bigger problem -- when to hide the green checkbox. The green tool is used for both the Components and Sum charts, and that tool is only hidden when _both_ of those charts are collapsed.  So if I put the green checkbox to the left of the "Waveform Envelope" checkbox, then collapse the Sum chart, I'm going to have this horrible situation:

<img width="1088" alt="screenshot_1178" src="https://user-images.githubusercontent.com/3046552/129432846-7429145b-aa27-49a1-8c0c-86669708d51a.png">

So... For now (and for lack of a better idea), I put these checkboxes where there is space - under the main control panel:
 
<img width="1086" alt="screenshot_1179" src="https://user-images.githubusercontent.com/3046552/129432886-df1013b5-e037-4b04-919c-ddcfcc7dcc1e.png">

@arouinfar @ariel-phet thoughts?

**Comment by pixelzoom** [comment]
Another idea for placement would be in the control panel, in the "Component Spacing" section.  The yellow tool is measuring component spacing, so it clearly belongs in this section.  The green tool measures wavelength or period, which is a function of component spacing, and only changes when component spacing is changed.    This would also be consistent with how we have the checkbox for "width indicators" in the Wave Packet Width section of the control panel.

The screenshot below shows the sim's layoutBounds with `?dev`.  So we have some space about the control panel that we could use. And we could reduce the y margin on the control panel.  This would probably allow us to add both checkboxs to the "Component Spacing" section if we lay them out horizontally.

**Comment by pixelzoom** [comment]
I moved the checkboxes to the "Component Spacing" section of the control panel. Screenshot below, test drive in master.  I had to move the entire control panel up a bit, and I reduced the panel's `yMargin` from 15 to 5.  

This feels like a better starting place for discussion than the other alternatives. 

<img width="1087" alt="screenshot_1181" src="https://user-images.githubusercontent.com/3046552/129433424-9c035249-4431-4b63-921c-25027b0d1532.png">

**Comment by ariel-phet** [comment]
@pixelzoom @arouinfar I definitely like these checkboxes in the control panel. It seems pretty natural where you have put them, I think the other option could be under "Graph Controls" if we wanted those check boxes found later, but certainly they are a measure of component spacing.

**Comment by pixelzoom** [comment]
After sleeping on it (and dreaming about it :) I do like them where they are not, in the Component Spacing section of the control panel.   If we moved them under graph controls, I would lobby to move the "Width Indicators" checkbox there too, for consistency.  But I prefer having the checkboxes in the sections that they are relevant to.

**Comment by arouinfar** [comment]
Putting the measurement tools in the Component Spacing section makes a lot of sense to me. It may also provide a bit of scaffolding for their purpose. The same goes for the Width Indicators -- they could fit under Graph Controls, but I think it makes more sense to group them with the most relevant controls.
