### ISSUE TITLE
Default position of the "green tool" in Wave Packet screen.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#134]
In https://github.com/phetsims/fourier-making-waves/issues/122, @ariel-phet suggested:

> **Wave Packet Screen**
> ...
> 3. Perhaps consider moving the default position of the "Lamda" green measuring tool. Currently if you don't move the tool from its default position and put on the "Width Indicators" they clash a bit. Not a big concern. Or perhaps easier would be to move the Width indicator vertically to the negative portion of the Sum graph (below the x-axis), since there is nothing special about having it on the positive side of the graph. Then this clash would be avoided in the default positions.

Let's refer to the "green tool" and "yellow tool" in this issue.

For reference, here's the default position of the green tool, shown with "Width Indicators" and "Waveform Envelope" checked:

![screenshot_263](https://user-images.githubusercontent.com/3046552/129422455-3f123c47-5a5b-44b5-a362-4d2b8cee82fd.png)

First, I really don't like that I can't hide the measurement tools in the Wave Packet screen. They are often in the way, and visually distracting.  We'll discuss that in https://github.com/phetsims/fourier-making-waves/issues/133.  That said...

I'm also not wild about the default position of the top (green) tool, but for a different reason - it doesn't encourage the student to move it to make a measurement.  The yellow tool is clearly in a default position where it's not making a useful measure, and the student needs to move it.

I have to push back on moving the width indicator below the x axis. That's not at all appropriate when "Waveform Envelope" is checked (as in the above screenshot), because the envelope is totally _above_ the x axis.

I'm thinking that something like what we did in the Java version would be better, screenshot below.  The tool is out of the way, a bit below the graph, and not lined up with anything to be taking a measurement.

@arouinfar @ariel-phet thoughts?

![screenshot_258](https://user-images.githubusercontent.com/3046552/129422502-fa07ef71-ad79-4c70-bee0-8d017cb0d30d.png)

**Comment by ariel-phet** [comment]
Moving the tool to a default position at the bottom of the graph (like the Java sim but perhaps with its points sitting on the axis) also seems like a good solution.

**Comment by arouinfar** [comment]
I like @ariel-phet's suggestion. Let's try it out @pixelzoom.

**Comment by pixelzoom** [comment]
The initial position of the green tool has been move to the bottom of the chart, see screenshot below. @arouinfar please review in master.

<img width="1087" alt="screenshot_1174" src="https://user-images.githubusercontent.com/3046552/129431891-8743cf45-c793-4d82-b851-6b42194e6853.png">

**Comment by arouinfar** [comment]
Looks great, thanks!
