### ISSUE TITLE
Add an icon to "Infinite Harmonics" checkbox.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#135]
In https://github.com/phetsims/fourier-making-waves/issues/122, @ariel-phet suggested:

> **Discrete Screen**
> ...
> I think it might be good to have some sort of icon associated with the "Infinite Harmonics" checkbox, perhaps just a simple gray line that suggests "here is what you would say if you had infinite harmonics" -- basically just a bit more feedback to the user as to what that checkbox means.

Agree. I think icons are great wherever we have room.  

Let's nail down what this "simple gray line" is.  Is it a straight line? A sine wave?...  I do not want to change the icon to match the "Waveform" combo box selection.

**Comment by ariel-phet** [comment]
@pixelzoom @arouinfar I do not think the icon should change to match the waveform.

I think I would either:
1. Choose one waveform and just use an iconic snippet, such as
![waveform](https://user-images.githubusercontent.com/4051174/129426770-393d1eb4-e28f-418e-a9b4-306bc463e28c.PNG)

2. Or just have a straight gray line

**Comment by arouinfar** [comment]
I'd go with a straight gray line to avoid a mismatch between the checkbox icon and the actual curve. A straight line is also typically what we do for legends, which this sort of is.

**Comment by pixelzoom** [comment]
Presumably we'll want to add the same icon to "Continuous Waveform" checkbox and "Waveform Envelope" checkbox in the Wave Packet screen?  Those checkboxes do something similar to "Inifinited Harmonics" checkbox - they show a gray line for some continous plot.

**Comment by pixelzoom** [comment]
All 3 checkboxes that control what I'm calling "secondary waveforms" are now using the same checkbox implementation, which adds a straight-line icon.  The icons and the plots all use the same color (`secondaryWaveformStrokeProperty`) and the same `lineWidth: 4` constant.

Screenshots attached below. @arouinfar please review in master.

<img width="1082" alt="screenshot_1172" src="https://user-images.githubusercontent.com/3046552/129431790-d811bbec-4baa-45dd-8f48-2d1ba612a626.png">
<img width="1088" alt="screenshot_1173" src="https://user-images.githubusercontent.com/3046552/129431793-4b8c985c-920e-401d-91be-003511b8dddc.png">

**Comment by arouinfar** [comment]
The checkboxes all look good, and I think adding the icon makes the interpretation clearer. However, I've noticed that the Infinite Harmonics curve is now black instead of gray, see #140.

@ariel-phet how does it look to you?

**Comment by pixelzoom** [comment]
> However, I've noticed that the Infinite Harmonics curve is now black instead of gray, see #140.

Yeah sorry, that got broken when I combined a bunch of different ProfileColorProperties into a single ProfileColorProperty.  It'll will be fixed pronto.

**Comment by ariel-phet** [comment]
I think that definitely helps. I am going to go ahead and close this issue.
