### ISSUE TITLE
Make the Waveform selection more noticeable.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#136]
In https://github.com/phetsims/fourier-making-waves/issues/122, @ariel-phet suggested:

> **Discrete Screen**
> ...
> 3. I also think some sort of simple icon might be nice to associate with the Waveform combo box (perhaps a simple icon next to the Fourier Series title of the panel. My reasoning is that lets say you are on "Square" -- the moment you tweak a harmonic amplitude the waveform switches back to custom (as it should). But I think the user could still have the impression they are on a Square wave waveform. Having some kind of icon that disappears might help make the fact that you have switched back to custom more obvious.

**Comment by pixelzoom** [comment]
If the user isn't noticing that the Waveform combo box has changed, then I doubt that they'll notice that an icon directly above it has changed. And if there's a problem with the Waveform combo box, we should first try to fix/improve the Waveform combo box, not add something else to an already-busy UI.

Ideas for improving the Waveform combo box, and making the selection more noticeable:
* Make the combo box larger.
* Add icons to the choices.
* Change that combo box's color when "custom" is selected. 

@arouinfar @ariel-phet thought?

**Comment by ariel-phet** [comment]
I think you captured the issue well in the title -- something like a color when you are on "custom" would probably fix my concern. I am open to any of the suggestions -- and I also don't think this is a critical change. Just something I feel could be confusing.

**Comment by ariel** [comment]
Remove me

**Comment by pixelzoom** [comment]
@arouinfar what would you like to try here?

**Comment by arouinfar** [comment]
I appreciate the suggestion, but I don't think we need to do anything. So far, both students in the interview noticed that editing a waveform switched the selection to custom. This is also a pattern we use elsewhere in other sims, such as a  paired NumberControl and ComboBox.

I'll leave this open until interviews wrap up, and close if I don't see any issues.

**Comment by arouinfar** [comment]
I interviewed two more students and didn't see any issues, so we can proceed with the current design. Closing.
