### ISSUE TITLE
How to label the x axis on the Amplitudes chart in Wave Packet screen?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#137]
In https://github.com/phetsims/fourier-making-waves/issues/122, @ariel-phet suggested:

> **Wave Packet Screen**
> ...
> 2. I would advocate for finding a way to get *k* rad/m label on one line. It just looks odd currently. I would advocate for just using "k" -- the units are in the control panel and I don't think you are losing much by removing the from the graph axis label in this case. 

For context, see red arrow in the screenshot below.

I'm OK with removing the units, or leaving it as is.  

Putting the units on the same line as "k" would require making the charts noticeable narrower, and we'll have a lot of empty space to the right of the charts.  Keep in mind that this has to be translatable.

@arouinfar how would you like to proceed.

![screenshot_266](https://user-images.githubusercontent.com/3046552/129423965-810e6f52-3238-4058-8e62-e3c46ae0d79b.jpg)

**Comment by arouinfar** [comment]
Let's axe the units @pixelzoom.

**Comment by pixelzoom** [comment]
Units have been removed from the x-axis label for the Amplitudes chart.  And I increased the font size for axis labels by 1 point.  @arouinfar please review in master.

**Comment by arouinfar** [comment]
Thanks @pixelzoom, looks good.
