### ISSUE TITLE
Increase font size for "sin" and "cos" radio button labels.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#138]
In https://github.com/phetsims/fourier-making-waves/issues/122, @ariel-phet suggested:

> **DIscrete Screen**
> ...
> 1. I think the "sin" and "cos" font on this screen (and wave packet) under Graph controls could be bumped up. I think the font could be nearly the same sice as what you see in the "Function of" combo box. I am mainly thinking of a use where this sim is projected and those might be a bit small.
...
>  **Wave Packet**
> 
> 1. As noted above, increasing the font size of "sin" and "cos"

**Comment by pixelzoom** [comment]
I'll go ahead and do this, then have @arouinfar review.

**Comment by pixelzoom** [comment]
I increased the size by 2 points.  Compare master to [1.0.0-dev.40](https://phet-dev.colorado.edu/html/fourier-making-waves/1.0.0-dev.40/phet/fourier-making-waves_en_phet.html).  @arouinfar please review.

**Comment by arouinfar** [comment]
> I increased the size by 2 points.

Looks good to me! It's definitely much more readable without being overly large.
