### ISSUE TITLE
ComboBoxItems needed `tandemName`

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#141]
All ComboBoxItems in this sim needed `tandemName`.  Also consider opening a sun issue to make sure this is the case when ComboBox is instrumented, because this (according to @arouinfar) seems to a common developer error.

**Comment by pixelzoom** [comment]
Done in the above commit.  I also fixed a couple of bugs in the "Function of" combo box, where the symbol shown for an item was incorrect.

@arouinfar please review in master.  The 3 combo boxes are:

fourierMakingWaves.discreteScreen.view.controlPanel.fourierSeriesSubpanel.waveformComboBox
fourierMakingWaves.discreteScreen.view.controlPanel.graphControlsSubpanel.equationComboBox
fourierMakingWaves.discreteScreen.view.controlPanel.graphControlsSubpanel.functionOfComboBox

**Comment by arouinfar** [comment]
Looks good @pixelzoom.

Leaving open and self-assigned to create a sun issue.

**Comment by arouinfar** [comment]
Sun issue created, so closing this one.
