### ISSUE TITLE
Make ?rewardScore public

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#143]
From https://github.com/phetsims/fourier-making-waves/issues/4#issuecomment-846256591:
> Change the condition for triggering the RewardNode (e.g. lower the threshold to 5 stars)

... so make the `rewardScore` query parameter public.

**Comment by pixelzoom** [comment]
Done in the above commit. `rewardScore` must be an integer > 0.  If it's not, you'll see an OopsDialog like the example below. @arouinfar please verify in master.

<img width="552" alt="screenshot_1188" src="https://user-images.githubusercontent.com/3046552/129639331-05477829-6838-499c-9132-9d500423bfa4.png">

**Comment by arouinfar** [comment]
Looks good in master, thanks!
