### ISSUE TITLE
Add a `gameLevels` query parameter.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#145]
... like in EqualityExplorerQueryParameters:

```js
  // The levels to show in the game (Solve It!) screen.
  // The level numbers must be unique, valid, and in ascending order.
  // See https://github.com/phetsims/equality-explorer/issues/165
  gameLevels: {
    public: true,
    type: 'array',
    elementSchema: {
      type: 'number',
      isValidValue: Number.isInteger
    },
    defaultValue: null,
    isValidValue: array => {
      return ( array === null ) || (
        array.length > 0 &&
        // unique level numbers
        array.length === _.uniq( array ).length &&
        // valid level numbers
        _.every( array, element => element > 0 && element <= EqualityExplorerConstants.NUMBER_OF_GAME_LEVELS ) &&
        // sorted by ascending level number
        _.every( array, ( value, index, array ) => ( index === 0 || array[ index - 1 ] <= value ) )
      );
    }
  },
```

**Comment by pixelzoom** [comment]
Handle layout of level-selection buttons grid, for query parameter and when hidden from Studio.

**Comment by pixelzoom** [comment]
I've added the `gameLevels` query parameter, but it's not hooked up to anything.  I'm concerned that omitting levels may cause PhET-iO API validation to fail.

In WaveGameModel.js, I was going to do something like this to filter out the unwanted game levels:

```js
this.levels = [
   ...
];

// Filter levels by gameLevels query parameter.
// See https://github.com/phetsims/equality-explorer/issues/165
if ( FMWQueryParameters.gameLevels ) {
  this.levels = _.filter( this.levels, level =>
    FMWQueryParameters.gameLevels.includes( level.levelNumber )
  );
}

    // @public {Property.<null|WaveGameLevel>} the selected game level
    // null means 'no selection' and causes the view to return to the level-selection UI
    this.levelProperty = new Property( null, {
      validValues: [ null, ...this.levels ],
      phetioType: Property.PropertyIO( NullableIO( WaveGameLevel.WaveGameLevelIO ) ),
      tandem: options.tandem.createTandem( 'levelProperty' ),
      phetioDocumentation: 'The level currently selected in the Wave Game, null if no level is selected.'
    } );
  }
```

My concern here is that `validValues` for `levelProperty` may be included in state and/or the PhET-iO API. ]

If I include the omitted levels in `validValues`, they'll appear as choices in Studio:

<img width="662" alt="screenshot_1192" src="https://user-images.githubusercontent.com/3046552/129653347-ca81164d-561e-457c-90ca-28b90352f1c0.png">

Another option would be to include all levels in the model, but exclude levels from the view, by hiding LevelSelectionButton instances in WaveGameLevelSelectionNode.  If the client sets levelProperty to one of the excluded levels, that excluded level will be shown, but presumanbly they shouldn't do that if they have excluded a level via query parameter.

@samreid @zepumph what is the recommended way of handling this?

**Comment by pixelzoom** [comment]
> Another option would be to include all levels in the model, but exclude levels from the view, by hiding LevelSelectionButton instances in WaveGameLevelSelectionNode. 

I went with this option, implemented in WaveGameLevelSelectionNode:

```js
    // Hide buttons for levels that are not included in gameLevels query parameter.
    // We must still create these buttons so that we don't change the PhET-iO API.
    if ( FMWQueryParameters.gameLevels ) {
      levelSelectionButtons.forEach( button => {
        button.visible = FMWQueryParameters.gameLevels.includes( button.level.levelNumber );
      } );
    }
```

With `?gameLevels=1,2,4`, the Wave Game screen looks like this:

<img width="460" alt="screenshot_1193" src="https://user-images.githubusercontent.com/3046552/129654521-9a5bd452-d876-43e5-9d75-0ff487d300a8.png">

The client still choose one of the "not included" levels like this:

<img width="760" alt="screenshot_1194" src="https://user-images.githubusercontent.com/3046552/129654584-4dc75498-b566-421a-b4be-c02f45b1437a.png">

... which will show that level, like this:

<img width="627" alt="screenshot_1195" src="https://user-images.githubusercontent.com/3046552/129654624-74006ee2-030e-4456-beaf-c8e2bc667e1b.png">

This all seems less than idea, and potentially confusing. But it seems like the only option that doesn't change the PhET-iO API.  And I guess we can rationalize that this is another one of those cases where we just tell the client "don't do that".  

@samreid @zepumph @arouinfar thoughts?

**Comment by pixelzoom** [comment]
High priority because this sim needs to be in dev testing in < 2 weeks.

**Comment by pixelzoom** [comment]
Discussed with @samreid via Zoom:

* This seems like the best option: Make it so that the student can't get to the levels, but the instructional designer still can.  
* The instructional designer is the one who sets `?gameLevels`, so they should know not to select excluded levels.
* Keeping things static is a good approach because be avoid `PhetioDynamicElementContainer`.

So going with this approach. @arouinfar please review to see if this is an acceptable design.

**Comment by arouinfar** [comment]
The `gameLevels` query parameter is working nicely. I think it's a reasonable expectation that clients shouldn't set the `levelProperty` to a level that is hidden from the student view. I've also made a note in #149 to document this in the client guides.
