### ISSUE TITLE
Translation and display of symbols

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#15]
Here's the set of symbols used in Fourier.  Please indicate which symbols need to be translatable, and which need to be displayed in math font, by putting an 'X' in the appropriate column in the table.

| symbol | description | translatable? | math font? | italic? |
| :--- | :--- | --- | --- | --- |
| A | amplitude | x | | |
| cos | cosine | x | | |
| f | frequency | x | x | x |
| F | function of frequency | x | | |
| λ | wavelength | x | x | |
| k | wave number | x | x | x |
| L | string length, if this were a plucked string | x | | |
| n | mode, order, harmonic number | x | x | x |
| π | pi |  | x | |
| σ | width of the Gaussian wave packet (dx) | x | x | |
| Σ | summation |  | x | |
| sin | sine | x | | |
| t | time | x | x | x |
| T | sampling period, or period of the 1st harmonic | x | | |
| ω | angular frequency | x | x | |
| x | position in space along L | x | x | x |

**Comment by pixelzoom** [comment]
The above symbols are currently _not_ translatable, and _not_ displayed in math font.  They have been factored out into FMWSymbols.js.  Displaying them in math font, like (for example the "x" in "Mode (x)") will be a lot of work.

**Comment by pixelzoom** [comment]
Raising priority to high.  These symbols are everywhere in this sim.  The more I flesh the sim out, the more I'm going to have to change.

**Comment by pixelzoom** [comment]
Whether to use `style: 'italic'` is now an option, so I've added that to the above table.  The default is `style: 'italic'`, but some symbols (e.g. summation) look better with `style: 'normal'`.

**Comment by pixelzoom** [comment]
12/3/2020 design meeting @arouinfar @ariel-phet @kathy-phet @pixelzoom 

translation:
* @ariel-phet suggested running Java versions for languages where we know people have changed math symbols (e.g. Greek) to see if anyone has translated symbols.  If not, then make them all non-translatable.
* @kathy-phet suggested sensing the list to translators to see what they have to say. Would they translate any of the above symbols?
* @arouinfar make symbols translatable, leave it up to the translator.  <=== DO THIS

font:
* @pixelzoom will make a first pass, @arouinfar will review and suggest changes

**Comment by pixelzoom** [comment]
In the above commit, I made all symbols translatable _except_ π and Σ.  I can easily make these translatable, but these 2 seemed generally inappropriate to translate. 

I applied math font and italics as shown in the table above. Let me know if you'd like any changes, it's trivial to change.

Over to @arouinfar for review.

**Comment by pixelzoom** [comment]
Btw.. My choices for math font and italics were guided by aesthetics, but happened to end up conforming to the following:

* Greek letters are in math font, no italics
* Roman capital letters are in normal font, no italics
* Roman lowercase letters are in math font, with italics

**Comment by arouinfar** [comment]
@pixelzoom I like the formatting choices you've made with the symbols. I don't have changes to request, so closing.
