### ISSUE TITLE
Does y-axis auto scaling cause any usability or pedagogical problems?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#150]
Over in https://github.com/phetsims/fourier-making-waves/issues/139, we removed the Auto Scale checkbox and y-zoom buttons on the Sum graph in the Discrete screen.  Scaling of the y-axis now occurs automatically to fit the peak amplitude, as it does for the Sum chart in the Wave Game screen, and all 3 charts in the Wave Packet screen.  

In that same issue, we also discussed whether to add "(Auto-Scaled)", or something similar, to some or all of the charts that auto scale. For example, "Sum (Auto-Scaled)".

In https://github.com/phetsims/fourier-making-waves/issues/139#issuecomment-901345690, @kathy-phet suggested:
> I would suggest leaving it as "Sum" and then seeing if there are interpretation issues in the interviews - noticing this change.

Assigning to @arouinfar to include in interviews.

**Comment by arouinfar** [comment]
There have been two interviews so far, both were STEM majors and had taken calculus or higher. Neither was familiar with Fourier series/transforms, but they did not have any difficulty interpreting the representations in the sim. 
* The first student used dev.43 which contains the Auto Scale checkbox. The student found the checkbox when first making sense of the Sum graph and left it on throughout the rest of their exploration. They correctly identified what was happening to the y-axis and expressed a preference for the autoscaling behavior.
* The second student used dev.44 which automatically scales the y-axis of the Sum graph. They found the x-axis zoom buttons fairly early on and realized that it affected both the Harmonics and Sum graphs. It took a bit of time for the student to create a situation where the Sum graph re-scaled. However, they did notice what was happening once the graph lines started increasing in density.

**Comment by arouinfar** [comment]
I interviewed two more students and didn't see any issues with the autoscale behavior in dev.44, so I think this is safe to close.
