### ISSUE TITLE
Measurement Tools: disable spinner when checkbox is unchecked

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#151]
@arouinfar change request, based on interviews:

For the Discrete screen Measurement Tools, if a checkbox is unchecked, disable the associated spinner.

**Comment by pixelzoom** [comment]
Done in the above commit. @arouinfar please verify in master.

**Comment by arouinfar** [comment]
Looks good in master!

In interviews, students had trouble figuring out how to turn on the measurement tools on the Discrete screen. All four students first tried the NumberSpinner. It's more attractive than the checkbox and naturally gets more attention. Two students quickly realized they needed to turn on the checkbox, but the other two expressed confusion and were eventually prompted to, "try turning on the tool". 

When students encountered other disabled controls, they usually tried to figure out how to enable them. By disabling the NumberSpinner, I think students will be more likely to find the checkbox.
