### ISSUE TITLE
Reduce reward score to 5.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#152]
@arouinfar change request, based on interviews:

Reduced the reward score to 5.  The current value (10) is too difficult

**Comment by pixelzoom** [comment]
Done in the about commit. @arouinfar please verify in master.

**Comment by arouinfar** [comment]
Looks good @pixelzoom.

Interview observations:
* No one triggered the RewardNode in interviews.
* Students generally solve 3-5 challenges before trying the next level. 
* Two students wanted to know how long the game would continue, but after 6-7 stars assumed it would go on forever.
* Higher levels are more time-consuming, so solving 10 challenges just isn't reasonable.
