### ISSUE TITLE
Enable the “Show Answer” button after one “Check Answer” attempt.  

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#153]
@arouinfar change request, based on interviews:

In the Wave Game screen: Enable the “Show Answer” button after one “Check Answer” attempt.  It currently requires 2 pressed.

Relevant code in WaveGameLevelNode:

```js
const CHECK_ANSWER_PRESSES = 2; // number of 'Check Answer' button presses required to enabled the 'Show Answers' button
```

**Comment by pixelzoom** [comment]
Done in the above commit. @arouinfar please verify in master.

**Comment by arouinfar** [comment]
Looks good in master, thanks @pixelzoom!

I requested this change based on interview observations. It's very clear to students when their answer is correct, and they are unlikely to press the "Check Answer" until there is a perfect match. However, there are times when a student wants to see the answer after having attempted the challenge. They knowingly check an incorrect answer hoping to activate the Show Answer button, but are confused when the button is still inactive.
