### ISSUE TITLE
“Wavelength” checkbox label is scaled down

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#154]
Reported by @arouinfar:

In the Discrete screen's control panel, the “Wavelength” checkbox label is scaled down:

<img width="255" alt="screenshot_1203" src="https://user-images.githubusercontent.com/3046552/130476465-a13da1e3-76a0-4ecb-8967-0ebc1ca02987.png">

**Comment by pixelzoom** [comment]
Fixed in the above commit. Screenshot below for normal, `stringTest=double`, and `stringTest=long`.  @arouinfar please verify in master.

<img width="323" alt="screenshot_1206" src="https://user-images.githubusercontent.com/3046552/130486818-a172c604-dcad-430a-9666-36c024adb5f0.png">
<img width="353" alt="screenshot_1204" src="https://user-images.githubusercontent.com/3046552/130486845-8fc88bbd-4aa8-4dea-8e00-28a5b1fdcb11.png">
<img width="305" alt="screenshot_1205" src="https://user-images.githubusercontent.com/3046552/130486852-0702b0e4-3583-4e69-8df8-cae4cb9d5963.png">

**Comment by arouinfar** [comment]
Looks good, thanks!
