### ISSUE TITLE
Make the infinity symbol larger.

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/fourier-making-waves#156]
Adding a list of pixel polishes. Currently at 1 polish: 

- [ ] Make the infinity symbol larger font size, if possible. It's hard to see, and much smaller than in the first screen values. 
![image](https://user-images.githubusercontent.com/5096804/130515373-66f91e1f-5270-491c-b17c-c5f329b3c219.png)

**Comment by pixelzoom** [comment]
Related to https://github.com/phetsims/fourier-making-waves/issues/122.

**Comment by pixelzoom** [comment]
I've increased the size of the infinity symbols, see screenshots below.   @arouinfar @kathy-phet please review in master. 

FYI, there are a couple of things about this that are a compromise:

* The "n =" and the ∞ symbol are one RichText node, sharing one font size.  The "n =" feels a little large to me, but the ∞ feels about right.
*  The vertical alignment of the characters in "n = -∞" is not great. All of those characters are aligned on their baselines. And if I start pushing them around by pixels to make it look better, they are very likely to be messed up with diffferent fonts, in different languages.  So it's better to live with it.
* The code that renders a summation/integral symbol is SumSymbolNode. It's used in both Discrete and Wave Packet screens. In the Discrete screen, the min/max are numbers. In the Wave Packet screen, the min/max are -∞ and ∞.  Those min/max have totally different bounds issues, so the layout is a compromise.  I'd prefer the ∞ to be a bit closer to the top of the sum symbol, but then the numeric max is too close.  So the layout is a compromise.

For k1 > 0:
<img width="246" alt="screenshot_1209" src="https://user-images.githubusercontent.com/3046552/130528652-8f8d85d3-1675-4c2f-80cd-0e1c70b847ef.png">

For k1 = 0:
<img width="259" alt="screenshot_1210" src="https://user-images.githubusercontent.com/3046552/130528796-52f12424-d4fc-4b03-bd4b-f3d2dabdf9ef.png">

**Comment by kathy-phet** [comment]
Checked on master. Looks great! Thanks.

**Comment by arouinfar** [comment]
I think this is a good compromise @pixelzoom. I do agree that the n looks a bit large, but I think it's preferable to the too-small infinity symbol.
