### ISSUE TITLE
Default checkboxes to 'on' in Wave Packet screen.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#157]
Related to #122....

Minor change requests for Wave Packet screen:

* Default “Continuous Waveform” to on.
* Default “Waveform Envelope” to on.

**Comment by pixelzoom** [comment]
Done in the above commit, and tested with Reset All button.

@arouinfar please verify in master.

**Comment by arouinfar** [comment]
The Continuous Waveform is very helpful when making sense of the amplitudes chart, especially when the distribution is off-center, and I think this is a great change.

I'm was a bit more on the fence about the default state of the Waveform Envelope checkbox. I generally prefer to have students turn things on themselves, but there are plenty of other things for students to do on this screen. The Waveform Envelope makes it easier to see that the wavelength/period is unaffected by shifting the wave packet center, which is a detail that can easily be overlooked.
