### ISSUE TITLE
Adjust ranges in Wave Packet screen to avoid under-sampled states.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#158]
Related to #122 (Wave Packet screen review)...  Zoom meeting with @arouinfar and @kathy-phet.

The range of some of the controls allows the sim to get into an "under sampled" state, where odd/confusing conditions exist.  Those states exist at the extremes of these ranges, and students have a tendency to move controls (sliders in this case) to their extremes.   So the following changes were requested:

- [x] Change range of Component Spacing to [0,pi]
- [x] Change range of Wave Packet Width (standard deviation) to [pi,4pi]
- [x] Change range of Wave Packet Width (conjugate standard deviation) to [1/(4pi),1/pi].  
- [x] If possible, add 1/(2pi) tick mark for conjugate standard deviation.
- [x] Verify that width indicators do not go off the top of the charts.

**Comment by pixelzoom** [comment]
@arouinfar @kathy-phet these changes are ready for review in master.

**Comment by pixelzoom** [comment]
FYI, this was a scenario that previously made the width indicators go off their charts. And these settings are no longer possible.

<img width="1147" alt="screenshot_1208" src="https://user-images.githubusercontent.com/3046552/130525647-2d29d009-b2e5-4c05-98ea-d63d2ea76b5f.png">

**Comment by kathy-phet** [comment]
I really like these adjustments. Thanks!

**Comment by arouinfar** [comment]
I'm really loving these changes! I'm unable to reproduce the rogue width indicators and I haven't seen any issues with undersampling with the new ranges.

**Comment by pixelzoom** [comment]
Agreed, I think this is one of the most import deviations that we've made from the Java version.
