### ISSUE TITLE
Use a fixed y-axis scale for Sum chart in Wave Packet screen.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#159]
Related to #122 (Wave Packet screen review), Zoom meeting with @arouinfar and @kathy-phet.

In the Wave Packet screen, use a fixed y-axis scale of [-1,1] for the Sum chart.  Do not autoscale to the peak amplutude.

**Comment by pixelzoom** [comment]
Done in the above commit. The Sum chart's y-axis scale is now fixed.  I added a bit of padding above/below the range [-1,1], so the axis' actual range is [-1.1,1.1].  See screenshot below. 

@arouinfar please verify in master.

<img width="763" alt="screenshot_1212" src="https://user-images.githubusercontent.com/3046552/130531443-26f03c1d-0f88-4038-8dfa-7d6fd9f06cb2.png">

**Comment by arouinfar** [comment]
Looks good, thanks!
