### ISSUE TITLE
"snap" requirements for amplitude sliders

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#17]
Amplitude sliders currently snap to 0.05 intervals, except at the min (1.27) and max (1.27).  It's trivial to change the interval.  

@arouinfar please test-drive in master.  Would you like any changes?

**Comment by pixelzoom** [comment]
You might want to get feedback from @kathy-phet too, since she suggested this feature in a design discussion.

**Comment by arouinfar** [comment]
We decided to increase the range to [-1.5, 1.5], see https://github.com/phetsims/fourier-making-waves/issues/22.

@pixelzoom can you set the snap interval to 0.05? It looks like it's back to 0.01 in master.

**Comment by pixelzoom** [comment]
Snapping occurs when you _release_ a slider, not while you're dragging it, and I verified that it's still set to 0.05 in master.  

The change in value as you drag is something totally different.  We don't have a way to set that to 0.05, we can only specify the number of decimal places, which is currently 2 (thus a delta of 0.01).   And if we did somehow manage to set the delta to 0.05, we'd likely have problems when the user enters a keypad value that is not a multiple of 0.05.

**Comment by pixelzoom** [comment]
Oh wait... I think I understand what you're asking for - you want dragging to snap to 0.05 increments.  It seems like we should be able to do that, and I've (dimly) recall doing it before.  So let me investigate.

**Comment by pixelzoom** [comment]
OK, amplitude sliders now snap to 0.05 interval while dragging.  Slider has a `constrainValue` option that supports this.  In case min/max ever change to something that's not a multiple of 0.05, this snapping does not apply to the min/max values.

Back to @arouinfar to review in master.

**Comment by arouinfar** [comment]
Yep, `constrainValue` was exactly what I was thinking about! Looks good in master, closing.
