### ISSUE TITLE
Reset-all on Wave Packet screen doesn't restore amplitude/sum accordion box collapse

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/fourier-making-waves#172]
Starting configuration on Wave Packet screen:
![image](https://user-images.githubusercontent.com/480878/132549168-0f582dbd-98af-4e3f-9a12-9b4c235615f3.png)

Reset-all won't take this configuration back to the starting configuration:
![image](https://user-images.githubusercontent.com/480878/132549241-0583ec83-2af7-456f-be37-5149ce7458cb.png)

To reproduce:
1. Load sim, Wave Packet screen
2. Collapse Amplitude (top) and Sum (bottom) accordion boxes
3. Press reset-all.

Expected: accordion boxes expand again
Actual: nothing changes

**Comment by pixelzoom** [comment]
Thanks. I overrode `rest` and forgot to call `super.reset`.  Fixed in the above commit. Closing.
