### ISSUE TITLE
Chart scaling documentation

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/fourier-making-waves#173]
In the implementation notes:

> All charts automatically adjust their y-axis scale to fit the peak amplitude that is displayed. (PhET typically refers to this behavior as auto-scaling.) The exception to this is the Sum chart in the the Wave Game screen; that chart adjusts its y-axis scale to match the answer (pink waveform) but ignores the user's guess (black waveform).

It looks like there's a minimum y-axis scale of -1.5 to 1.5 on many charts (harmonics, and the Sum chart in the game as described above). Is there a way the documentation could be updated for that (unless I'm wrong)?

Review issue: https://github.com/phetsims/fourier-making-waves/issues/165

**Comment by pixelzoom** [comment]
You're correct -- some of the charts have a minimum y-axis scale of [-1.5,1.5].   I'll ammend implementation-notes.md.

**Comment by pixelzoom** [comment]
Revised in the above commit, here's the new paragraph:

>  Many of the charts automatically scale their y-axis to fit the peak amplitude, with a bit of "padding"
added to the peak. PhET typically refers to this behavior as _auto-scaling_. In the **Discrete** screen, the Sum chart auto-scales, with a minimum range of [-1.5,1.5]. In the **Wave Game** screen, the Sum chart auto-scales to fit the answer (pink waveform), again with a minimum range of [-1.5,1.5]. In the **Wave Packet** screen, all three charts auto-scale.

Back to @jonathanolson for review. Feel free to close or suggest clearer language.

**Comment by pixelzoom** [comment]
Oops, revised again.  Only 2 of the charts auto-scale on the Wave Packet screen.  Here's the new paragraph:

> Many of the charts automatically scale their y-axis to fit the peak amplitude, with a bit of "padding"
added to the peak. PhET typically refers to this behavior as _auto-scaling_. In the **Discrete** screen, the Sum chart auto-scales, with a minimum range of [-1.5,1.5]. In the **Wave Game** screen, the _Sum_ chart auto-scales to fit the answer (pink waveform), again with a minimum range of [-1.5,1.5]. In the **Wave Packet** screen, the Amplitudes and Components charts auto-scale, with no minimum range.

**Comment by jonathanolson** [comment]
Looks great! Thanks.
