### ISSUE TITLE
Create screenshots

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#177]
We'll need the primary and alternate screenshots for this sim.

**Comment by pixelzoom** [comment]
@arouinfar what's the status of screenshots? Since we're going to skip dev test and go directly to RC... It would be a lot easier if these screenshots were in the release branch, so I don't have to patch it later.

**Comment by arouinfar** [comment]
For some reason, I still don't see the assets directory, so here are the screenshots @pixelzoom
[assets.zip](https://github.com/phetsims/fourier-making-waves/files/7239537/assets.zip)

**Comment by pixelzoom** [comment]
Thanks @arouinfar.  Screenshots have been added in the above commit.  Please review in master, then close.

**Comment by pixelzoom** [comment]
Oops... I see why you could find assets/.   I created it under fourier-making-waves/js/assests.  I'll need to fix this.

**Comment by pixelzoom** [comment]
Fixed in the above commit, ready for review.

**Comment by arouinfar** [comment]
Thanks @pixelzoom, looks good
