### ISSUE TITLE
Team testing prior to RC

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#178]
Dev-lit testing https://github.com/phetsims/qa/issues/701 and code review #165 did not reveal any problems with this sim. We're in excellent shape, so we're going to skip dev testing and go right to RC.  

Before RC, the consensus was that the team members would exercise the sim. When you have completed testing, please check your name off below. Also please indicate which platforms you tested.  If you find any new problems, please create new issues, and link them to this issue. 

- [x] @arouinfar 
- [x] @kathy-phet 
- [x] @ariel-phet 
- [x] @pixelzoom 
- [x] QA team

Please complete this task by the end of the day on Monday, 9/27.

**Comment by kathy-phet** [comment]
A few things I found: 

- [ ] for the amplitude sliders, when you click in the track, keep mouse down, and move up and down, you do not get the clicking slider sounds (I don't naturally do this on the computer version, but this happens a lot on a touch pad device like iPads)

- [ ] Design question (@arouinfar) - Should "Infinite Harmonics" checkbox be available when on "Sinusoidal". It feels like it should be disabled for Sinusoidal, just like it is for custom.

- [ ] (iPad only bug?) when Component spacing is set to 0 spacing, k1 (yellow) shows zero which is correct, but a small Lambda1 green box in the lower right of the screen (seems like this is a bug/unitentional). There is also inconsistency as I change the component spacing. I can get the lamda1=infinity to be on the graph. But if I reset, then change spacing to 0, then check k1 and lambda1. I don't see any of this on my Windows machine. 

(Gotta go)

**Comment by pixelzoom** [comment]
From https://github.com/phetsims/fourier-making-waves/issues/178#issue-1005939816:
>  If you find any new problems, please create new issues, and link them to this issue.

I have created GitHub issues for the checklist items items in https://github.com/phetsims/fourier-making-waves/issues/178#issuecomment-926970316.  Please do the same for anything else that you find. Putting comments in this issue creates additional work for me, makes it more difficult to track these issues, and makes it difficult to locate similar report/decisions in the future.

**Comment by ariel-phet** [comment]
I finished my testing, I will create a few issues -- nothing is a "show stopper" but there are a few minor issues usability issues that I will document. The wave game works great now, no issues on that screen.

**Comment by pixelzoom** [comment]
> ...  please check your name off below. Also please indicate which platforms you tested. 

@ariel-phet could you please list the platform(s) that you tested? I'd like to know (and document) our coverage.

**Comment by kathy-phet** [comment]
I invited the QA team to do some testing on master too - to flesh out as many issues as possible in this rapid test.

**Comment by pixelzoom** [comment]
I've completed my testing, on these devices:

MacBookPro16,1 + macOS 11.5 + Chrome 94.0.4606.61
MacBookPro16,1 + macOS 11.5 + Safari 14.1.2 (16611.3.10.1.3)
iPad6 + iOS 14.8 + mobile Safari

**Comment by pixelzoom** [comment]
> I invited the QA team to do some testing on master too - to flesh out as many issues as possible in this rapid test.

@KatieWoe when QA is done, please check the "QA team" item above, and comment on which platforms (machine + OS + browser) you tested.

**Comment by ariel-phet** [comment]
@pixelzoom testing was on Windows 10 chrome (fast desktop) and no other platforms

**Comment by KatieWoe** [comment]
iPadOS 15, MacBook Air (m1 chip) 11.5.2 + chrome 93.0.4577.82 and safari 14.1.2, and win10 chrome for various members of QA

**Comment by arouinfar** [comment]
Here are the configurations I tested:
Mid-2014 MacBook Pro, macOS 10.15.7 + Chrome 94.0.4606.54
Mid-2014 MacBook Pro, macOS 10.15.7 + Safari 14.0.2 (15610.3.7.1.10, 15610)

I found one issue with the focus order, referenced above.

**Comment by kathy-phet** [comment]
Here are my systems: 
Dell Latitude 7490, Microsoft Windows 10, Version 10.0.19042 Build 19042, Google Chrome Version 93.0.4577.82 (Official Build) (64-bit)
iPad (6th generation) 14.4.2 Safari 14 (Catalina) 14.0.3
