### ISSUE TITLE
No support for sound in the track of Amplitude sliders

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#179]
From https://github.com/phetsims/fourier-making-waves/issues/178#issuecomment-926970316, reported by @kathy-phet:

>  - [ ] for the amplitude sliders, when you click in the track, keep mouse down, and move up and down, you do not get the clicking slider sounds (I don't naturally do this on the computer version, but this happens a lot on a touch pad device like iPads)

**Comment by pixelzoom** [comment]
The team's decison on 7/29/21 was to defer any additional work on sound for Fourier sliders, and wait for general support in Slider, see https://github.com/phetsims/fourier-making-waves/issues/56#issuecomment-881034899.   

The current implementation of sound for the amplitude sliders is based on Wave Interference, at the request of the design team. That implementation has no support for interactions with the slider track, as noted in https://github.com/phetsims/wave-interference/issues/519, and there has been no progress on that issue. 

The need to support track sounds in common-code Slider.js is also noted in https://github.com/phetsims/sun/issues/697#issuecomment-827962942, and there has been no progress on that issue. 

So... I recommend doing nothing here. But if you'd like to do additional work on slider sound for Fourier, please reopen https://github.com/phetsims/fourier-making-waves/issues/56.  @arouinfar @kathy-phet please advise how you'd like to proceed.

**Comment by kathy-phet** [comment]
@pixelzoom - So I understand that there is no sound support for when you "click in the track". The thing that sort of surprised me was after I clicked in the track, and the slider jumped to meet my mouse, I then started to wiggle the slider up and down without releasing and it still did not make any clicking sound even though this is a continuous motion now. Is that also expected and part of the "no sound when clicking in track" behavior? 

If this is an associated limitation to the just the single jump not having clicks and isn't easy to fix, then I think we should just publish it as "won't fix". And address it in the slider work to come.

**Comment by pixelzoom** [comment]
When you clicking in the track and drag, you're not actually dragging the thumb.  The track is handling input events, setting the Property value, and the thumb just stays synchronized with the Property value. This is how Slider.js works, not specific to Fourier's amplitude slider.

I checked Wave Interference, and sound does work when dragging in the track.  I haven't made a deep dive. But I'm guessing that the difference is that Fourier provides a custom thumb and track, while Wave Interference uses the default thumb and track.  And the "fix" is likely to require changes to Slider.js, and would be more appropriate to be handled as part of 
https://github.com/phetsims/sun/issues/697 (Slider API for sound). 

Now that you have that information... Do you want me to move forward with this?

**Comment by kathy-phet** [comment]
@arouinfar should weigh in, but I am OK with publishing with the current behavior.

**Comment by pixelzoom** [comment]
I looked into this further, and the problem is indeed in Slider.  If you provide a custom track, you are on your own - none of the sound stuff that you've provided for that track gets propagated to the custom track.  I've reported this in https://github.com/phetsims/sun/issues/697#issuecomment-928149768.

Now that I understand the problem, I could work around it.  It will take 1-2 hours.

**Comment by pixelzoom** [comment]
> Now that I understand the problem, I could work around it. Estimate is 1-2 hours.

I'm going to go for it.

**Comment by pixelzoom** [comment]
Sound support for the track has been added in the above commits, and took ~30 minutes.

Commit https://github.com/phetsims/fourier-making-waves/commit/858ed2d4e356738d097a9c26877f25ac5037d014 was the easy part - getting it working in a hacked-together way.

The harder part was https://github.com/phetsims/fourier-making-waves/commit/61fd2c5341afd9c1beb38e042a4c792b9d3347a3, factoring it out in away that will make it easy to get rid of it when Slider eventually supports sound.  I had previously factored all of the sound stuff into subclass AudibleSlider, but that approach didn't make it possible to support sound for the track - it had the same problem as Slider, described in https://github.com/phetsims/sun/issues/697#issuecomment-928149768.  The new approach is encapsulated in AmplitudeSlider.SoundDragHandler, which handles the drag events, and is shared by both Slider and my custom track.

@arouinfar @kathy-phet please review in master.

**Comment by pixelzoom** [comment]
I said:
> ... Please take a good look, because this was a big change.

This was a big enough change that I thought it wise to publish a dev version, for confirming any regressions.

Before the change: [1.0.0-dev.49](https://phet-dev.colorado.edu/html/fourier-making-waves/1.0.0-dev.50/phet/fourier-making-waves_en_phet.html)

After the change: [1.0.0-dev.50](https://phet-dev.colorado.edu/html/fourier-making-waves/1.0.0-dev.50/phet/fourier-making-waves_en_phet.html)

**Comment by arouinfar** [comment]
I edited the link to dev.49 in @pixelzoom's comment because it was pointing to dev.50.

The behavior in dev.50 sounds good to me @pixelzoom. Thanks for making this change. It definitely improves the experience on mobile.
