### ISSUE TITLE
Amplitude equations for preset functions

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#18]
In the Java version, amplitudes for preset functions are defined in [Preset.java](https://phet.unfuddle.com/a#/projects/9404/repositories/23262/file?path=%2Ftrunk%2Fsimulations-java%2Fsimulations%2Ffourier%2Fsrc%2Fedu%2Fcolorado%2Fphet%2Ffourier%2Fenums%2FPreset.java&commit=75193), the relevant parts of which are reproduced here:

<details>
<summary>Preset.java</summary>

```java
    /*
     * Sine/Cosine Wave
     * A1 = 1
     */
    private static final double[] SINE_COSINE_AMPLITUDES = {
            1.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    };
    
    /* Sine Square Wave:
     * An = (2 - (2 * cos(n * PI))) / (n * PI)
     */
    private static final double[] SINE_SQUARE_AMPLITUDES = {
            4/PI, 0, 4/(3*PI), 0, 4/(5*PI), 0, 4/(7*PI), 0, 4/(9*PI), 0, 4/(11*PI)
    };
    
    /* Cosine Square Wave:
     * An = ((4 * sin(n * PI / 2)) - (2 * sin(n * PI))) / (n * PI)
     */
    private static final double[] COSINE_SQUARE_AMPLITUDES = {
            4/PI, 0, -4/(3*PI), 0, 4/(5*PI), 0, -4/(7*PI), 0, 4/(9*PI), 0, -4/(11*PI)
    };
    
    /* Sine Triangle Wave:
     * An = ((2 * sin( n * PI / 2)) - (2 * sin( n * PI))) / (n^2 * PI^2) 
     */
    private static final double[] SINE_TRIANGLE_AMPLITUDES = {
            8/(PI*PI), 0, -8/(9*PI*PI), 0, 8/(25*PI*PI), 0, -8/(49*PI*PI), 0, 8/(81*PI*PI), 0, -8/(121*PI*PI)
    }; 
    
    /* Cosine Triangle Wave:
     * An = ((4 * cos(n * PI)) - (2 * n * PI * sin(n * PI)) / (n^2 * PI^2)
     */
    private static final double[] COSINE_TRIANGLE_AMPLITUDES = {
            8/(PI*PI), 0, 8/(9*PI*PI), 0, 8/(25*PI*PI), 0, 8/(49*PI*PI), 0, 8/(81*PI*PI), 0, 8/(121*PI*PI)
    };
    
    /* Sine Sawtooth Wave:
     * An = ((2 * n * PI * cos(n * PI)) + (2 * sin(n* PI))) / (n^2 * PI^2)
     */
    private static final double[] SINE_SAWTOOTH_AMPLITUDES = {
            2/PI, -1/PI, 2/(3*PI), -1/(2*PI), 2/(5*PI), -1/(3*PI), 2/(7*PI), -1/(4*PI), 2/(9*PI), -1/(5*PI), 2/(11*PI)
    };
    
    /* Gaussian Wave Packet:
     * An = (1 / (p * sqrt(2 * PI)))^( -(n-no)^2 / (2 * p^2))
     * where p = 1.5, no = (number of harmonics + 1) / 2
     */
    private static final double[][] WAVE_PACKET_AMPLITUDES = {
            { 1.000000 },
            { 0.457833, 0.457833 },
            { 0.249352, 1.000000, 0.249352 },
            { 0.172422, 0.822578, 0.822578, 0.172422 },
            { 0.135335, 0.606531, 1.000000, 0.606531, 0.135335 },
            { 0.114162, 0.457833, 0.916855, 0.916855, 0.457833, 0.114162 },
            { 0.100669, 0.360448, 0.774837, 1.000000, 0.774837, 0.360448, 0.100669 },
            { 0.091394, 0.295023, 0.644389, 0.952345, 0.952345, 0.644389, 0.295023, 0.091394 },
            { 0.084658, 0.249352, 0.539408, 0.856997, 1.000000, 0.856997, 0.539408, 0.249352, 0.084658 },
            { 0.079560, 0.216255, 0.457833, 0.754840, 0.969233, 0.969233, 0.754840, 0.457833, 0.216255, 0.079560 },
            { 0.075574, 0.191495, 0.394652, 0.661515, 0.901851, 1.000000, 0.901851, 0.661515, 0.394652, 0.191495, 0.075574 }
    };
```

</details>

Note that each preset consists of an array of hardcoded values, with documentation showing the equation that was (supposedly) used to create those values. 

In the HTML5 version, it would be preferable not to use hardcoded values, since that is error prone. So I started by implementing the equations. I quickly discovered that many of these equations do not result in the hardcoded values. 

Here is the status of each equation:

* SINE_COSINE_AMPLITUDES might be OK?

* SINE_SQUARE_AMPLITUDES and COSINE_SQUARE_AMPLITUDES are correct. But is there a simpler form of the equations? It also looks a little suspicious that SINE_SQUARE_AMPLITUDES uses `cos`, while COSINE_SQUARE_AMPLITUDES uses `sin`, but maybe that's correct.
  
* SINE_TRIANGLE_AMPLITUDES and COSINE_TRIANGLE_AMPLITUDES are incorrect. The SINE version results in values that are much smaller than the hardcoded value. The COSINE version fails with values outside the amplitude range [-1.5,1.5].

* SINE_SAWTOOTH_AMPLITUDES is incorrect, does not produce the hardcoded values.

* WAVE_PACKET_AMPLITUDES is incorrect. It fails with values outside the amplitude range [-1.51.5].

What we'd like to have for each of the above is:
* a function of `n`
* documentation about where that function comes from

@arouinfar and I discussed this via Zoom, assigning to her to investigate.  In the meantime, I'll proceed by using the hardcoded arrays, as in the Java version.

**Comment by pixelzoom** [comment]
@arouinfar FYI, I found and implemented the equations for all waveforms _except_ "wave packet", and I've documented where they came from in the source code.  See [Waveform.js](https://github.com/phetsims/fourier-making-waves/blob/master/js/discrete/model/Waveform.js).

**Comment by pixelzoom** [comment]
Status of this issue...  

I've located and implemented equations for all preset waveforms except "Wave packet".    

For wave packet, the equation documented in the Java code (Preset.java) is

> An = (1 / (p * sqrt(2 * PI))) ^ (-(n-no)^2 / (2 * p^2))
> 
> where: 
> p = 1.5
> N = number of harmonics
> no = (N + 1) / 2

This equation results in amplitudes that are signficantly outside the range [-1.5, 1.5].  

I don't know where this equation came from (nothing in the legacy design doc), and I have been unable to locate anything that remotely resembles it.

**Comment by pixelzoom** [comment]
Playing around with the wave packet equation, I suspect that there's an error in the operator precedence of this term:

`-(n-no)^2`

That gets executed as `-((n-no)^2)`, and I suspect it should be `(-(n-no))^2)`.  I've change the code to use the latter, and the amplitude values are now in the range [-1.5,1.5].   The amplitude values still do not match the hardcoded Java values, but they are closer, and yield something that looks/behaves more like a wave packet.  

So... Now I'm not sure if the Java hardcoded amplitudes are wrong, or the equation is wrong.

**Comment by pixelzoom** [comment]
`WAVE_PACKET_AMPLITUDES`, the hardcoded amplitude values (and equation doc), was first added to FourierConstants.java in https://phet.unfuddle.com/a#/projects/9404/repositories/23262/commit?commit=3827.   If was later moved to Presets.java in https://phet.unfuddle.com/a#/projects/9404/repositories/23262/commit?commit=5354.  The values and equation doc were never changed, and (unfortunately) the commit message doesn't include any additional info about where the values came from.

**Comment by pixelzoom** [comment]
Here's a page in the original [Fourier Design Outline](https://phet.unfuddle.com/a#/projects/9404/repositories/23262/file?path=%2Ftrunk%2Fsimulations-java%2Fsimulations%2Ffourier%2Fdoc%2FFourier_Design_Outline.pdf&commit=75222) that looks close to the equation shown in Presets.java:

<img width="917" alt="screenshot_874" src="https://user-images.githubusercontent.com/3046552/108766057-e57cfe80-7511-11eb-940a-5b27660d5f96.png">

**Comment by pixelzoom** [comment]
Here's a page in the original [Fourier Design Outline](https://phet.unfuddle.com/a#/projects/9404/repositories/23262/file?path=%2Ftrunk%2Fsimulations-java%2Fsimulations%2Ffourier%2Fdoc%2FFourier_Design_Outline.pdf&commit=75222) that looks close to the equation shown in Presets.java:

<img width="917" alt="screenshot_874" src="https://user-images.githubusercontent.com/3046552/108766057-e57cfe80-7511-11eb-940a-5b27660d5f96.png">


This equation seems to have the same operator precedence problem as the Presets.java documentation. @arouinfar could you double-check this derivation?

**Comment by arouinfar** [comment]
@pixelzoom I wonder if the large amplitude occurs because we're using a slightly different definition of k (extra factor of 2pi). I found this in the Teacher Tips:
![image](https://user-images.githubusercontent.com/8419308/121730883-7b329e80-caad-11eb-9773-50810d0de052.png)

**Comment by pixelzoom** [comment]
I'm not sure how to apply this observation to the Discrete screen.  The equation there has nothing to do with k. It involves n, where n is harmonic order, [0,1,2,...].

**Comment by pixelzoom** [comment]
Here's a summary of  where we're at with the Wave Packet equation for the _Discrete_ screen. 

The model is currently using hardcode amplitudes, from this array, where `numberOfHarmonics - 1` is the index into the array. This is the same array used in the Java version.

```js
  return [
    [ 1.000000 ],
    [ 0.457833, 0.457833 ],
    [ 0.249352, 1.000000, 0.249352 ],
    [ 0.172422, 0.822578, 0.822578, 0.172422 ],
    [ 0.135335, 0.606531, 1.000000, 0.606531, 0.135335 ],
    [ 0.114162, 0.457833, 0.916855, 0.916855, 0.457833, 0.114162 ],
    [ 0.100669, 0.360448, 0.774837, 1.000000, 0.774837, 0.360448, 0.100669 ],
    [ 0.091394, 0.295023, 0.644389, 0.952345, 0.952345, 0.644389, 0.295023, 0.091394 ],
    [ 0.084658, 0.249352, 0.539408, 0.856997, 1.000000, 0.856997, 0.539408, 0.249352, 0.084658 ],
    [ 0.079560, 0.216255, 0.457833, 0.754840, 0.969233, 0.969233, 0.754840, 0.457833, 0.216255, 0.079560 ],
    [ 0.075574, 0.191495, 0.394652, 0.661515, 0.901851, 1.000000, 0.901851, 0.661515, 0.394652, 0.191495, 0.075574 ]
  ][ N - 1 ];
```

For 11 harmonics, we use the last entry in the array:

```js
[ 0.075574, 0.191495, 0.394652, 0.661515, 0.901851, 1.000000, 
  0.901851, 0.661515, 0.394652, 0.191495, 0.075574 ]
```

... and it looks like this in the sim:

<img width="810" alt="screenshot_1031" src="https://user-images.githubusercontent.com/3046552/122103649-168c8200-cdd4-11eb-9a53-b2d221fe81b5.png">

It would be preferrable to use an equation, as we do for the other waveforms. This would also give us confidence that the amplitudes are correct, since we don't know how they were computed.  The equation documented in the Java code is:

`An = (1 / (p * sqrt(2 * PI)))^( -(n-no)^2 / (2 * p^2))`

But that equation results in amplitudes that are outside the range [-1.5, 1.5].  

In https://github.com/phetsims/fourier-making-waves/issues/18#issuecomment-783639454, I said that I suspect there may be a problem with operator precedence of one of the terms in that equation.  If I change `-(n-no)^2` to `(-(n-no))^2)` , then the values are in the range [-1.5, 1.5], and the result looks like a wave packet.  But the amplitudes are different than the hardcoded values. For 11 harmonics, we get these amplitudes:

```js
[0.0006376009074296057, 0.009013870470163656, 0.07073553026306462, 
 0.3081256325868873, 0.7450440608344457, 1, 
 0.7450440608344457, 0.3081256325868873, 0.07073553026306462, 
 0.009013870470163656, 0.0006376009074296057]
``` 

Here's what that looks like in the sim. Note that A<sub>1</sub> and A<sub>11</sub> are so small that they round to zero, and that's a problem.

<img width="807" alt="screenshot_1030" src="https://user-images.githubusercontent.com/3046552/122104102-8995f880-cdd4-11eb-9688-ad84d176d2b2.png">

So.... 
* Are the hardcoded values correct?  If so, how were they computed?
* Or is the revised equation correct? If so, how do we deal with very small amplitudes that display as zero?

**Comment by pixelzoom** [comment]
We touched on this briefly in 7/29/21 standup meeting. I noted that the wave packets in the Discrete vs Wave Packet screens look quite different. For example:

Discrete (HTML5, Java is identical):
<img width="762" alt="screenshot_1104" src="https://user-images.githubusercontent.com/3046552/127557894-d7bc2f22-6957-46fb-9810-86e052bfd4cc.png">

Wave Packet (Java, HTML5 not implemented yet but will look the same):
<img width="741" alt="screenshot_1105" src="https://user-images.githubusercontent.com/3046552/127557929-9827f42e-e89d-4b04-9a62-b595dbfa7dec.png">

This makes me wonder if the Discrete hardcoded values are correct, or what we really want to use.

We agreed that it would be preferrable if they looked the same.

@arouinfar suggested that I might be able to reuse the implementation in the Wave Packet screen, replacing the hardcoded Discrete implementation.  I'll be sure to consider that when completing the implementation for the Wave Packet screen.

**Comment by pixelzoom** [comment]
> @arouinfar suggested that I might be able to reuse the implementation in the Wave Packet screen, replacing the hardcoded Discrete implementation. I'll be sure to consider that when completing the implementation for the Wave Packet screen.

This looks promising.  In the Wave Packet screen, ampllitudes are computed using this equation:

`A(k,k0,dk) = exp[ -((k-k0)^2) / (2 * (dk^2) )  ] / (dk * sqrt( 2pi ))`

... where (in the space domain)`k` is the component number, `k0` is the wave packet's center, and `dk` is the wave packet's standard deviation.   I'm not entirely clear on what is appropriate for `k0` and `dk` in the Discrete screen.  Maybe I'll start with 12pi and 4pi respectively.  @arouinfar any thoughts?

**Comment by pixelzoom** [comment]
> @arouinfar suggested that I might be able to reuse the implementation in the Wave Packet screen ...

This is not working out at all.

This sim is approaching feature complete, so we need to wrap this up.  We could leave it as is, hardcoded amplitudes for "wave packet" that we're no sure are correct, and that look different than the wave packet in the Wave Packet screen.   Or we could consult with a subject-matter expert to determine what the correct equation is, or at least whether the hard-coded amplitudes are correct.

This needs to be wrapped up in the next week. @arouinfar How do you want to proceed?

**Comment by pixelzoom** [comment]
Discussed with @arouinfar on Zoom.  She would like to use the hardcoded values for the wave packet preset.  The goal is to show something that is "wave packet list / Gaussian", and there is no need to match the shape of the wave packet in the Wave Packet screen.  So the hardcoded values work.

**Comment by pixelzoom** [comment]
In Waveform.js, I summarized why we're using hardcoded amplitude values:

```js
const WAVE_PACKET = new WaveformValue( {

  // Presets.java used these same hardcoded amplitude values. It documented an equation, but that equation did not
  // produce these values, and in fact produced invalid values. After repeated attempts to identify a correct equation,
  // we gave up and decided to stick with the hardcoded values.
  // See https://github.com/phetsims/fourier-making-waves/issues/18
  getAmplitudes: ( numberOfHarmonics, seriesType ) => {
```

Closing.
