### ISSUE TITLE
Problem with position of λ1 tool.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#181]
Reported by @kathy-phet in https://github.com/phetsims/fourier-making-waves/issues/178#issuecomment-926970316:
> - [ ]  (iPad only bug?) when Component spacing is set to 0 spacing, k1 (yellow) shows zero which is correct, but a small Lambda1 green box in the lower right of the screen (seems like this is a bug/unitentional). There is also inconsistency as I change the component spacing. I can get the lamda1=infinity to be on the graph. But if I reset, then change spacing to 0, then check k1 and lambda1. I don't see any of this on my Windows machine.

**Comment by pixelzoom** [comment]
@kathy-phet Please provide the standard Troubleshooting info.  At the very least, I need to know what version of iOS you're running.

**Comment by pixelzoom** [comment]
OK, I think I've figure out what is being reported here.

"k1" and "lambda1" are referring to the measurement tools in the Wave Packet screen.  

I would have been helpful to have a screenshot. But if I understand what @kathy-phet is describing, I can reproduce it on all platforms by following these steps:

1. Start the sim
2. Go to Wave Packet screen
3. Set Component Spacing to pi/4.
4. Set Component Spacing to 0
5. Check the checkboxes for k1 and lambda1 tools.
6. The lamba1 tool is in the wrong place, at lower-right of the screen.  See screenshot below, running with `?dev` to show the bounds that would be visibile on iPad.

@kathy-phet is this what you're reporting?  Is there anything else?  I cannot parse this sentence in your report:
> But if I reset, then change spacing to 0, then check k1 and lambda1. 

<img width="1132" alt="screenshot_1275" src="https://user-images.githubusercontent.com/3046552/134769776-b5fbe65a-e8f2-40c9-bd1a-f8d752011b95.png">

**Comment by kathy-phet** [comment]
Yes this is the bug. I took a screen shot with my phone, but had to go listen to some music :), so was going to elaborate with issues when I returned to it. I wanted to put what I had found so far. You just got to it, before I got back to reporting more detail. 

That last sentence means… If you change sliders from the point you have on this image you will see the lambda1=infinity move around in terms of where it is drawn.

**Comment by pixelzoom** [comment]
Fixed in the above commit. (And thanks for supporting live music! :)  @kathy-phet please review in master. You might want to run with `?debugTools` so that you can see the origin (red dot) and drag bounds (red rectangle) to the tools.

**Comment by pixelzoom** [comment]
Running with `?debugTools` ...

For finite values of λ1, the default position of the tool is as shown in this screenshot. Red dot is the tool's origin.

<img width="1133" alt="screenshot_1282" src="https://user-images.githubusercontent.com/3046552/134790481-2f508f4a-1875-4fb9-a928-2648fa1a99fd.png">

And here's the default position of "λ1 = ∞":

<img width="1131" alt="screenshot_1283" src="https://user-images.githubusercontent.com/3046552/134790473-66b23c24-7a10-4550-bfb4-2b2dbe0a5175.png">

**Comment by arouinfar** [comment]
Thanks @pixelzoom @kathy-phet. The behavior looks good in master, closing.
