### ISSUE TITLE
Zoom "in" button is in a disabled state by default on Discrete screen

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/fourier-making-waves#182]
For #178 

Not a bug, but I think would be a good change for the publication.

I think on the Discrete screen I would make the default zoom level one increment lower. Currently, the zoom control is fully "zoomed in" when you open this screen, so pressing the "zoom in button" does nothing. It feels like a nonoptimal UX choice since then the control feels a bit broken. In contrast, on the Wave Packet screen the zoom level is chosen so it can be zoomed in or out when you open the screen. 

My personal preference might be to start the default zoom when there are two full wavelengths on the screen. That way it is easy to identify lamda1 (which is why I imagine the current default was chosen), like so:

![zoom](https://user-images.githubusercontent.com/4051174/134784011-f3c7afdb-04d5-44f1-97e3-efad9a25366d.PNG)

**Comment by pixelzoom** [comment]
For the record, the Java sim (and the HTML5 sim, until 8/24/21) had one additional zoom level, [-0.25, 0.25].  So in the default state the charts could be zoomed in or out.  @arouinfar asked me to delete that zoom level in https://github.com/phetsims/fourier-making-waves/issues/160.

The default is easy enough to change. But note that the default x-axis scale in the Discrete screen is the same as the ONLY x-axis scale in the Wave Game.  Do you want to leave the Wave Game as is, or change it too?  

Let me know how you'd like to proceed.

**Comment by pixelzoom** [comment]
My 2 cents is that I don't think it's a problem to have the zoom in (+) button disabled as the default state. All it says is that fully zoomed in is what we consider to be the most useful zoom level.

**Comment by kathy-phet** [comment]
It didn’t bother me to have it disabled. I prefer it the way it is because I think it helps to keep with the wavelength tool.

**Comment by pixelzoom** [comment]
What I'm hearing is "leave as is".  So I'll go ahead and close this.  If I've misunderstood, please reopen.
