### ISSUE TITLE
Tools should be bounded on the top of the sim

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/fourier-making-waves#183]
For #178 

@pixelzoom I think this should be a pretty quick change, but some of the tools can have there label covered by moving them to the top of the sim, it seems like the bounds should be such that the label (such as lambda) cannot be lost.

Currently:
![tools](https://user-images.githubusercontent.com/4051174/134784191-5c500a8c-4e1f-46dd-9faf-78a4ae60b85c.PNG)

Ideally, the tool would go no higher than the top of the label at the sim bounds:
![tools1](https://user-images.githubusercontent.com/4051174/134784198-9aa08187-157c-4d40-9852-8a8d6efbc1d5.PNG)

**Comment by pixelzoom** [comment]
As I started working on this, it seemed like the drag bounds could use a little polishing overall, and that's been done in the above commits.  I've also added a `debugTools` query parameter, defined as follows:

```js
  // Shows the origin (as a red dot) and the drag bounds (as a red rectangle) for measurement tools.
  // For internal use only, not public facing.
  debugTools: {
    type: 'flag'
  }
```

Below are a couple of screenshots, running with `?dev&debugTools`, showing the tool origins and drag bounds for the Discrete and Wave Packet screens.  The red dot (origin) is constrained to stay within the drag bounds (red rectangle).

@arouinfar @ariel-phet please review in master.

<img width="1133" alt="screenshot_1280" src="https://user-images.githubusercontent.com/3046552/134790047-ae056faa-6582-4a2a-88b2-93f15df93a91.png">

<img width="1134" alt="screenshot_1279" src="https://user-images.githubusercontent.com/3046552/134790048-1aab6413-cdcc-4bc0-af66-f73d623a5e19.png">

**Comment by ariel-phet** [comment]
That all works well for me

**Comment by pixelzoom** [comment]
There's still a minor problem here. The `λ1 = ∞` is slight outside layout bound when dragged to left.  Self-assigning to address this.

**Comment by pixelzoom** [comment]
Fixed in the above commit.  `λ1 = ∞` now stays inside the layout bounds.  And note that I also fixed its origin (red dot) so that it's a the bottom center.   See screenshot below, running with `?dev&debugTools`.  

Back to @arouinfar to review.

<img width="1133" alt="screenshot_1287" src="https://user-images.githubusercontent.com/3046552/134955621-040a88f9-4c5d-4091-93a1-dbd33e4ae147.png">

**Comment by arouinfar** [comment]
The updated bounds feel good to me. Thanks @pixelzoom @ariel-phet!
