### ISSUE TITLE
Interference between measurement tools and control panel on Wave Packet screen

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/fourier-making-waves#184]
On the Wave Packet screen you can easily get into a situation via zooming where the measurement tools and cover the control panel in way that makes certain control panel elements not usable when the look like they should be. For example:

![interference](https://user-images.githubusercontent.com/4051174/134784436-6e4d5b39-6833-4a97-a33e-a5c5681f0439.PNG)

In this situation, it looks like you should be able to still click the "Function of" combo box, but it is not clickable (presumably due to interference with the wavelength measurement tool.

Although it might look odd, perhaps the easiest solution would be to layer the control panel over these measurement tools (it doesn't serve much purpose for such tools to be over the control panel, and they are only really useful being on the graph).

**Comment by pixelzoom** [comment]
Good suggestion, and easy to change. We have the same issue on the Discrete screen (see screenshot below), so I'll apply the same change there.

<img width="1128" alt="screenshot_1276" src="https://user-images.githubusercontent.com/3046552/134788725-4ddb6107-fad4-48d8-95c6-1dacba1ade71.png">

**Comment by pixelzoom** [comment]
Done in the above commit, for Discrete and Wave Packet screens.  @ariel-phet or @arouinfar please review in master.

**Comment by ariel-phet** [comment]
Looks good to me, closing
