### ISSUE TITLE
Visibility of measurement tools is inconsistent/complicated.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#185]
Related to https://github.com/phetsims/fourier-making-waves/issues/178.

In the Discrete screen, visibility of the measurement tools is controlled solely by their associated checkboxes. If you collapse both charts while the checkboxes are checked, the tools will be remain visible. For example:

<img width="1131" alt="screenshot_1277" src="https://user-images.githubusercontent.com/3046552/134789290-769738a1-8ce8-49ef-ad37-f971019ea63b.png">

The Wave Packet screen tried to be more clever.  If the charts associated with the tools are collapses, then the tools are hidden, even if their checkboxes are checked. For example:

<img width="1133" alt="screenshot_1278" src="https://user-images.githubusercontent.com/3046552/134789306-b6be297d-6050-4d75-b3a1-36435770302e.png">

The first problem is that these 2 behaviors are inconsistent - we should do the same thing in both screens.

The second problem is that the behavior of the Wave Packet screens feels too clever, and could be confusing. (Why don't I see the tools when I have them enabled via checkboxes?)  The implementation is also more complicated, and harder to maintain - I've broken it several times during implementation, and forsee someone easily breaking it in the future.   

So I'm going to change the Wave Packet screen to behave like the Discrete screen. Visibility of the measurement tools will be controlled solely by their associated checkboxes.

**Comment by pixelzoom** [comment]
Done in the above commit. Visibility of ALL measurement tools in the sim is now controlled solely by their associated checkboxes.  @arouinfar please review in master.

**Comment by arouinfar** [comment]
> So I'm going to change the Wave Packet screen to behave like the Discrete screen. Visibility of the measurement tools will be controlled solely by their associated checkboxes.

Good call @pixelzoom. The behavior likely came from the original implementation before the tools on the Wave Packet screen had their own checkboxes. The behavior in master feels much better to me.
