### ISSUE TITLE
Font for summation index is too larger in Discrete screen.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#186]
For https://github.com/phetsims/fourier-making-waves/issues/178 ...

In https://github.com/phetsims/fourier-making-waves/issues/156, we made the infinity symbols larger for summation and integral in the Wave Packet screen.  Either in that issue or (more likely) in https://github.com/phetsims/fourier-making-waves/issues/165, the range for the summation got a little too larger, see screenshot below.

I'm going to reduce the font size in the Discrete screen, while being careful not to change the Wave Packet screen.  

<img width="328" alt="screenshot_1285" src="https://user-images.githubusercontent.com/3046552/134950904-3d0181cc-999d-425f-b672-cdf903f3859a.png">

**Comment by pixelzoom** [comment]
Fixed in the above commit.

Index font for the Discrete screen is now smaller (12 pt), as it was originally:

<img width="267" alt="screenshot_1288" src="https://user-images.githubusercontent.com/3046552/134957298-fb434960-cf47-4aa5-9210-6928a8ef53e9.png">

Wave Packet screen is unchanged from the sizes that were approved in #156:

<img width="229" alt="screenshot_1289" src="https://user-images.githubusercontent.com/3046552/134957327-2d7627b7-dcb1-480e-a7a1-5e9daadcd85f.png">
<img width="242" alt="screenshot_1290" src="https://user-images.githubusercontent.com/3046552/134957354-0bfe37c0-715e-4dbb-9b01-219dc6c4a937.png">

@arouinfar please review in master.

**Comment by arouinfar** [comment]
Looks good, thanks @pixelzoom.

**Comment by kathy-phet** [comment]
@pixelzoom - If you are pixel polishing this, should we make the "n =" part under the summation the same size on both screens? The discrete the n= is smaller than on the Wave Packet. I like the size of the "1" the "11" and the "infinity symbols". The "n=" could be either of the two sizes, but seems like it should be the same on both screens. I perhaps have a slight preference for the slightly larger version of "n=", but no terribly strong. I like the new size of the "1" and "11" over version v.48.

**Comment by kathy-phet** [comment]
No need to reimplement. I can certainly be fine with what's there ... just noticed the difference.

**Comment by pixelzoom** [comment]
Yeah, the difference bothers me too.  So I'm going to reopen this (again :) and take another look.

**Comment by pixelzoom** [comment]
In the above commit, I broke the index minimum into 2 separate parts: 'n =' and '0' (or -infinity).  The table below shows the things that have separate font sizes, and what their current font sizes are.  And to be clear, this is just for the summation/integral part of the equations.

| component | font size |
| :-- | :-- |
| ∑ and ∫ symbols | 30 |
| n = | 14 |
| range numbers, like '1' and '11' | 12 |
| ∞, -∞ | 16 |

Examples:

<img width="284" alt="screenshot_1293" src="https://user-images.githubusercontent.com/3046552/135006380-a92f239f-f465-4daf-9a3d-50adc28d3100.png">

<img width="220" alt="screenshot_1291" src="https://user-images.githubusercontent.com/3046552/135006387-0e9ea8aa-5e2f-4818-bf75-8ddaf315ed39.png">

<img width="241" alt="screenshot_1292" src="https://user-images.githubusercontent.com/3046552/135006397-7c1a10f9-3c94-47c3-aca7-08fc0915db69.png">

I'm glad I did this, because this makes me happy. 

What does not make me happy is the vertical alignment of 'n' and '=', '-' and '∞'.   I have no control over that, it's how scenery is rendering the strings and aligning their baselines.   I'd have to render each character/sign separately, and adjust their positions empirically - and that would be ill-advised because it would be specific to one font, on one platform.   So I'll leave it there, and learn to ignore it.

@kathy-phet @arouinfar please review in master, and let me know if you'd like to tweak any of the font sizes in the above table.

**Comment by kathy-phet** [comment]
Chris, this looks nicer. Thanks! I assume you can’t center align them vertically, so it depends less on the rendering. Just a thought.

**Comment by pixelzoom** [comment]
No, I can't center align them vertically.  I have no control over any form of vertical alignment (center, baseline,...) unless I render each character as a separate Node, then move them around empirically.  And that empirical adjustment (as I said above) would be specific to one browser/platform, because of differences in how fonts are rendered.

@arouinfar feel free to close if this looks OK to you.
