### ISSUE TITLE
Potential lag on sliders in Wave Packet screen

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/fourier-making-waves#188]
For https://github.com/phetsims/fourier-making-waves/issues/178. iPadOS 15.
I noticed on the iPad that dragging the sliders on the third page had some lag that wasn't present on the other screens.

**Comment by pixelzoom** [comment]
This was raised in https://github.com/phetsims/fourier-making-waves/issues/131 and we decided that the performance was fine.   Assigning to @arouinfar to decide if that has changed.

**Comment by arouinfar** [comment]
> This was raised in #131 and we decided that the performance was fine.

That's correct. There is some lag between the cursor/finger and the slider thumb on the Wave Packet screen, but the graphs appear responsive, and I thought the behavior was acceptable. Given that there isn't any low-hanging fruit for optimization, and the lag doesn't really affect the usability, we decided to leave as-is. Closing.
