### ISSUE TITLE
odd numeric values for x-axis tick labels in Java version

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#19]
In the Java version (and the HTML5 version), `L` (the string length) is 1.  

In the Java version, if you have "Math form" checked, the Harmonics chart will have this x-axis scale, with symbolic tick labels, expressed in terms of `L`:

<img width="742" alt="screenshot_707" src="https://user-images.githubusercontent.com/3046552/100686668-0d5a2d00-333c-11eb-8ee3-4b50dd5154ea.png">

If you uncheck "Math form", the x-axis scale is then ticks are labeled with numeric values. I would expect those tick labels to simply be the numeric values that correspond to `L = 1`.  But that's not the case, and only the min and max ticks are labeled:

<img width="743" alt="screenshot_706" src="https://user-images.githubusercontent.com/3046552/100686764-38dd1780-333c-11eb-98f1-6bd26a9c2050.png">

Here's another zoom level, with "Math form" checked:

<img width="742" alt="screenshot_709" src="https://user-images.githubusercontent.com/3046552/100686839-60cc7b00-333c-11eb-8608-1746e642aad5.png">

and "Math form" unchecked:

<img width="741" alt="screenshot_708" src="https://user-images.githubusercontent.com/3046552/100686829-5ad69a00-333c-11eb-9c51-474ee9f32401.png">

Again, the numeric values are not what I expected. And again, only the min and max ticks are labeled.

I've looked through the Java implementation, and the value discrepancy looks like a bug to me.  Labeling only the min and max ticks with numeric values might have been a "feature", but I can't be certain, and I don't know why that would be desirable.

@arouinfar can you think of any reason why the numeric values would not correspond to the value of `L`?  And should we label the same tick marks for both numeric and symbolic tick labels?

**Comment by pixelzoom** [comment]
12/3/2020 design meeting @arouinfar @kathy-phet @ariel-phet @pixelzoom 

* Keep symbolic and numeric x-axis tick labels
* For numeric, only label min and max
* For numeric, fix values for space domain, use L=1

**Comment by pixelzoom** [comment]
On 12/8/20, @arouinfar and I reviewed tick labels on Slack.  Including only min/max for numeric labels looks very odd - and is more complicated!  Labeling the same ticks for both numeric and symbolic cases looks good, so we'll go with that.

Other requirements have been implemented, and this is ready to review in [1.0.0-dev.4](https://phet-dev.colorado.edu/html/fourier-making-waves/1.0.0-dev.4/phet/fourier-making-waves_en_phet.html).  Note that the Sum is not plotted yet, and "space & time" domain isn't supported yet.  But you can play around with all of the zoom control to test-drive how ticks and labels are handled. 

Over to @arouinfar for review.

**Comment by arouinfar** [comment]
@pixelzoom things are generally looking good in master, but `0L` and `0T` looks strange to me. Can you label the zero as simply `0`?

**Comment by pixelzoom** [comment]
Hmmm, that's a regression - zero values are not supposed to include the symbol.  I'll investigate.

**Comment by pixelzoom** [comment]
Fixed in master and [1.0.0-dev.6](https://phet-dev.colorado.edu/html/fourier-making-waves/1.0.0-dev.6/phet/fourier-making-waves_en_phet.html).  See screenshots below with 'L' (space) and 'T' (time) x axis.  

I'll go ahead and close this, since it sounded like this was the only issue.

<img width="917" alt="screenshot_757" src="https://user-images.githubusercontent.com/3046552/102405595-a462ee00-3fa6-11eb-809e-3da3a246ba0f.png">
<img width="928" alt="screenshot_758" src="https://user-images.githubusercontent.com/3046552/102405604-a88f0b80-3fa6-11eb-80bc-df91ee85c586.png">
