### ISSUE TITLE
Focus traversal does not include Amplitude value displays.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#197]
For phetsims/qa#711

@Nancy-Salpepi reported this in https://github.com/phetsims/fourier-making-waves/issues/194, and I moved it here because it's (mostly) a new topic:

> @pixelzoom I am noticing that keyboard nav doesn't allow me to tab to those amplitude boxes at all. Once I am in them, keyboard nav works, but shouldn't I be able to access them without a mouse?

... where "those amplitude boxes" is referring to the row of NumberDisplays above the amplitude sliders in the Discrete and Wave Game screens.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/fourier-making-waves/issues/53#issuecomment-820763082, we explicitly decided to omit the Amplitude NumberDisplays from focus traversal:

> 4/15/21 design meeting:
> 
> @Kathy would like to proceed with:
> 
> * Include only interactive UI components in the traversal order
> * Ignore the amplitude NumberDisplays and keypad

There were 2 reasons for this decision: 
(1) The Keypad is a common-code component, and needs focus traversal work. @kathy-phet didn't feel that we had the resources for that at this time.
(2) Tabbing through 11 sliders and 11 NumberDisplays would take you forever to get to the control panel.
(3) Using the keypad is not strictly necessary to successfully using the sim.  In the Wave Game in particular, all challenges are generated with amplitudes in 0.1 intervals, which can be entered via the sliders.

We expect to circle back to the amplitude NumberDisplays someday, but not for 1.0.  So there's nothing to do here

@arouinfar if I summarized that correctly, please feel free to close.

**Comment by pixelzoom** [comment]
9/30/21 design meeting:

We're not going to address this issue for the adhoc implementation in Fourier. It will be generally addressed in https://github.com/phetsims/sun/issues/697. 

Closing.

**Comment by pixelzoom** [comment]
Oops, I accidentally closed this (thanks @Nancy-Salpepi).  

@arouinfar please confirm and close.

**Comment by arouinfar** [comment]
@Nancy-Salpepi this is definitely the type of thing to look for when testing keyboard nav. However, in this particular case, it was an explicit decision not to include the NumberDisplays in the focus order. 

@pixelzoom summarized the reasons nicely. I completely agree and have added my comments below.

> (1) The Keypad is a common-code component, and needs focus traversal work. @kathy-phet didn't feel that we had the resources for that at this time.

The Keypad is traversable, but a better keyboard experience would be to allow users to type in the values directly which goes beyond the scope of this sim.

> (2) Tabbing through 11 sliders and 11 NumberDisplays would take you forever to get to the control panel.

Agreed, adding an extra 11 NumberDisplays to the traversal order would be cumbersome for users.

> (3) Using the keypad is not strictly necessary to successfully use the sim. In the Wave Game in particular, all challenges are generated with amplitudes in 0.1 intervals, which can be entered via the sliders.

With the shift and page up/down modifiers, keyboard access of the sliders can be very efficient and precise. It takes less time than tabbing around the keypad to enter numbers, too.
