### ISSUE TITLE
Width Indicator label is cut off

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/fourier-making-waves#198]
**Test device**
MacBook Air (m1 chip)

**Operating System**
11.6

**Browser**
Safari

**Problem description**
In the Wave Packet Screen, when using query parameter ?stringTest=long the Width Indicator Label appears cut off in the top panel. 

**Visuals**
Amplitudes of Fourier Components Panel:
<img width="703" alt="Screen Shot 2021-09-29 at 1 32 31 PM" src="https://user-images.githubusercontent.com/87318828/135321295-11b66f7d-b2b6-4942-b7eb-432c2a9e9730.png">

Compare to Sum Panel:
<img width="789" alt="Screen Shot 2021-09-29 at 1 36 19 PM" src="https://user-images.githubusercontent.com/87318828/135321360-919e5a89-672a-4a7b-9d64-7bb84eee750e.png">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: 12345678901234567890123456789012345678901234567890
URL: https://phet-dev.colorado.edu/html/fourier-making-waves/1.0.0-rc.1/phet/fourier-making-waves_all_phet.html?stringTest=long
Version: 1.0.0-rc.1 2021-09-28 15:44:23 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15
Language: en-US
Window: 1440x675
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by pixelzoom** [comment]
Thanks @Nancy-Salpepi.  I missed seeing the `maxWidth` for the width indicators. Fixed in the above commits in master and 1.0.  See screenshot below. Ready for verification in the next RC.

<img width="1134" alt="screenshot_1300" src="https://user-images.githubusercontent.com/3046552/135322672-d6777cf6-2999-42c2-9fbc-1d3b26b2590d.png">

**Comment by Nancy-Salpepi** [comment]
Width indicators look OK now.
