### ISSUE TITLE
Issue with "Third-Party Libraries" credits? 

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/fourier-making-waves#209]
While looking at "Thanks to" credits, I noticed that this sim is missing the Sherpa credits on the sim page -- 

Numberline distance looks like this: 
![image](https://user-images.githubusercontent.com/5096804/137220455-fb5d175c-bc01-47f1-8af7-c35ea0051493.png)

But Fourier has a blank for Third-Party Libraries which seems highly unlikely. 

Is this a bug in the build process?

**Comment by pixelzoom** [comment]
Sorry, this outside of my wheelhouse.  If I had to speculate... like alterntive images, this might be one of those "wait for caching" things.

**Comment by kathy-phet** [comment]
Sorry for the red herring. Closing this.
