### ISSUE TITLE
Teacher Tips

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#21]
This issue is for documenting things that should go in Teacher Tips.

**Comment by pixelzoom** [comment]
- [ ] From #11, explain why the amplitude range is [-1.27, 1.27], which is [ -4/pi, 4/pi ].

**Comment by arouinfar** [comment]
I've been organizing the items for the Teacher Tips over in #82, so I'll close this one.

We figured out the range issue in https://github.com/phetsims/fourier-making-waves/issues/11 and I don't think it's something that needs to be included in the Teacher Tips.
