### ISSUE TITLE
Revise "Thanks To" credits on website.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#212]
Related to #208...

@arouinfar can you please update the "Thanks To" credits on the sim's web page? 

What it should say:

> We gratefully acknowledge support from STROBE NSF Science & Technology Center Grant DMR-1548924. Any opinions, findings, and conclusions or recommendations expressed in this material are those of the author(s) and do not necessarily reflect the views of the National Science Foundation.

What it currently says:

<img width="1123" alt="screenshot_1359" src="https://user-images.githubusercontent.com/3046552/137400428-6f139f56-89f2-4afd-ac11-15c298e30184.png">

**Comment by arouinfar** [comment]
This was blocked by a character limit in the "Thanks to" field, but it was expanded in https://github.com/phetsims/website/issues/1280. The full text is now up on the sim page.
