### ISSUE TITLE
small parts of the translated text is lagging behind  sim's components

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/fourier-making-waves#213]
We translate the [Fourier simulation into spanish](https://phet.colorado.edu/sims/html/fourier-making-waves/latest/fourier-making-waves_es.html) and the translation of "component Spacing" that is "Espacio de Componentes" in the "Wave Packet" screen is getting behind the i control:

![image](https://user-images.githubusercontent.com/26031501/137790339-58a88924-44db-4739-9f06-f78aaf6491ef.png)

I share this with @arouinfar, and she can reproduce it with text, but not with `stringTest=long`:
![image](https://user-images.githubusercontent.com/26031501/137790475-1d79e794-74eb-4b31-b7e7-82a23bd36aeb.png)

**Comment by arouinfar** [comment]
> I share this with @arouinfar, and she can reproduce it with text

@pixelzoom this issue appears when editing `wavePacketScreen.view.controlPanel.componentSpacingSubpanel.componentSpacingText.textProperty` in Studio.
