### ISSUE TITLE
Sim launches without sound in Studio using Chrome

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/fourier-making-waves#217]
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.0.1

**Browser**
Chrome

**Problem description**
When testing https://github.com/phetsims/phet-io/issues/1626 in master:
In the Studio wrapper, if I launch the sim with sound on, the sim launches without the sound. I need to click somewhere on the screen in order for the sound to be initiated. In the State wrapper, when setting the state, the downstream sim has sound, although sometimes it is very low. 

With Mac + safari--the sound works as in should in both wrappers. 

As per MK's recommendation, I am not assigning to any developer at this time. 

**Steps to reproduce**
In Studio (with chrome):
1. Go to the discrete screen
2. In the Fourier Series portion of the panel, check the box for sound
3. Press 'preview sim' --The sim will launch without sound 
4. Click anywhere on the screen--the sound will turn on

**Visuals**

https://user-images.githubusercontent.com/87318828/153529255-44631d01-2912-4b82-9a8e-084c955f2963.mov

**Comment by KatieWoe** [comment]
Tested this on Windows 11. I saw this bug on Chrome but it did not seem to happen on Firefox.

**Comment by zepumph** [comment]
>I need to click somewhere on the screen in order for the sound to be initiated.

This is part of Chrome's audio policy, a user must interact with a sim in order for it to convey sound (or any audio for that matter). This also applies to voicing responses with SpeechSynthesis, as well as auto playing a video, etc. I recommend closing this issue, but I want to make sure QA is aware of this, and can document it as needed. See https://developer.chrome.com/blog/autoplay/ for details.

**Comment by Nancy-Salpepi** [comment]
I updated the Sound portion under Section 4.4 of the QA book to include the information in https://github.com/phetsims/fourier-making-waves/issues/217#issuecomment-1051140400.
