### ISSUE TITLE
use [-1.5,1.5] for amplitude range

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#22]
Related to #11... 

The only reason that amplitude range is [-1.27,1.27] is because the square ware preset has 1.27 as an amplitude.   @arouinfar suggested that [-1.5,1.5] might be a nicer range, because it feels less like a weird magic number.  It would make the amplitude sliders cleaner.  We'll probably need to expand the max "zoomed out" range for the Sum chart's y axis.   And expanding the range is less likely to break someone's lesson plan.

I'll give this a go.

**Comment by pixelzoom** [comment]
This was relatively painless to change, and I think it's much better.  We can tweak the Sum y-axis range later, but for now the maximum range is [-20,20], because 11 harmonics * 1.5 = 16.5.

@arouinfar please test drive in master or [1.0.0-dev.3](https://phet-dev.colorado.edu/html/fourier-making-waves/1.0.0-dev.3/phet/fourier-making-waves_en_phet.html).

**Comment by arouinfar** [comment]
@pixelzoom the amplitude range and sum zoom levels are looking good to me in mater, thanks!
