### ISSUE TITLE
Should zero-amplitude harmonics be plotted?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#23]
In the Java version, harmonics with 0 amplitude are not plotted in the Harmonics chart, in both the Discrete and Game screens.  For example, note that only the harmonics with non-zero amplitude (1 & 4) are plotted in this example:

<img width="1024" alt="screenshot_733" src="https://user-images.githubusercontent.com/3046552/101704179-69f6cf80-3a41-11eb-83ea-11babcece973.png">

Do you want that same behavior in the HTML5 version? Or do you want to plot zero-amplitude harmonics as a horizontal line that covers the x axis?  For example, zero-amplitude harmonics are plotted in this example:

<img width="837" alt="screenshot_734" src="https://user-images.githubusercontent.com/3046552/101704386-e5588100-3a41-11eb-9237-fd2052f70197.png">

You will only see one such zero-amplitude harmonic (in this case, the 2nd harmonic), because harmonics are rendered from front-to-back by increasing order.

Since you'll only be able to see one zero-amplitude harmonic, my recommendation is to hide them, as in the Java version.

If the sum is for some reason zero, we will of course plot that.

**Comment by pixelzoom** [comment]
As in the Java version, zero amplitude harmonics are not plotted.  Test drive in master.

**Comment by arouinfar** [comment]
> As in the Java version, zero amplitude harmonics are not plotted.

Perfect. I think showing zero amplitude harmonics clutters the graph and is not particularly useful. It would also be confusing when the zero-amplitude harmonic is emphasized or compared to the corresponding wavelength/period tool.

Master looks good, closing.
