### ISSUE TITLE
Credits for 1.1 release

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#246]
Credits will need to be updated for the 1.1 release #247.   The current credits are:

<img width="612" alt="screenshot_3623" src="https://github.com/user-attachments/assets/2a19e7a4-f014-4475-bc13-b8b1999948a1">

**Comment by pixelzoom** [comment]
Please specify changes to QA credits for https://github.com/phetsims/qa/issues/1178.

**Comment by Nancy-Salpepi** [comment]
Please add Matthew Moore to QA credits.

**Comment by pixelzoom** [comment]
Please specify changes to QA credits for https://github.com/phetsims/qa/issues/1186.

**Comment by KatieWoe** [comment]
Ashton Morris can be added

**Comment by pixelzoom** [comment]
I have updated the QA credits, and there was nothing else to address as the result of https://github.com/phetsims/qa/issues/1186.   So I will publish 1.1.0-rc.2, self-test, then publish 1.1.0.
