### ISSUE TITLE
Update Teach Tips for 1.1 release

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#248]
Related to #247.

**Comment by arouinfar** [comment]
Thanks for the reminder @pixelzoom. There's a relatively short list of updates for this release:

- [ ] Add `:cog-icon: Indicates this customization can be accessed from the Preferences menu within the simulation.` preface.
- [ ] Add cog icon to `locale` entry.

I'll make the updates shortly.

**Comment by arouinfar** [comment]
Done, closing.
