### ISSUE TITLE
Update screenshots for 1.1 release

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#249]
The 1.1 release (#247) will add the Preferences (gear) icon in the navigation bar.  Otherwise the UI should be the same.  @arouinfar up to you whether it's worth revising screenshots.

**Comment by arouinfar** [comment]
@Nancy-Salpepi unless you are bored to death, we can skip updating the screenshots for this release. I'll go ahead and close, but feel free to re-open if desperation strikes.
