### ISSUE TITLE
Long strings can cause info button to overlap display

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/fourier-making-waves#251]
**Test device**
MacBook Air M1 chip

**Operating System**
15.1.1

**Browser**
Safari 18.1.1

**Problem description**
For https://github.com/phetsims/qa/issues/1178, with ?stringTest=dynamic, on the Wave Packet screen the info button can overlap the Component Spacing display. I didn't see this on the Discrete screen. 

**Steps to reproduce**
1. Add ?stringTest=dynamic to the end of the url
2. Go to the Wave Packet Screen
3. Press the right arrow a couple of times

**Visuals**
<img width="261" alt="Screenshot 2024-12-02 at 3 58 42 PM" src="https://github.com/user-attachments/assets/9e2217b1-9d17-40ee-8522-14b2f27bc7b0">

**Comment by pixelzoom** [comment]
Reproduced in main.

**Comment by pixelzoom** [comment]
There was some funky hard-coded positioning of the Info buttons going on.  That has been changed to using scenery layout -- an HBox in this case.  There is a bit more space to the right of the InfoButton than there was before, but that can't be helped if we're going to do dynamic layout properly.

@Nancy-Salpepi please review, close if OK.

**Comment by Nancy-Salpepi** [comment]
Looks good on main. Closing.
