### ISSUE TITLE
Period label can be obscured by panel

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/fourier-making-waves#252]
**Test device**
MacBook Air M1 chip

**Operating System**
15.1.1

**Browser**
Safari 18.1.1

**Problem description**
For https://github.com/phetsims/qa/issues/1178 on the Discrete screen:
When the text for the period label is very long (eg. TTTT), the panel can partially overlap it. 

**Steps to reproduce**
1. Add ?stringTest=dynamic to the end of the url
2. Go to the discrete screen and select Space & Time under Graph Controls
3. Check the Period Checkbox
4. Press the right arrow key twice. 

**Visuals**
<img width="261" alt="Screenshot 2024-12-02 at 4 21 20 PM" src="https://github.com/user-attachments/assets/b598a311-ffee-4568-8a8e-02e5101605ce">

**Comment by pixelzoom** [comment]
All of the tools can be dragged such that part of them is behind the control panel. So it's not a matter of adjusting the drag bounds for the period tool, but a matter of adjusting its initial position.   So I moved the initial position to the left, and the screenshot below shows the situation when the label is at its maximum width.  The user can still drag the period such that part of it is behind the control panel - and that's OK, they can drag it back if that's a problem.

@Nancy-Salpepi please review, close if OK.

<img width="421" alt="screenshot_3625" src="https://github.com/user-attachments/assets/11a9df99-0beb-4c66-9dd8-9bff21fa6896">

**Comment by Nancy-Salpepi** [comment]
Looks good on main. 
Closing.
