### ISSUE TITLE
Expand interactive/focus highlights to include graph title

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/fourier-making-waves#254]
**Test device**
MacBook Air M1 chip

**Operating System**
15.1.1

**Browser**
Safari 18.1.1

**Problem description**
For https://github.com/phetsims/qa/issues/1178, clicking on a graph title expands and collapses the graph. With interactive highlights turned on or when using the keyboard, only the expand/collapse button is highlighted. Shouldn't the entire thing (title + button) be highlighted?

**Steps to reproduce**
1. Turn on interactive highlights in the preferences menu
2. Press the "Harmonics"  graph title on the Discrete screen or any graph title -- there is no highlight
3. Tab to any graph -- only the button is highlighted

This seems to be different than other published sims, for example Diffusion:
<img width="265" alt="Screenshot 2024-12-03 at 9 08 18 AM" src="https://github.com/user-attachments/assets/9bfb8a90-3f5c-4eaf-a54c-3ed8ffa34c80">

**Comment by pixelzoom** [comment]
AccordionBox (like in the Diffusion screen example above) handles putting the interactive highlight around the expandCollapseButton + label (aka title).  For the graphs in FMW, we are not using accordion boxes -- we have an expandCollapseButton with a label next to it, with no support for common-code support for putting an interactive highlight around both of them. 

Options are:
1. Convert to using AccordionBox, with invisible stroke and fill.  This would be a major change, and would impact many aspects of layout.  Estimate: 4-6 hours. (And I really don't want to go here.)
2. Add an option to ExpandCollapseButton to provide a label.  This would be a lot of work, and would require a lot of testing to verify that it does not cause regressions in sims that use ExpandCollapseButton or AccordionBox. Estimate: 4-8 hours. 
3. Create a new common-code UI component, something like LabeledExpandCollapseButton.  Estimate 3-6 hours.
4. Write sim-specific code that puts the interactive highlight around expandCollapseButton + label. This would not impact common code or other sims, but would result in more sim-specific code, and nothing that can be reused by other sims. Estimate: 2-3 hours.
5. Do nothing for this sim and create a GitHub issue requesting common-code support for "expandColapseButton + label" interactive highlight.
6. Do nothing.

I recommend option 4, 5, or 6.

@arouinfar your thoughts?

**Comment by arouinfar** [comment]
Thanks for writing up the options @pixelzoom. I prefer option 5. In the context of Fourier, option (6) is a valid choice for ExpandCollapseButton. However, there could be instances of ExpandCollapseButton where including the label in the interactive highlight would be more necessary. Please proceed with 5 and open an issue.

**Comment by pixelzoom** [comment]
Thanks @arouinfar.

The common-code request is being tracked in https://github.com/phetsims/sun/issues/919.

Closing this issues a "won't fix".
