### ISSUE TITLE
Amplitude Controls number spinner doesn't return to default with Reset All

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/fourier-making-waves#256]
**Test device**
MacBook Air M1 chip

**Operating System**
15.1.1

**Browser**
Safari 18.1.1

**Problem description**
For https://github.com/phetsims/qa/issues/1178, on any game level, if I change the amount of amplitude controls present, that value isn't reset with Reset All. This also happens in published. 

**Steps to reproduce**
1. On the Game screen, select Level 1 
2. Increase the number of amplitude controls 
3. Return back to the main Game screen
4. Press Reset All
5. Select Level 1 -- number of amplitude controls doesn't reset back to 2. 

**Visuals**

https://github.com/user-attachments/assets/de8d9b51-50a3-4ad3-b1aa-dd4407aa499a

**Comment by Nancy-Salpepi** [comment]
@pixelzoom, I asked Amy yesterday on Slack:

Nancy:
Should pressing Reset All on the game screen reset the Amplitude Controls number spinner? It resets the Amplitudes back to zero, so why not the number spinner? This also happens in published.
Second issue that I also see in published as well….the Check Answer button is still enabled after the erase button is pressed. Seems odd. Thoughts?

Amy Rouinfar
  
1. Good find. That’s definitely a bug. All controls should go back to their default state on Reset All.
2. Also seems like a bug to me. Check Answer requires some amount of non-zero amplitudes to initially be enabled, so it makes sense to disable it when erased.

**Comment by pixelzoom** [comment]
Thanks @Nancy-Salpepi.  Fixed and ready for your review, close if OK.

**Comment by Nancy-Salpepi** [comment]
All fixed!
Closing.
