### ISSUE TITLE
Check Answer button still enabled after erase

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/fourier-making-waves#257]
**Test device**
MacBook Air M1 chip

**Operating System**
15.1.1

**Browser**
Safari 18.1.1

**Problem description**
For https://github.com/phetsims/qa/issues/1178, on the Game Screen the Check Answer button remains enabled after the Erase button is pressed.  This also happens in published. 

**Steps to reproduce**
1. On any level of the Game screen, move an amplitude control --Check Answer button becomes enabled
2. Press Erase button -- Check Answer button is still enabled 

**Visuals**
<img width="973" alt="Screenshot 2024-12-03 at 1 11 26 PM" src="https://github.com/user-attachments/assets/04a8a993-a5ef-47b8-a4e3-e077c9f18ed8">

**Comment by pixelzoom** [comment]
@Nancy-Salpepi please review, close if OK.

**Comment by Nancy-Salpepi** [comment]
Fixed on main. Closing.
