### ISSUE TITLE
Should time controls be disabled when there is no possibility of animation?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#26]
Should the time control be disabled when the domain is not set to "space & time"?  There is no animation occurring otherwise.   

The concern is that the user might play with the time control when domain is "space" or "time", see that it does nothing with those settings, leave the sim paused, and never set it to play for "space & time".  If the control is disabled, then the first time they select "space & time", they will see animation. 

In the Java version, the control is always enabled.

**Comment by pixelzoom** [comment]
I went ahead and enabled the time controls only for "space & time".  Test-drive in master.

**Comment by arouinfar** [comment]
I think it's very weird to have an enabled TimeControlNode when it doesn't actually do anything. The behavior in master looks natural to me, thanks @pixelzoom!
