### ISSUE TITLE
'sine' and 'cosine' radio button group

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#28]
Re this radio button group in the Discrete screen control panel:

<img width="323" alt="screenshot_742" src="https://user-images.githubusercontent.com/3046552/101968363-12409b80-3bdc-11eb-9915-c10f8129c599.png">

These buttons determine whether the waveform is approximated using sines or cosines.  So maybe we should relabel these as "sines" and "cosines" (plural)?

It might also be nice to label this button group, give it a name/concept that the teacher can refer to.  A name would also help me in naming things in the code.  It's currently called "wave type", as it was in the Java code.

@arouinfar thoughts?

**Comment by pixelzoom** [comment]
12/17/2020 design meeting @arouinfar @ariel-phet @kathy-phet @pixelzoom 

* Change waveform "sine/cosine" to "sinusoidal"
* Change "sine" and "cosine" radio buttons to "sin" and "cos"
* Label radio buttons with "Series:"

**Comment by pixelzoom** [comment]
@arouinfar Done, ready for review in master. 

Note that I changed "sine/cosine" to "sinusoid", not "sinusoidal".  "sinusoidal" is an adjective; if we used that, then we should also use "triangular".

**Comment by arouinfar** [comment]
> Note that I changed "sine/cosine" to "sinusoid"

Good catch, thanks!

Everything looks good in master, closing.
