### ISSUE TITLE
usability of amplitude sliders

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#29]
In the Java version, there is a "wiggle me" telling the user that amplitude bars are draggable:

<img width="564" alt="screenshot_744" src="https://user-images.githubusercontent.com/3046552/101968524-de19aa80-3bdc-11eb-8944-94b81522bf3b.png">

First, should we interview to see if there's a usability issue?  Do students quickly discover that these bars are interactive?

Should we make these bars look more like sliders?  Maybe replace the black bars with "grippy" bars, something that looks like a slider thumb, something that communicates "I'm draggable" ?  Other ideas?  (I really would like to avoid a "wiggle me" - that always feels like design failure to me.)

**Comment by pixelzoom** [comment]
Here's what I came up with.  I started by putting grippy dots on the thumb.  Then I thought it would be nice to color-code the dots to the harmonic, so that you know what color is used for a harmonic even when it's amplitude is zero.   For example, the "square" waveform looks like this:

<img width="847" alt="screenshot_748" src="https://user-images.githubusercontent.com/3046552/102118393-dfc1b900-3dfc-11eb-975f-3e212200cd49.png">

I should also note that, like the Java version, you can click anywhere in the "track" (including above/below a bar) to make the slider jump to that value.

**Comment by pixelzoom** [comment]
Here's what I came up with.  I started by putting grippy dots on the thumb.  Then I thought it would be nice to color-code the dots to the harmonic, so that you know what color is used for a harmonic even when it's amplitude is zero.   For example, the "square" waveform looks like this:

<img width="847" alt="screenshot_748" src="https://user-images.githubusercontent.com/3046552/102118393-dfc1b900-3dfc-11eb-975f-3e212200cd49.png">

I should also note that:

* Like the Java version, you can click anywhere in the "track" (including above/below a bar) to make the slider jump to that value

* Like the solid black bars, you can't see any of the bar for a very small amplitude value, because the value position is the center of the thumb.  This seems OK, but I thought I should point it out.

**Comment by pixelzoom** [comment]
Note in the above screenshot that I made the thumb a little wider than the track (bar), and gave the thumb rounded corners. Imo it makes it look more like a slider thumb, like a separate piece that you should grab.

It's also easy to make the thumb the same width as the track (bar) and lose the rounded corners, like this:

<img width="654" alt="screenshot_750" src="https://user-images.githubusercontent.com/3046552/102131140-038dfa80-3e0f-11eb-87c9-0e1ea1c8dc6e.png">

**Comment by arouinfar** [comment]
The rounded thumbs currently in master look great! I'll tag for design meeting for team sign-off.

> Like the solid black thumbs, you can't see any of the bar for very small amplitude values, because it's covered by the thumb. The value position is (necessarily) the center of the thumb. This seems OK since the thumb is not centered on zero in these cases, and since the values are shown in NumberDisplays. But I thought I should point it out.

This all sounds reasonable to me. If we want the sliders to look interactive, we are going to need some sort of visual decoration on the thumb. Regardless of what that decoration looks like, it will somewhat obscure the bar height, but I think it's an acceptable trade-off. The graph lines help users estimate of the value and visually compare the amplitudes. The precise value is provided in the NumberDisplay.

**Comment by pixelzoom** [comment]
Great, glad you like them.  At first they felt a little "industrial" to me. But it's not exactly an organic-looking UI (or domain), and they've grown on me.

**Comment by pixelzoom** [comment]
12/17/2020 @arouinfar @kathy-phet @ariel-phet @pixelzoom 

@kathy suggested to make the thumbs narrower than the bars, like so:

<img width="857" alt="screenshot_768" src="https://user-images.githubusercontent.com/3046552/102547517-91b7ea00-4076-11eb-93e6-48b53facfedd.png">

I'll check this change in, then self-assign to adjust pointer areas.

**Comment by pixelzoom** [comment]
Pointer areas have been adjusted.  Here's what it looks like with and without `?showPointerAreas`:

<img width="842" alt="screenshot_770" src="https://user-images.githubusercontent.com/3046552/102553048-743b4e00-407f-11eb-9af2-450e7fd1f47b.png">

<img width="852" alt="screenshot_771" src="https://user-images.githubusercontent.com/3046552/102553052-769da800-407f-11eb-9787-570066a00f98.png">

Note that pointer areas are also a bit moot, since the slider tracks (even the invisible part) function like a bit pointer area.

Back to @arouinfar for sign-off.

**Comment by arouinfar** [comment]
Looks good in master, thanks @pixelzoom!
