### ISSUE TITLE
evaluate griddle for use in this sim

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#3]
This issue will evaluate whether the chart requirements of this sim can be met by (1) using existing griddle components, or (2) adding addition functionality to griddle.

**Comment by pixelzoom** [comment]
The Amplitude graph appears in the _Discrete_ and _Wave Game_ screens.  It looks like this:

<img width="739" alt="screenshot_566" src="https://user-images.githubusercontent.com/3046552/93157195-fa35aa80-f6c6-11ea-8649-f575ccfb923c.png">

The number of harmonics is variable from [1,11].  Each bar is a slider. 

The bars are custom (see `AmplitudeSlider`), and unlikely to be used in other sims.  The graph only has an y-axis, which I don't see supported in griddle.  So there is currently nothing in griddle that I would use here, and nothing that I would add to griddle from this sim.

**Comment by pixelzoom** [comment]
For the charts shown below, I'll attempt to use XYChartNode, and see what problems I encounter.   The "Harmonics" chart consists of sine/cosine functions, so describing them as XY data series (`DynamicSeries`)  may not be the most efficient approach. I'm also concerned about griddle's ability to handle the "Components" chart.

<img width="743" alt="screenshot_645" src="https://user-images.githubusercontent.com/3046552/97916467-3e7d1880-1d10-11eb-82dd-b9595d3f2675.png">
<img width="740" alt="screenshot_646" src="https://user-images.githubusercontent.com/3046552/97916476-40df7280-1d10-11eb-80da-8b5a5446f80c.png">

**Comment by pixelzoom** [comment]
For the chart below, I'll attempt to use BarChartNode, and see what problems I encounter.

<img width="738" alt="screenshot_647" src="https://user-images.githubusercontent.com/3046552/97916873-d7ac2f00-1d10-11eb-9f5f-485f7b0b336e.png">

**Comment by pixelzoom** [comment]
For the chart below, I cannot use BarChartNode, because it does not support XY data sets. See https://github.com/phetsims/griddle/issues/76.  So I plan to implement this chart for Fourier, and evaluate for migration to griddle later.

<img width="738" alt="screenshot_647" src="https://user-images.githubusercontent.com/3046552/97916873-d7ac2f00-1d10-11eb-9f5f-485f7b0b336e.png">

**Comment by pixelzoom** [comment]
I've completed my review of griddle.  

Specific to Fourier requirements:
* griddle has no support for the Amplitude chart in the Discrete screen, where we need interactive bars.
* griddle has no support for XY bar charts like the Amplitude chart in the Continuous screen.
* griddle's support for XY line plots might be usable for the Harmonics and Sum charts, but it currently lacks a proper "plot" abstraction.
* griddle's support for model-view transforms and dynamic ranges needs work, phetsims/griddle#77. 

Generally:
* griddle's biggest problem is that it lacks an "overall design". I'm concluding this based on the strange mix of terminologies, approaches, options, etc. and general lack of consistency in APIs.
* griddle appears to be a collection of sim-specific components that were moved here so that they could be reused. Since there was no general design plan, their generalization was probably minimal, and that's probably the reason why there are inconsistent terminologies, APIs, etc.
* griddle is currently used by a small number of sims, and does work for the limited features needed by those sims. The fact that usage is relatively small is good, because imo griddle needs a lot of work, and these sims will need to be changed.
* Outside of adding things when needed by sims, there has been minimal work on griddle. There are 20 open issues, some as old as 2015. There were some improvements and generalizations around the time of my last review (for potential use in Natural Selection, see https://github.com/phetsims/natural-selection/issues/21). Otherwise, PhET has not allocated resources to griddle.  
* I get the impression that the plan for griddle is to add features as needed.  That's not a sustainable or cost-effective approach to developing a charting package.  It also doesn't make it appealing to contribute to griddle, or to use it in a sim, because you have to deal with the near-certainty that you'll need to make big changes.

Recommendation:
Do not use griddle in Fourier.  As with Natural Selection (again see https://github.com/phetsims/natural-selection/issues/21), implement sim-specific charts. If PhET is willing to incur the additional cost, attempt to keep Fourier charts general enough that they might be migrated to griddle, contingent on griddle having an "overall design" when the time comes to migrate.  @ariel-phet does this plan reasonable?

**Comment by pixelzoom** [comment]
My review of griddle is complete. Here's a summary and recommendations for Fourier. 

Specific to Fourier requirements:

* griddle has no support for the interactive bars (sliders) needed for the Amplitudes chart in the Discrete screen.
* griddle has no support for XY bar charts, needed for the Amplitudes chart in the Continuous screen.
* griddle’s XYChartNode might be usable in Fourier, but there are concerns (see above), and not without significant changes.
* griddle’s support for dynamic XY ranges needs work, see https://github.com/phetsims/griddle/issues/77.  This affects the ability to support zoom and auto scale, needed by the Harmonics, Components, and Sum charts.
* griddle’s support for model-view transform needs work, see https://github.com/phetsims/griddle/issues/77.  This affects all of the charts in Fourier.

General observations:

* PhET has not allocated resources to development of griddle, and this will not change in the timeframe of Fourier implementation.  
* griddle has not evolved much since I reviewed it for potential use in Natural Selection, see https://github.com/phetsims/natural-selection/issues/21.  There was a bit of cleanup done as the result of that review.  But there are still 20 open issues, some as old as 2015. 
* griddle’s biggest problem is that it lacks an “overall design”.  It’s a collection of components that have been migrated from sims, without consideration for how they fit into the griddle framework (because there is no framework). The result is inconsistent terminology, odd APIs, etc.
* griddle is being “built” by identifying components for reuse “as needed”, moving those components to griddle from sims, then adding features later as they are needed.  This is an expensive way to develop a chart library, and (without an “overall design”) is unlikely to result in a good API.  It also makes using griddle in a sim (like Fourier) unattractive, since there will certainly be costly diversions that involve changing griddle and sims that use griddle.

Recommendation:

Do not use griddle for charts in Fourier.  As in Natural Selection, implement sim-specific charts, generalizing where it makes sense to do so. If PhET is willing to incur the additional cost, and an “overall design” for griddle is put in place, consider migrating Fourier charts to griddle at the completion of Fourier implementation.

@ariel-phet Is this an acceptable plan?

**Comment by ariel-phet** [comment]
Definitely an acceptable plan @pixelzoom

**Comment by pixelzoom** [comment]
I'd like to clarify the "migration to griddle" aspect of this issue before closing. 

The plan (as I described it in https://github.com/phetsims/fourier-making-waves/issues/3#issuecomment-721293038) is:
> ... If PhET is willing to incur the additional cost, and an “overall design” for griddle is put in place, consider migrating Fourier charts to griddle at the completion of Fourier implementation.

Note that migration is not a given, it is very much conditional. If there is no "overall design", there is unlikely to be any migration.

In https://github.com/phetsims/griddle/issues/54#issuecomment-721481880 (the "big picture" for griddle), @ariel-phet said:
> Sounds like there won't be much movement on this topic for Fourier, so closing.

... which I interpret to mean that no such "overall plan" will be identified in the Fourier timeframe.  If that's the case, then the expectation should be that migration to griddle may be minimal or nonexistent.

And in https://github.com/phetsims/griddle/issues/54#issuecomment-723270325, @samreid said:
> * Any charting parts that are added for Fourier should be added in griddle, with the intent that they can be reused in the future

Regardless of intent, this won't happen (or won't happen well) without requirements. See my full reply in https://github.com/phetsims/griddle/issues/54#issuecomment-723337860.

So to clarify how I'm going to proceed with charts in Fourier...  If griddle requirements exist when I start work on a charts, I will attempt to incorporate them into what I implement in Fourier. (I anticipating beginning to implement Fourier charts next week.) I will also try to use my best judgement about how to keep APIs general/flexible, based on my experience with other charting packages.  I will not attempt to build in features that are not needed by Fourier, unless those features have been identified as "needed by griddle".

@ariel-phet does this part of the plan sound acceptable?

**Comment by samreid** [comment]
Here are some parts that seem like they should developed in Griddle (if they aren't there already) for use in Fourier:

### Considering the Amplitude Chart
![image](https://user-images.githubusercontent.com/679486/98426145-f97d1d00-2054-11eb-92bd-637ebf2b609f.png)

(1) The chart area that shows the background, border, gridlines, tickmark and labels.
(2) An easy way to embed arbitrary Nodes on a chart (that are aware of the transform)

### Considering the Harmonics Chart
![image](https://user-images.githubusercontent.com/679486/98426215-3812d780-2055-11eb-885d-2b3096058736.png)

(3) Horizontal and vertical zoom buttons.  Rendering the curve can be done using a Shape Node combined with (2) above.

By building the modular components (1) (2) and (3) in griddle, we lay a foundation that will lead to ease-of-use and reusability for our chart-based sims.

**Comment by pixelzoom** [comment]
@samreid said:
> Here are some parts that seem like they should developed in Griddle (if they aren't there already) for use in Fourier:

I disagree with all of these.

> (1) The chart area that shows the background, border, gridlines, tickmark and labels.

Something that is supposed to fill this role already exists.  It's griddle's `GridNode`.  It does not support charts like "Amplitudes" where there is no x-axis scale.  It will be considered for the other charts in Fourier. (It wasn't used in Natural Selection because it didn't exist at the time.)

> (2) An easy way to embed arbitrary Nodes on a chart (that are aware of the transform)

If "embed" implies that the chart is somehow responsible for the arbitrary Nodes...  I see no reason to do this, because it increases coupling.  With well-defined model-view transforms, arbitrary Nodes can be positioned by the client, or a sim-specific subclass.  The problem with griddle (and a big reason why it's not being used in Fourier) is that it does not have a consistent API for transforms (see https://github.com/phetsims/griddle/issues/77), something that should be part of an "overall plan" for griddle.  And if that work is not going to be done, then there is little to be gained by writing more code that depends on griddle's current transform APIs. 

> (3) Horizontal and vertical zoom buttons.  ...

We already have zoom button implementations, and there's no reason for them to be specific to griddle.  Fourier will be using the more modern-looking `ZoomButtonGroup`, which was implemented for Natural Selection and migrated to scenery-phet.

> ... Rendering the curve can be done using a Shape Node combined with (2) above.
  
The griddle client shouldn't have to deal with Shape or Path.  Rendering the curve should be the responsibility of a "plot" abstraction, which is currently missing from griddle - see https://github.com/phetsims/griddle/issues/74.

**Comment by samreid** [comment]
All of my remarks were about “parts that seem like they should [be] developed in Griddle (if they aren’t there already)”.  Are you pointing out things that “aren’t there already” or are you making the stronger claim that “they should never be developed in griddle”?

> Something that is supposed to fill this role already exists -- griddle's GridNode. It does not support charts like "Amplitudes" where there is no x-axis scale.

So why not add support for this in GridNode which we agree is "supposed to fill this role" instead of creating a duplicate that will have to be built, designed, debugged, maintained?

> If "embed" implies that the chart is somehow responsible for the arbitrary Nodes

No, the chart would not be responsible for the Nodes other than (a) giving them a coordinate frame and maybe (b) an optional clipping area.

> The problem with griddle (and a big reason why it's not being used in Fourier) is that it does not have a consistent API for transforms (see phetsims/griddle#77), something that should be part of an "overall plan" for griddle. And if that work is not going to be done

I recommend that we make any necessary improvements to griddle as part of the work on Fourier, unless Fourier is supposed to be a "rush job".

> We already have zoom button implementations, and there's no reason for them to be specific to griddle. 

Thanks for reminding me, that sounds perfect.

> The griddle client shouldn't have to deal with Shape or Path -- that's an implementation detail, and one strategy. Rendering the curve should be the responsibility of a "plot" abstraction, which is currently missing from griddle

So it sounds like we agree that should be added to griddle?  As long as you need an implementation of that for Fourier, why not start implementing it in griddle in the first place?  Is the primary concern that we don't have a complete set of requirements for it?

**Comment by pixelzoom** [comment]
> So it sounds like we agree that should be added to griddle?  

Yes.  But in a way that fits with the vision for PhET's chart library. Not as something that's just moved to griddle from a sim.

> As long as you need an implementation of that for Fourier, why not start implementing it in griddle in the first place? 

Because without griddle "big picture", anything I migrate from Fourier will further contribute to griddle's core problems - inconsistent APIs, sim-specific approaches, and lack of a vision for PhET's chart library.  I'm also not interested in being the griddle architect, and PhET is allocating no resources to griddle "big picture" during the Fourier timeframe.

> Is the primary concern that we don't have a complete set of requirements for it?

No.  Requirements don't need to be "complete".  What's lacking is resources allocated to identifying requirements. Identification of sim needs and a roadmap would be a reasonable starting point.

**Comment by samreid** [comment]
@pixelzoom and I discussed this issue in a zoom call.  Afterwards, I posted this in slack:

> It was mentioned in https://github.com/phetsims/fourier-making-waves/issues/3 that we won’t have time to add any features to Griddle to support Fourier.  We also plan to start Eating and Exercise soon, which has charting features (though I think charts will not be in the first screen).  It seems like it would be most efficient to prepare a nice foundation before starting on simulations with charts.  Is it too late to add support to Griddle for Fourier?  Each extra copy we develop has all the expenses of: design, implementation, debugging,  documenting, QA testing and maintaining.  Yes, we can save some time in the short term by avoiding questions about generality, but the more we keep making sim-specific implementations of charts, the more technical debt we accrue.

After some discussion about other projects and timelines, I said:

> May I please have time to do a mini-sprint in Griddle, to see if we can get it ready for Fourier?

@ariel-phet replied:

> @samreid I am all for that

I'll open side issues for the parts I investigate.

**Comment by ariel-phet** [comment]
@samreid leaving this issue assigned to you for the moment as you add linked issues

**Comment by samreid** [comment]
I want to report on the status of the mini-sprint, so we can coordinate and avoid duplication of effort.  In short, it is going very well. I opened https://github.com/phetsims/griddle/issues/86 and have been working in an associated branch.  The proposal fixes many of the problems that have open issues in griddle, and makes it possible for griddle to render charts that couldn't be rendered by griddle before, such as https://github.com/phetsims/fourier-making-waves/issues/14#issuecomment-727150626.  @jonathanolson reviewed the proposed strategy, and agreed it is a significant improvement, and I have incorporated some of his feedback.

It is not ready for @pixelzoom to start developing with, but I wanted to mention it sooner rather than later in the interest of coordination and avoiding duplication of effort.  I'd like to touch base with @pixelzoom before he spends much/any time developing sim-specific charts for Fourier.  Also, at @kathy-phet's recommendation, I have added this to Thursday's developer meeting agenda.

**Comment by samreid** [comment]
I don't have the correct data, but here is the current status of the Harmonics chart (in the griddle branch), which uses the new zoom controls that were developed during Natural Selection:

![image](https://user-images.githubusercontent.com/679486/99157115-90fcf400-2683-11eb-9d65-1657e9fd7a9a.png)

It zooms, but it doesn't highlight one data set at a time yet.

**Comment by samreid** [comment]
How many curves need to be rendered on the "components" chart? On my machine, it's taking around 200ms to render 500 curves:

![image](https://user-images.githubusercontent.com/679486/99157779-467e7600-2689-11eb-980b-736b956a8104.png)

**Comment by pixelzoom** [comment]
> How many curves need to be rendered on the "components" chart?

The number of curves equals the number of Fourier components. The number of Fourier components is based on the "Spacing between Fourier components" slider in the control panel:

<img width="280" alt="screenshot_681" src="https://user-images.githubusercontent.com/3046552/99290154-2373d380-27fb-11eb-8ad2-3845ceab5bc5.png">

The slider snaps to tick marks, so the 5 values that we need to show are:

| Spacing | Fourier components |
| ---: | ---: |
| 2𝜋 | 11 |
| 𝜋 | 23 |
| 𝜋 / 2 | 47 |
| 𝜋 / 4 | 95 |
| 0 | infinite |

For 0, we should "Cannot show infinite number of components", so the max number of curves is 95.

**Comment by pixelzoom** [comment]
Btw... For performance reasons, the Java version flattens the "Components" graph to an image.  See D2CComponentsView.java and FlattenedChart.java.  Unlikely that we'll need to do that in the JavaScript implementation, but thought I'd mention it.

**Comment by samreid** [comment]
@pixelzoom and I discussed this today, and I wrote notes in https://github.com/phetsims/griddle/issues/86#issuecomment-728347949.  We also have developer meeting agenda items scheduled for Thursday.  I'm not sure how @pixelzoom will want to proceed with this issue, but I'll unassign myself for now.

**Comment by pixelzoom** [comment]
Summary of the notes in https://github.com/phetsims/griddle/issues/86#issuecomment-728347949... 

Change of plans. Instead of developing sim-specific charts for Fourier, I'll be using the result of @samreid's "sprint", a next-gen griddle sprint (aka "bamboo").

I think we can close this issue.
