### ISSUE TITLE
Add a key for math symbols

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#30]
This sim has a relatively large number of math symbols, and the meaning of most of them is not identified in the sim.  See list below, taken from model.md.

Should we add a key that identifies these symbols? Maybe a dialog, that is accessed via an "Info" button to the right of the "Math Form" label in the Discrete control panel? And somewhere else in the Continuous screen?

Discrete screen:
* A = amplitude
* f = frequency, in Hz
* λ = wavelength, in meters
* k = wave number
* L = string length, if this were a plucked string, in meters
* n = harmonic number, order, or mode
* t = time, in milliseconds
* T = period, in milliseconds
* x = position in space along L, in meters

Continuous screen:
* A = amplitude
* λ = wavelength, in meters
* k = wave number
* σ = Gaussian wave packet width, in radians/meter
* t = time, in milliseconds
* T = period, in milliseconds
* ω = angular frequency, in radians
* x = position in space along L, in meters

**Comment by pixelzoom** [comment]
12/17/2020 design meeting @arouinfar @kathy-phet @ariel-phet @pixelzoom 

Put info button in upper-right corner of control panel, opens dialog titled "Symbols".

**Comment by pixelzoom** [comment]
@arouinfar ready for review in master, screenshot below.  Let me know if you'd like to change any of the symbol descriptions.

<img width="1062" alt="screenshot_776" src="https://user-images.githubusercontent.com/3046552/102573466-bed2bf80-40ab-11eb-8c59-3f6b82b12235.png">

**Comment by pixelzoom** [comment]
@arouinfar After reviewing, please keep this issue open and assign to me.  We'll need to decide where to put the Info button in the Continuous screen.

**Comment by arouinfar** [comment]
@pixelzoom the symbols dialog looks good. My only suggestion would be to abbreviate all units for consistency. Can you change "meters" to "m" and "milliseconds" to "ms"?

For the Continuous screen, let's start by putting the button in the upper right corner of the control panel.

**Comment by pixelzoom** [comment]
Unassigning this until I get to the Continuous screen.

**Comment by pixelzoom** [comment]
This is now implemented for the Continuous screen.  So ready for review by @arouinfar.   I think the symbols dialog for the Discrete screen is pretty solid.  I'm less sure about the Continuous screen.

**Comment by pixelzoom** [comment]
I discovered another symbol in the Continuous screen. In the Java version, set component spacing to 0, and you'll see this equation above the Sum chart:

<img width="303" alt="screenshot_1021" src="https://user-images.githubusercontent.com/3046552/121430860-e2c5de00-c935-11eb-8622-743fab431227.png">

Should "d" be described in the symbol dialog? Should it use normal or italic font style?

**Comment by arouinfar** [comment]
There's currently a mix of abbreviated (Hz) and spelled-out units. Given the target audience, we could probably abbreviate them all.

"Width" is a bit tricky when talking about Gaussians. There is no one width, as it varies with height. Depending on your field, you may be interested in the full width at half maximum (FWHM) or 1/e<sup>2</sup> of the max (used for laser beam diameter). Regardless, the standard deviation (σ) determines how broad the distribution will be. From the Teacher Tips:
>In the Discrete to Continuous tab, σ<sub>k</sub> and σ<sub>x</sub> are the standard deviations of the gaussian curves in fourier and position space, respectively.

I think it's still appropriate to refer to σ as the "width" in the control panel since it's a more conceptually useful term, but the Symbols dialog should use more precise language.

Change requests
- [ ] Abbreviate all units
- [ ] Add rad/m units to k (see #79)
- [ ] Change σ entry to: standard deviation of Gaussian wave packet

**Comment by pixelzoom** [comment]
Change requests completed, back to @arouinfar for review in master. 

Re this request:
> - [ ] Change σ entry to: standard deviation of Gaussian wave packet

I'm assuming that you did not include units here because they vary depending on domain (rad/m or rad/ms).  If you'd like me to add units, let me know.

**Comment by arouinfar** [comment]
Looks good in master, thanks @pixelzoom.

> I'm assuming that you did not include units here because they vary depending on domain (rad/m or rad/ms). If you'd like me to add units, let me know.

Correct. I'd prefer to keep the sigma entry general so it can apply to both σ<sub>k</sub> and σ<sub>x</sub>.
