### ISSUE TITLE
relocate "Math Form" control?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#32]
In the _Discrete_ screen, "Math Form" is currently its own section in the control panel:

<img width="249" alt="screenshot_755" src="https://user-images.githubusercontent.com/3046552/102400022-927d4d00-3f9e-11eb-8625-e83a4382925a.png">

Since it controls how the charts are labeled (equations above the graph, numeric vs symbol tick labels on the x axis), should this control be moved to the "Graph Controls" section, and simply labeled "Math Form"?  Something like this:

<img width="255" alt="screenshot_756" src="https://user-images.githubusercontent.com/3046552/102400649-7b8b2a80-3f9f-11eb-81fb-283c5989574e.png">

EDIT: Imo, the control panel still needs layout polishing.  But this should give you the general idea.

**Comment by pixelzoom** [comment]
12/17/2020 design meeting @arouinfar @kathy-phet @ariel-phet @pixelzoom 

* Move "Math Form" control up to Graph Controls
* Rename "Math Form" to "Equation"

**Comment by pixelzoom** [comment]
@arouinfar Changes have been completed, ready for review in master.

**Comment by arouinfar** [comment]
Thanks @pixelzoom. Looks good in master.
