### ISSUE TITLE
polish suggestions - Discrete screen

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#34]
12/17/2020 design meeting @arouinfar @kathy-phet @ariel-phet @pixelzoom 

Suggestions for polishing the Discrete screen:

- [ ] @ariel-phet: Somehow tie together the pieces of each of the 3 main areas (maybe a vertical bar at left?)
   _Moved this one to #37_

- [x] @ariel-phet: Reduce size of equations above chart (but keep summation indices at current size)
    _Reduced from 18 to 14, summation indices are still 10._

- [x] @ariel-phet: Reduce vertical space between equations and top of chart
    _Reduced from 5 to 3._

- [x] @kathy-phet: Move top of 'A's above amplitude sliders up
    _'A's now encroach into the top margin, such that they are 7 pixels from the top of the layoutBounds_

- [x] @ariel-phet: Use 'black' for Amplitude grid lines
- [x] @pixelzoom: move gridline colors to ColorProfile
    _You can now edit the grid line colors in colors.html, if you want to tweak them further._

**Comment by pixelzoom** [comment]
I move the first suggestion to #37, because it's more involved.  The others have been addressed in master. 

@arouinfar @ariel-phet @kathy-phet please review.

**Comment by pixelzoom** [comment]
I should mention that you can now edit the grid line colors in colors.html, if you want to tweak them further.

**Comment by kathy-phet** [comment]
My 2 cents: I like this without pursuing #37. I imagine it will be used a lot without the equations up, and its pretty nicely separated in that case. I think I prefer that than losing the space that would be needed to get the equations to fall into a box. 

Chiming in on other small aspects. I would add a bit more vertical spacing/padding in the right hand controls section. There is room to make the whole control taller so should be fine on space. I like the new Harmonics control, but I would put more padding between it and the Waveform (so we can increase the touch area more too of those smaller buttons).  There seems to be ample room above the titles (e.g. Measurement Tools) but it feels a bit crowded vertically of the things below the titles. I like the info button. 

We discussed keeping the A's at the top aligned with the control box on the right, moving them both up by the same amount. I'm fine either way, just noting that we had discussed it. 

Overall, looking really nice!

**Comment by pixelzoom** [comment]
Thanks for the feedback @kathy-phet.

> Chiming in on other small aspects.  ...

Thanks for this. I'm planning a "polish" of the control panel after it has stabilized.  What things should be aligned, spacing, etc.  I'm tracking that in https://github.com/phetsims/fourier-making-waves/issues/38, and will note your comments there.

> We discussed keeping the A's at the top aligned with the control box on the right, moving them both up by the same amount. I'm fine either way, just noting that we had discussed it.

Sorry, I misunderstood.  Most (all?) of the HTML5 sims that I've worked on have standard x & y margins, which I feel is important to a clean look, as well as usability on touch devices where you can't resize the browser window.  To me, many PhET sims feel a little cramped on touch devices.   That said, I thought we discussed allowing the A's to encroach into the top margin.  I didn't hear the request to move the control panel up to.  I don't think it's important (or even noticeable) that the A's don't top-align with the control panel, we have plenty of vertical space for the control panel, and keeping a respectable margin looks nicer (less cramped) to me on touch devices.  So I would prefer to keep a nice margin above the control panel.  But happy to discuss more.

**Comment by pixelzoom** [comment]
Thanks for the feedback @kathy-phet.

> My 2 cents: I like this without pursuing #37. I imagine it will be used a lot without the equations up, and its pretty nicely separated in that case. I think I prefer that than losing the space that would be needed to get the equations to fall into a box.

That's my preference too.  I did a quick-and-dirty implementation that puts subtle colored background behind the 3 sections.  The background for the Sum area needs to be noticeably taller, with lots more space above the chart.  It looked very lopsided to me, and we'd lose a lot of space to make it look balanced. 

> Chiming in on other small aspects.  ...

Thanks for this. I'm planning a "polish" of the control panel after it has stabilized.  I'm tracking that in https://github.com/phetsims/fourier-making-waves/issues/38, and will note your comments there.

> We discussed keeping the A's at the top aligned with the control box on the right, moving them both up by the same amount. I'm fine either way, just noting that we had discussed it.

Sorry, I misunderstood.  Most (all?) of the HTML5 sims that I've worked on have standard x & y margins, which I feel is important to a clean look, as well as usability on touch devices where you can't resize the browser window.  To me, many PhET sims feel a little cramped on touch devices.   That said, I thought we discussed allowing the A's to encroach into the top margin.  I didn't hear the request to move the control panel up to.  I don't think it's important (or even noticeable) that the A's don't top-align with the control panel, we have plenty of vertical space for the control panel, and keeping a respectable margin looks nicer (less cramped) to me on touch devices.  So I would prefer to keep a nice margin above the control panel.  But happy to discuss more.

**Comment by ariel-phet** [comment]
Looking good, I commented in #37

**Comment by arouinfar** [comment]
@pixelzoom I think the pixel polishes look excellent

>>We discussed keeping the A's at the top aligned with the control box on the right, moving them both up by the same amount. I'm fine either way, just noting that we had discussed it.
>
>Sorry, I misunderstood. Most (all?) of the HTML5 sims that I've worked on have standard x & y margins, which I feel is important to a clean look, as well as usability on touch devices where you can't resize the browser window. To me, many PhET sims feel a little cramped on touch devices. That said, I thought we discussed allowing the A's to encroach into the top margin. I didn't hear the request to move the control panel up to. I don't think it's important (or even noticeable) that the A's don't top-align with the control panel, we have plenty of vertical space for the control panel, and keeping a respectable margin looks nicer (less cramped) to me on touch devices. So I would prefer to keep a nice margin above the control panel. But happy to discuss more.

The panel pixel polishing in #38 has wrapped up, and I think the current position of the control panel looks really nice with equal top/right padding. I don't think we need to top-align the A's with the panel (or vice-versa). I would differently if the Amplitude controls were in a panel, but the free-floating A's don't create the same edge as a panel would. 
![Fourier_ Making Waves screenshot](https://user-images.githubusercontent.com/8419308/104626497-3c5e0100-5653-11eb-9415-5b70fa6183af.png)

Since @pixelzoom and I agree on the panel alignment, and the current state of master looks good, I'll go ahead and close.
