### ISSUE TITLE
use NumberSpinner for setting number of harmonics

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#35]
12/17/2020 design meeting @arouinfar @kathy-phet @ariel-phet @pixelzoom 

Change harmonics control from NumberPicker to NumberSpinner, with 2 buttons on right side.

**Comment by pixelzoom** [comment]
@arouinfar ready for review in master.  Pointer areas have been expanded, but will be refined more later in the project, after polishing the entire control panel.

**Comment by arouinfar** [comment]
Looks great!
