### ISSUE TITLE
tie together the pieces of the 3 main areas

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#37]
Revisiting our decision in https://github.com/phetsims/fourier-making-waves/issues/9 to eliminate the "rectangles inside of rectangles" clutter...

In #34, @ariel-phet suggested that we somehow tie together the pieces of each of the 3 main areas (Amplitude sliders, Harmonics chart, Sum chart).   He feels that they are a little too "floaty".

Screenshot of 1.0.0-dev.9 shown below.

<img width="1024" alt="screenshot_807" src="https://user-images.githubusercontent.com/3046552/103694318-0a181980-4f58-11eb-8294-8bec392d17d7.png">

**Comment by pixelzoom** [comment]
I did a little playing around, and whatever I do here is going to be a decent chunk of work. Trying to keep these graphs lined up while they're inside a container is challenging (especially since PhET still lacks layout managers). That said...

It sounds to me like you want to go back to the accordion box interface, perhaps with a subdued stroke on the accordion boxes.  That's going to be a major change.  So before I do it - do you think that will provide what you're looking for? And do you think we can use accordion boxes for the Harmonics and Sum charts, but leave the Amplitude sliders alone.

Assigning to the team for input @arouinfar @ariel-phet @kathy-phet

**Comment by kathy-phet** [comment]
I'd like to see the extra vertical space stuff, before going back to an accordian box interface. I think that might help resolve Ariel's concerns without needing the background boxes.

**Comment by pixelzoom** [comment]
The extra vertical space suggesting have been addressed in #34.

**Comment by kathy-phet** [comment]
My 2 cents. I like it as it is now, and would avoid the extra boxes in favor of the extra space.

**Comment by pixelzoom** [comment]
As I mentioned in https://github.com/phetsims/fourier-making-waves/issues/34:
> ... I did a quick-and-dirty implementation that put subtle colored backgrounds behind the 3 sections. The background for the Sum area needs to be noticeably taller, with lots more space above the chart. It looked very lopsided to me, and we'd lose a lot of space to make it look balanced.

The additional space needed for the summation symbols is significant and noticeable, even after reducing font size.  So if we go back to a "put a rectangle around it approach" (which includes accordion box),  either spacing will look lopsided when the equations are hidden, or we'll need to steal a chunk of vertical space from something else to make it look balanced (which imo is not a good use of vertical space). 

So my preference is to find something that doesn't involve putting  each area inside of a rectangle, or leave it as is.

**Comment by ariel-phet** [comment]
I liked @pixelzoom suggestion during the meeting of just having a simple vertical leader line. Something like this was my thought, a subtle visual cue:

![fourier](https://user-images.githubusercontent.com/4051174/102811110-1e69ed00-4382-11eb-9e90-181e59a614cc.PNG)

**Comment by pixelzoom** [comment]
Thanks for the mockup @ariel-phet.  I'll give that a try, should be relatively easy.

**Comment by pixelzoom** [comment]
Leader lines have been added in master and [1.0.0-dev.10](https://phet-dev.colorado.edu/html/fourier-making-waves/1.0.0-dev.10/phet/fourier-making-waves_en_phet.html).  Color is currently `rgb(190, 217, 224)` and adjustable in colors.html.  Screenshot below.

To be honest...  I could live with this, but I don't love it.  

It comes with trade-offs.... The left side of the Sum chart was already crowded, and now it feels a bit more crowded.  The layout code is more complicated now - not as obvious, a little tricky to get all of the charts to align horizontally, more difficult to change and maintain.  And we'll presumably want to add these leader lines to the other 2 screens, so trickier layout code there too.

I'm also not convinced that the problem we're trying to solve actually exists.  The grouping of Harmonics and Sum components seems pretty clear to me without the leader lines.  And if there's any question, it should become clear when the expand/collapse buttons are used. My recommendation would be to ditch the leader lines, wait to see if interviews indicate a "parsing" problem, and (if so) revisit this issue.  But I don't feel too strongly, the work has been done, and (like I said) I could live with the leader lines.

Over to @arouinfar @ariel-phet @kathy-phet for feedback.

<img width="934" alt="screenshot_806" src="https://user-images.githubusercontent.com/3046552/103689885-22386a80-4f51-11eb-8a79-2e42abaa6b12.png">

**Comment by ariel-phet** [comment]
To me this layout looks more orangized/easier to parse. Fine with being out voted.

**Comment by arouinfar** [comment]
I think the leader line is vastly better than a fully-bounded AccordionBox, and generally looks pretty clean. I do share @pixelzoom's concern that it crowds the Sum chart a bit, though. 

>The layout code is more complicated - not as obvious, a little tricky to get all of the charts to align horizontally, more difficult to change and maintain. And we'll presumably want to add these leader lines to the other 2 screens, so trickier layout code there too.

For consistency, we should use the leader line for any ExpandCollapseButton that controls a chart. They'll definitely be on the Continuous screen, but the game is still somewhat an open question.

> My recommendation would be to ditch the leader lines, wait to see if interviews indicate a "parsing" problem, and (if so) revisit this issue. But I don't feel too strongly, and (like I said) I could live with the leader lines.

I don't have a strong opinion about the leader line, and could take it or leave it. If we decide to wait, we can leave this issue open and tagged for interviews. 

I'd also like to know @kathy-phet's thoughts before we make a final decision.

**Comment by kathy-phet** [comment]
Like Chris, I have a preference for without the leader line because it feels busier to me. I think with the spacing changes it works without the grouping. My leaning would be to go without for now, and see if their are issues in interviews.

**Comment by arouinfar** [comment]
Thanks for the feedback @kathy-phet. Let's wait and see what happens in interviews.

**Comment by pixelzoom** [comment]
@arouinfar could you please clarify? Does "Let's wait and see what happens in interviews" mean with or without the leader lines?

**Comment by arouinfar** [comment]
Let's remove the leader lines.

**Comment by pixelzoom** [comment]
Roger

**Comment by pixelzoom** [comment]
Leader lines have been removed. If we want to restore them in the future, see 82786ee.

Unassigning until we're ready for interviews.

**Comment by pixelzoom** [comment]
@arouinfar anything to add based on last week's interviews?

**Comment by arouinfar** [comment]
Students in interviews easily made connections between the three graphs, so we can leave the design as-is.
