### ISSUE TITLE
questions about Meaurement Tools

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#39]
Question about the Meaurement Tools in the Discrete screen ...

* Where should the tools be positoned initially?  Java initial positions are shown in screenshot below.  For domain=time, the Period tool is in the same initial position as the Wavelength tool.

* Should initial position be reset when Reset All is pressed? Java version does.

* How should dragging be constrained?  Java version allows tools to be dragged anywhere in the "play area", as long as some (tiny!) part of the tool remained visible.  This seems reasonable for HTML5 version, but I think more of the tool should be required to be inside window bounds.

@arouinfar please advise.

<img width="1016" alt="screenshot_810" src="https://user-images.githubusercontent.com/3046552/103839244-301ee600-504c-11eb-8d3c-42dbbfad1e12.png">

**Comment by pixelzoom** [comment]
Moving forward with this, doing what I think is correct...

> * Where should the tools be positoned initially? Java initial positions are shown in screenshot below. For domain=time, the Period tool is in the same initial position as the Wavelength tool.

Here are the initial tool positions:

Wavelength tool for _Function of: space (x)_ and _Function of: space (x) & time (t)_:

<img width="1105" alt="screenshot_819" src="https://user-images.githubusercontent.com/3046552/104393330-73240200-5501-11eb-847b-1e8b22537944.png">

Period tool for _Function of: time (t)_:

<img width="1103" alt="screenshot_818" src="https://user-images.githubusercontent.com/3046552/104393340-761ef280-5501-11eb-8c0e-fdfea9f92238.png">

Period tool for _Function of: space (x) & time (t)_:

<img width="1105" alt="screenshot_817" src="https://user-images.githubusercontent.com/3046552/104393343-77e8b600-5501-11eb-8a37-75afb5e14afc.png">

> * Should initial position be reset when Reset All is pressed? Java version does.

They are resettable.

> * How should dragging be constrained? Java version allows tools to be dragged anywhere in the "play area", as long as some (tiny!) part of the tool remained visible. This seems reasonable for HTML5 version, but I think more of the tool should be required to be inside window bounds.

Drag bounds for all tools are dynamically derived from the bounds of the browser window. If the browser window is resized such that a tool would be outside the drag bounds, any in-progress interaction is interrupted, and the tool is move inside the drag bounds.  That said...

The caliper-like tools are constrained differently in the x and y dimensions. In the x dimension, at least 50 pixels of a tool must be inside the browser window's bounds. In the y dimension, the entire tool must be inside the browser window's bounds. 

The clock-like (period) tool must be fully inside the browser window's bounds in both the x and y dimensions.

Over to @arouinfar to review in master.

**Comment by pixelzoom** [comment]
@arouinfar I made some changes to the tools (factored out duplicate code) and the initial position of the caliper-like tools is now off a little bit in master.  I'm trying to track this down, but wanted to let you know.  If you review this issue, please do so with the assumption that initial positions will be as shown in the above screenshots.

**Comment by pixelzoom** [comment]
@arouinfar Initial positions are fixed.  So you can review master or [1.0.0-dev.12](https://phet-dev.colorado.edu/html/fourier-making-waves/1.0.0-dev.12/phet/fourier-making-waves_en_phet.html).

**Comment by arouinfar** [comment]
@pixelzoom the initial positions of the Wavelength tool and Period clock look great. I think something's up with the initial position of the caliper-like Period tool, though. When turning it on for the first time, it occludes the Amplitude readouts. 
![image](https://user-images.githubusercontent.com/8419308/104546148-c624b480-55e8-11eb-94b7-5a1c3e201241.png)

Once after using the ResetAllButton, it respawned near the Harmonics plot, though offset to the left.
![image](https://user-images.githubusercontent.com/8419308/104546792-37189c00-55ea-11eb-87f7-8f71ec2fe856.png)



The drag bounds all look reasonable in dev.12. I would be fine with limiting everything to the browser window's bounds like the clock-like period tool, but I don't have a strong opinion. Do whatever you think is best @pixelzoom.

**Comment by pixelzoom** [comment]
@arouinfar I can't reproduce the case where the caliper-like Period tool occludes the Amplitude readouts. Can you please provide steps to reproduce? 

For the other case, where the caliper-like Period tool is shifted further left than it should be:
1. start sim
2. go to Discrete screen
3. select "Function of: time"
4. Check the "Period" checkbox

**Comment by pixelzoom** [comment]
@arouinfar said:
> ... I would be fine with limiting everything to the browser window's bounds like the clock-like period tool, but I don't have a strong opinion. Do whatever you think is best @pixelzoom.

All tools are now constrained to be fully inside the browser window's bounds. I think this will make more sense to the user, and make it less likely that a tool will get "lost".   Programmatically it's also more straightforward and will be easier to maintain.  So win win.

**Comment by arouinfar** [comment]
> @arouinfar I can't reproduce the case where the caliper-like Period tool occludes the Amplitude readouts. Can you please provide steps to reproduce?

Sure, it's the same steps you outlined for the offset:

> start sim
go to Discrete screen
select "Function of: time"
Check the "Period" checkbox

The caliper-like Period tool always shows up on top of the Amplitude controls for me when I follow this procedure. Here's my troubleshooting info:
>Name: ‪Fourier: Making Waves‬
URL: https://phet-dev.colorado.edu/html/fourier-making-waves/1.0.0-dev.12/phet/fourier-making-waves_en_phet.html
Version: 1.0.0-dev.12 2021-01-13 23:17:06 UTC
Features missing: applicationcache, applicationcache, touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
Language: en-US
Window: 2560x1329
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

**Comment by pixelzoom** [comment]
Wow, really weird.  With macOS 11.1 + Chrome 87, I was not able to reproduce what @arouinfar described with the Period tool (covering the amplitude displays).  After updating to Chrome 88, I can reproduce.

**Comment by pixelzoom** [comment]
More weirdness...  On Safari, I consistently see what @arouinfar described -- the initial position of the Period tool covers the amplitude displays:

![image](https://user-images.githubusercontent.com/8419308/104546148-c624b480-55e8-11eb-94b7-5a1c3e201241.png)

With Chrome 88, I saw that happen exactly once.  And every reload after that, the Period tool is nowhere near the amplitude displays, it's here:

![image](https://user-images.githubusercontent.com/8419308/104546792-37189c00-55ea-11eb-87f7-8f71ec2fe856.png)

**Comment by pixelzoom** [comment]
If I change the default domain  to "time", then the Wavelength tool is in the wrong initial position.  So I'm guessing that a tool is not being initialized properly when it doesn't correspond to the domain.

**Comment by pixelzoom** [comment]
In the above commit I had to change the drag bounds for the caliper-like tools.  When you zoom in on the graphs, these tools (specifically for n=1) will become wider than the bounds of the browser window. So it's impossible to constrain these tools to be fully visible. The new behavior is that the left tip of the tool has to be within the width (x dimension) of the browser window, minus a margin of 40 pixels.   

So for example, this is the furthest left that a caliper-like tool can be dragged:

<img width="1006" alt="screenshot_827" src="https://user-images.githubusercontent.com/3046552/105111256-be985c00-5a7d-11eb-930c-fa3c84c1e679.png">

And this is the furthest right:

<img width="1008" alt="screenshot_828" src="https://user-images.githubusercontent.com/3046552/105111350-f2738180-5a7d-11eb-8cdd-868d839fac69.png">

@arouinfar seem OK to you?

**Comment by pixelzoom** [comment]
It might even be better to limit the x postions of these tools to the left and right edges of the charts.  If you wanted to get them out of the way, you should uncheck the checkboxes, not move the tools drastically to the right.

**Comment by pixelzoom** [comment]
Hmmm... What I proposed in the previous comment is going to involve some major changes to my scenegraph structure.  So perhaps we should leave it the way it is.

**Comment by pixelzoom** [comment]
Initial position of Period tool is fixed in the above commit.

@arouinfar to summarize what's I need from you:

* Verify that initial postion of all tools is now correct.
* Verify that the drag constraint change described in https://github.com/phetsims/fourier-making-waves/issues/39#issuecomment-763245857 is OK.

**Comment by arouinfar** [comment]
> Verify that initial position of all tools is now correct.

Looks good!

>Verify that the drag constraint change described in #39 (comment) is OK.
> >In the above commit I had to change the drag bounds for the caliper-like tools. When you zoom in on the graphs, these tools (specifically for n=1) will become wider than the bounds of the browser window. So it's impossible to constrain these tools to be fully visible. The new behavior is that the left tip of the tool has to be within the width (x dimension) of the browser window, minus a margin of 40 pixels.

Oh, good catch with the zoom level. I think the behavior in master feels really nice.
