### ISSUE TITLE
future PhET-iO requirements

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#4]
Fourier 1.0 will not include a PhET-iO version. But how 1.0 is implemented will affect what's possible for future PhET-iO instrumentation.  The more we know about future needs, the fewer sim changes will be necessary, and the easier it will be to instrument.  This issue will track options and decisions.

For any new sim, it's difficult to make 1.0 implementation decisions without addressing these high-level questions:

(1) What are the sim-specific PhET-iO features that will be desired?
(2) How should the Studio tree be structured?
(3) What elements should be static vs dynamic? 

It's also difficult to verify that the 1.0 implementation will satisfy future needs without doing some level of instrumentation to test and verify. So an additional question is:

(4) How much PhET-iO instrumentation can (should!) be done as part of 1.0?

Labeling for discussion at design meeting. Priority is high, since this affects implementation decisions that are being made now.

**Comment by ariel-phet** [comment]
We will plan to have an initial discussion this week

**Comment by pixelzoom** [comment]
11/12/2020 design meeting with @arouinfar @kathy-phet @samreid @pixelzoom 

> (1) What are the sim-specific PhET-iO features that will be desired?

@arouinfar and @kathy-phet will brainstorm sim-specific PhET-iO features, so assigning them this issue.  It would probably be good to put those requirements in a PhET-iO Design Google Doc, as we did for Natural Selection and pH Scale.

> (2) How should the Studio tree be structured?

We discussed the model structure in https://github.com/phetsims/fourier-making-waves/issues/6, and decided to go with the "static elements" approach. If @arouinfar and @kathy-phet think of any other sim-specific requirements for Studio tree structure, please not them as part of the brainstorming task.

> (3) How much PhET-iO instrumentation should be done as part of 1.0?
 I should instrument as much as I feel is necessary.

Assigning to @arouinfar and @kathy-phet to brainstorm sim-specific requirements.

**Comment by pixelzoom** [comment]
I said:
> It would probably be good to put those requirements in a PhET-iO Design Google Doc, as we did for Natural Selection and pH Scale.

@arouinfar and @kathy-phet met and added notes to the main design doc, see "November 13, 2020" notes.  I will review and discuss with @arouinfar.

I think that it would be good to move those notes to a new "Fourier PhET-iO Design" document, since that's what we've been doing for other sims. And we decided to do that for other sims so that the main design doc doesn't get bloated.

**Comment by pixelzoom** [comment]
@arouinfar When are you available to discuss the "November 13, 2020"  notes in the design doc? And should we move these to a new "Fourier PhET-iO Design" document?

**Comment by pixelzoom** [comment]
We discussed "November 13, 2020" notes during 12/3/2020 design meeting.  See meeting notes in the design doc for details.

**Comment by pixelzoom** [comment]
@arouinfar I feel like I have enough information to inform 1.0 (`brand=phet`) implementation.  Is there any addition "up front" design that you and @kathy-phet are planning to do?  Or can this issue be unassigned and deferred for a future (PhET-iO) release?

**Comment by pixelzoom** [comment]
I guess the one thing that could be done proactively is what I suggested in https://github.com/phetsims/fourier-making-waves/issues/4#issuecomment-730612062:

> I think that it would be good to move those notes to a new "Fourier PhET-iO Design" document, since that's what we've been doing for other sims. And we decided to do that for other sims so that the main design doc doesn't get bloated.

Or you could wait until later to start the "Fourier PhET-iO Design" document -- up to you.

**Comment by arouinfar** [comment]
@pixelzoom in terms of the Discrete screen, I don't think there is anything else left to discuss for 1.0. We should identify PhET-iO requirements as we move forward with the Game and Continuous screens, though. I'll leave this self-assigned until those discussions happen.

I created [Fourier: Making Waves - PhET-iO](https://docs.google.com/document/d/1BaPMzLPeFiQoppEkvaSLlyqKpolXv6fzZ6nEr0EO7bA/edit) in the sim design folder. It is only accessible by the design and PhET-iO teams. The contents are pretty sparse, but moving forward we can use it to keep track of PhET-iO design.

**Comment by arouinfar** [comment]
Since the Wave Game is coming along, I revisited the PhET-iO design to see if there is anything sim-specific to be mindful of. Aside from hiding/disabling UI components, I don't see any requirements that are specific to this sim.

As far as I know, there isn't any general PhET-iO infrastructure in vegas, as we've never instrumented a game (build-an-atom excludes the game).  Thinking generally about any game, a client might want to:
* Hide specific levels
* Change the condition for triggering the RewardNode (e.g. lower the threshold to 5 stars)
* Specify their own challenge, or at least have some way of ensuring all students get the same sequence of challenges

These are all big-picture issues for vegas/PhET-iO and I don't think it's something that can or should be considered in the scope of FMW.

**Comment by pixelzoom** [comment]
@arouinfar Actually, all of those bullets that you listed would need to be considered in the scope of the sim.  vegas is only a collection of UI components that can be used to assemble a game. It currently provides no "framework" for games.  Any similarity in behavior/flow between PhET sims is not provided by vegas, it's due to sims implementing similar behavior/flow.

**Comment by arouinfar** [comment]
Good to know @pixelzoom. Do you think it would be helpful to discuss more at a design meeting? We're not including the phet-io-brand in the 1.0 release, but I don't know if there is anything that should be considered now.

**Comment by pixelzoom** [comment]
Imo, instrumenting a game is long overdue. But it's not my call when this should be discussed or investigated.

On 5/18/2017 (4 years ago), @samreid wrote in  https://github.com/phetsims/phet-io/issues/1137#issuecomment-302597073
> @kathy-phet said it will be important to instrument a game in the near future.

And it looks like an attempt to instrument the game screen in Build an Atom didn't go smoothly. In https://github.com/phetsims/build-an-atom/issues/156#issuecomment-586443167, @zepumph wrote:
> The game screen does not (still) support state, and is not set up to be maintained for phet-io yet. As @samreid and I work on updating phet-io tests, we decided to remove that screen from the PhET-iO sim above.

It's highly likely that instrumenting a game may result in the discovery of new issues and requirements, which may result in PhET-iO changes.

**Comment by pixelzoom** [comment]
Everything in this issue is either captured in https://github.com/phetsims/fourier-making-waves/issues/123, or has been broken out into a separate GitHub issue.  So I'll close this issue.
