### ISSUE TITLE
revisit design of measurement tools

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#41]
Revisiting the design of the measurement tools that are used to measure width....

They currently look like this:

<img width="821" alt="screenshot_813" src="https://user-images.githubusercontent.com/3046552/104361855-43a8d180-54d0-11eb-9922-fb7217edf5fa.png">

These are essentially calipers. And it's a little odd to have the sloped part of the caliper on the inside edge, because you're measuring with the inside edge.  For example, here's a typical caliper - note that the inside edge is perpendicular to the tool, not sloped:

<img width="573" alt="screenshot_814" src="https://user-images.githubusercontent.com/3046552/104362111-9d110080-54d0-11eb-82d2-83da23213a0a.png">

So would it be better to have the measurement tools look something like this?

<img width="827" alt="screenshot_812" src="https://user-images.githubusercontent.com/3046552/104362159-aa2def80-54d0-11eb-97f0-9a58839e4882.png">

**Comment by pixelzoom** [comment]
If we want to change to the new look shown above, here's the patch to do so.

<details>
<summary>Patch</summary>

```diff
Index: js/discrete/view/WidthToolNode.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/discrete/view/WidthToolNode.js b/js/discrete/view/WidthToolNode.js
--- a/js/discrete/view/WidthToolNode.js	(revision 598775eafc1d0c4ea8cccb51b0740f2419cbf537)
+++ b/js/discrete/view/WidthToolNode.js	(date 1610478943668)
@@ -153,12 +153,14 @@
       const caliperThickness = 5;
       const caliperLength = 20;
       const toolShape = new Shape()
-        .moveTo( 0, 0 )
-        .lineTo( viewValue, 0 )
+        .moveTo( -caliperThickness, 0 )
+        .lineTo( viewValue + caliperThickness, 0 )
+        .lineTo( viewValue + caliperThickness, barThickness )
         .lineTo( viewValue, caliperLength )
-        .lineTo( viewValue - caliperThickness, barThickness )
-        .lineTo( caliperThickness, barThickness )
+        .lineTo( viewValue, barThickness )
+        .lineTo( 0, barThickness )
         .lineTo( 0, caliperLength )
+        .lineTo( -caliperThickness, barThickness )
         .close();
       const toolNode = new Path( toolShape, {
         fill: this.harmonic.colorProperty,
```

</details>

**Comment by pixelzoom** [comment]
The mor caliper-like design seems to make things clearer as the length of the tool gets shorter.  For example, compare:

<img width="813" alt="screenshot_815" src="https://user-images.githubusercontent.com/3046552/104363138-ff1e3580-54d1-11eb-805b-50b6b2065a6a.png">

<img width="822" alt="screenshot_816" src="https://user-images.githubusercontent.com/3046552/104363144-00e7f900-54d2-11eb-884c-6f8da7070e74.png">

**Comment by pixelzoom** [comment]
Since I had this patch in my working copy, and I think there's a high probability that we'll want to change to this new look, I went ahead and make the change.  It's easy to revert if you hate it.   Over to @arouinfar to review in master.

**Comment by arouinfar** [comment]
@pixelzoom the caliper-like appearance looks really nice. Thanks for the suggestion!

Since the updated appearance is in master, I'll go ahead and close.
