### ISSUE TITLE
screen icons

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#44]
Screen icons for this sim need to be designed and implemented.

**Comment by pixelzoom** [comment]
In a recent design meeting, @kathy-phet said that it would be nice to have the screen icons done for the site visit related to a grant on June 22 & 24, 2021.    I'll need a specification by 6/15 to make that happen.

**Comment by pixelzoom** [comment]
Raising priority to high, since I need this in 8 days at the latest.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/fourier-making-waves/issues/44#issuecomment-852337293, @kathy-phet noted that the site visit has been moved to August.  So removing high-priority label.

**Comment by pixelzoom** [comment]
Here are my (rough) suggestions for screen icons.

Discrete:

<img width="206" alt="screenshot_1011" src="https://user-images.githubusercontent.com/3046552/121072742-d18e9d00-c78e-11eb-83a4-6cdf697ee01b.png">

Wave Game:

<img width="150" alt="screenshot_1012" src="https://user-images.githubusercontent.com/3046552/121073054-4cf04e80-c78f-11eb-85d6-e87acfdb23e2.png">


Continuous:

<img width="169" alt="screenshot_1013" src="https://user-images.githubusercontent.com/3046552/121072948-2205fa80-c78f-11eb-8a99-416978a47399.png">

**Comment by pixelzoom** [comment]
Because they were quick/easy to do programmatically, I pushed icons for the Discrete and Wave Game screens, test-drive in master.  Screenshot:

<img width="1193" alt="screenshot_1015" src="https://user-images.githubusercontent.com/3046552/121076078-364bf680-c793-11eb-86cf-291507fa2b6d.png">

**Comment by pixelzoom** [comment]
I also added an icon for the Continous screen, see screenshot below.  I created this icon by hiding the chart rectangle, ticks, etc. in the Discrete screen, increasing the lineWidth for the Sum chart, setting Waveform="wave packet", then taking a screenshot. This required adding a file to fourier-making-waves/images/, so I'll need to remember to delete it if it's not used.

<img width="1190" alt="screenshot_1017" src="https://user-images.githubusercontent.com/3046552/121077588-0867b180-c795-11eb-96a4-56654f7a56bd.png">

**Comment by arouinfar** [comment]
@pixelzoom the screen icons are awesome!

For Wave Game, I might instead want to go with your other suggestion in https://github.com/phetsims/fourier-making-waves/issues/44#issuecomment-856178630 since it has a bit more context.

Perhaps a magenta wave on iconic axes like the Continuous icon with a +1 star on top. Here are some ideas for the magenta wave:

A3 = 1, A4 = -1
![image](https://user-images.githubusercontent.com/8419308/121583701-d309d080-c9ed-11eb-8e6a-7de8e27e4037.png)

A1 = 1.5, A6 = 0.5
![image](https://user-images.githubusercontent.com/8419308/121583832-00ef1500-c9ee-11eb-9501-15739f536b02.png)

**Comment by pixelzoom** [comment]
6/10/21 design meeting: @arouinfar @kathy-phet @pixelzoom @KatieWoe 

Discrete and Continuous icons are good as is.

Wave Game icon: use +1 star, with a pink waveform behind it from Level 2.

**Comment by pixelzoom** [comment]
> Wave Game icon: use +1 star, with a pink waveform behind it from Level 2.

As a first step, I replace the PhET girl with "+1 star", see screenshot below, test-drive in master. This only took ~1 minute, and looks very clean to me.  Adding a pink waveform behind this is going to take ~30 minutes, and I'm afraid that it will make the icon kind of noisy, especially in the navbar.   @arouinfar what do you think? Do we need the pink waveform?

<img width="774" alt="screenshot_1024" src="https://user-images.githubusercontent.com/3046552/121612070-eb421580-ca16-11eb-9916-58bc2de9edb5.png">

**Comment by arouinfar** [comment]
@pixelzoom I agree, I think the pink waveform will muddy the icon. The +1 star is very clear and will read well in the navbar. Let's leave it as-is, closing.
