### ISSUE TITLE
requirements for harmonic colors

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#5]
Related to https://github.com/phetsims/fourier-making-waves/issues/4.

In the Java version, menu item `Options > Harmonic Colors...` opens this dialog to change harmonic colors:

<img width="229" alt="screenshot_656" src="https://user-images.githubusercontent.com/3046552/98586930-ad192380-2286-11eb-806c-b3be0ba982d5.png">

* Is a UI like this desired in the HTML5 version? Can it be added to the standard Options dialog?
* Does PhET have a color chooser?  
* Should colors be global to all screens? 
* Should it be possible to globally change colors via PhET-iO?
* Is it feasible to use ColorProfile, which doesn't support "array of color Property", and doesn't instrument its color Properties (see https://github.com/phetsims/scenery-phet/issues/515)?

**Comment by pixelzoom** [comment]
Assigning to @arouinfar @ariel-phet and @kathy-phet so they can think about this before design meeting, and provide input before the meeting if they feel like it.

**Comment by ariel-phet** [comment]
IMO this is NOT desirable for the HTML5 version. It seems like added complexity that is unnecessary and does not fit a pedagogical goal. I think we should be choosing a set of colors that works well for contrast and color blindness and stick with those.

**Comment by pixelzoom** [comment]
@ariel-phet please clarify. Is that a "no" to all of the above questions, including:

> Should it be possible to globally change colors via PhET-iO?

**Comment by pixelzoom** [comment]
11/12/2020 design meeting with @arouinfar @kathy-phet @samreid @pixelzoom 

* We will not have a UI for changing colors.

* We will not allow colors to be changed via PhET-iO.

* We will use a ColorProfile in this sim, to facilitate tweaking colors via fourier-making-waves-colors.hmtl. See https://github.com/phetsims/fourier-making-waves/issues/10.

* We noted that ColorProfile should be used in all new sims, to support future PhET-iO and a11y needs. @kathy-phet asked me to create an issue for developer meeting, see https://github.com/phetsims/scenery-phet/issues/642.
