### ISSUE TITLE
Requirements for Wave Game rewards

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#50]
@arouinfar How fancy do you want to get with rewards for the _Wave Game_ screen? The mockup in the design doc shows smiley faces and stars, so that's what I've currently implemented, for all levels (with 100 Nodes in the reward).  If that is sufficient, great, and you can close this issue. If you want level-specific rewards, or something other than faces and stars, let's discuss here.

**Comment by pixelzoom** [comment]
Possibilities, these can also be combined:

* NO EFFORT: Use 100 yellow faces and stars for all levels.
* MODERATE EFFORT: Use different Nodes for different levels
* EASY: Use different quantities of the same Nodes for different levels (more Nodes for higher levels)
* EASY: Use different colors of the same nodes for different levels
* EASY: Use a random combination of colors for the most difficult level

**Comment by arouinfar** [comment]
I'm happy to go with the NO EFFORT option here. The smileys and stars are fun, and I don't see a reason to mix up the proportion or number based on the level. There aren't sim-specific Nodes that would be a particularly whimsical option here, either.
