### ISSUE TITLE
Sound for sliders

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#56]
This sim has the following sliders:

* Discrete: custom amplitude sliders
* Discrete: standard volume slider for Fourier series sound
* Wave Pack: 4 standard sliders in the control panel

From #54
> Amplitude sliders would probably not have a "harmonic" sound, probably just click, click, click (like Waves Intro).

**Comment by pixelzoom** [comment]
Waves Intro adds sounds in WaveInterferenceSlider.js:

```js
import generalBoundaryBoopSoundPlayer from '../../../../tambo/js/shared-sound-players/generalBoundaryBoopSoundPlayer.js';
import generalSoftClickSoundPlayer from '../../../../tambo/js/shared-sound-players/generalSoftClickSoundPlayer.js';
``

Playing these sounds must be handled in the Slider's `options.drag` function.

**Comment by pixelzoom** [comment]
Below is the code that plays slider sounds in WaveInterferenceSlider.js.   @jbphet @samreid is this the recommended pattern?  Is this really the support that's available for Slider sound?  And the client is responsible for checking elapsed time between sounds?!?

```js
      drag: event => {

        const value = property.value;

        if ( event.isFromPDOM() ) {

          if ( Math.abs( value - property.range.max ) <= TOLERANCE ||
               Math.abs( value - property.range.min ) <= TOLERANCE ) {
            generalBoundaryBoopSoundPlayer.play();
          }
          else {
            generalSoftClickSoundPlayer.play();
          }
        }
        else {

          // handle the sound as desired for mouse/touch style input
          for ( let i = 0; i < ticks.length; i++ ) {
            const tick = ticks[ i ];
            if ( lastValue !== value && ( value === property.range.min || value === property.range.max ) ) {
              generalBoundaryBoopSoundPlayer.play();
              break;
            }
            else if ( lastValue < tick.value && value >= tick.value || lastValue > tick.value && value <= tick.value ) {
              if ( phet.joist.elapsedTime - timeOfLastClick >= MIN_INTER_CLICK_TIME ) {
                generalSoftClickSoundPlayer.play();
                timeOfLastClick = phet.joist.elapsedTime;
              }
              break;
            }
          }
        }
```

**Comment by samreid** [comment]
That pattern was recommended when we worked on it in mid-2020.  @jbphet is there better common code support for this now? Should there be?

**Comment by pixelzoom** [comment]
From 4/22/21 design meeting

There is currently no sound API for Slider, because most sounds were pedagogical.  

Now that some sims have been instrumented, there are probably some common patterns for sound in Sliders.  @jbphet will identify those in https://github.com/phetsims/sun/issues/697 and develop a sound API for Slider, including some type of default non-pedagogical sound, like WaveInterfaceSlider.

In the meantime, I've added rudimentary sound to the amplitude sliders in Fourier.  I did that totally in `AudibleSlider`, a `Slider` subclass.   It's a bit like the approach used in WaveInterfaceSlider, and I'm hoping that AudibleSlider can be entirely deleted once https://github.com/phetsims/sun/issues/697 is completed. 

Work on this is on hold until the Slider sound API is ready.

**Comment by pixelzoom** [comment]
Common-code work for Slider sound is being done by @jbphet in phetsims/sun#697.  

Fourier currently has a sim-specific implementation of Slider sound, with behavior identical to Waves Intro.  As the thumb is moved (with mouse, touch, or keyboard), there are discrete "tick" sounds. At the min/max there is a specific sound. And there is no sound when the value is changed by clicking on the track (a deficiency in the Waves Intro implementation, not easily correct in Fourier).  You can test-drive this is master or any recent dev version.

To help prioritize our work, it would be helpful to know whether the sim-specific implementation is sufficient for Fourer 1.0, or whether the common-code work needs to be completed (and is therefore blocking).

@arouinfar @kathy-phet your thoughts?

**Comment by pixelzoom** [comment]
Raising priority to get feedback from @arouinfar and @kathy-phet.  Slider sound API is a large task, so if this is needed, that work needs to start very soon.

**Comment by arouinfar** [comment]
A sim-specific approach seems reasonable to me. Perhaps we can defer the common code work until we get to a 3rd sim that wants to use the slider clicks. I know it's unconventional to wait so long to generalize, but given current priorities, it seems okay. I can't make that call, however, so leaving it up to @kathy-phet.

**Comment by kathy-phet** [comment]
Sim-specific is OK, so this shouldn't be blocking for this sim publication. But I will add as a line item in PhET overview, to keep it on the radar for a future quarterly goal.

**Comment by pixelzoom** [comment]
To clarify…. There is a sim-specific sound implementation for the Amplitude sliders. There is no sound for any of the other sliders, and I'm not planning to do a sim-specific sound implementation for those other sliders.  Which option do you want to pursue? 

(1) Sim-specific sound for Amplitude sliders, no sound for other sliders.
(2) Sim-specific sound for all sliders.
(3) Slider sound API in common code, https://github.com/phetsims/sun/issues/697.

**Comment by arouinfar** [comment]
Discussed in the 7/15/21 design meeting with @kathy-phet @pixelzoom 

(3) is the preferred option, but time may not permit. 
(1) is our fallback option.

**Comment by pixelzoom** [comment]
More notes from 7/15/21:

@kathy-phet will check in with @jbphet to see whether phetsims/sun#697 and option (3) is doable in the next month.  Feature-complete milestone is 8/24/21, with the goal of starting QA testing shortly after.

**Comment by pixelzoom** [comment]
@kathy-phet gave an update at Q3 planning meeting today.   phetsims/sun#697 is probably Q4 work, after @jbphet has published Greenhouse.  So we're going with this option for Fourier 1.0:

> (1) Sim-specific sound for Amplitude sliders, no sound for other sliders.

**Comment by pixelzoom** [comment]
@jbphet recently added sound support for Slider.  But in https://github.com/phetsims/fourier-making-waves/commit/fa3395888bec5872b649b8bcdac0f157907bb33d, he disabled that support in AmplitudeSlider.js:

```js
soundGenerator: ValueChangeSoundGenerator.NO_SOUND,
```

What really needs to be done is to delete the ad hoc sound from AmplitudeSlider.js (SoundDragHandler) and enable the Slider sound.

**Comment by pixelzoom** [comment]
In the above commit, I replaced ad hoc sound (SoundDragHandler) with Slider sound support. A sound in now generated on each value change, in 0.05 interval.  This results a *LOT* of sound when dragging the slider, so we'll want to reconsider -- what (in general) should we do when there are a lot of value changes?  Is it OK to have no sound for some values? (I guess this would have to be the case for a contiuous slider.)

**Comment by pixelzoom** [comment]
Now that Sliders have sound by default, all sliders in this sim will need to be reviewed.  

In particular, I think that it makes sense  to turn sound off for slider that controls the output level of the Fourier Series (see screenshot below).  Since this slider is itself controlling sound, it's distracting/confusing to have it make sound.  @arouinfar do you agree?

<img width="251" alt="screenshot_1590" src="https://user-images.githubusercontent.com/3046552/157106277-c08ecdf0-5baa-48f5-8a10-78bb9da3c103.png">

**Comment by pixelzoom** [comment]
@arouinfar agrees that the slider that controls the output level of the Fourier Series should not have sound enabled.

**Comment by pixelzoom** [comment]
Labeling as blocks-sim-publication because all sliders need to be reviewed before publishing from master again.
 
Self unassigning until we work on this sim again.

**Comment by pixelzoom** [comment]
Ready for testing in https://github.com/phetsims/qa/issues/1178. You may close this issue if it looks OK.

This issue is relevant to the 4 horizontal sliders that appear in the _Wave Packet_ screen:

<img width="259" alt="screenshot_3621" src="https://github.com/user-attachments/assets/5ba563ae-128d-448b-b332-23c670fc1b6b">

This issue is not relevant to the sound slider that appears in the _Discrete_ screen. That slider has no sound by design, because (when the checkbox next to it is checked) it controls the volume of a sound.

<img width="276" alt="screenshot_3622" src="https://github.com/user-attachments/assets/058a898d-8ccc-4da0-822d-8f1df7ebfbb9">

**Comment by Nancy-Salpepi** [comment]
Sliders sound good to me. 
Closing!

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.

**Comment by pixelzoom** [comment]
Reopened because of https://github.com/phetsims/perennial/issues/468.
