### ISSUE TITLE
LevelSelectionButton icons

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#57]
Here's a screenshot of the current LevelSelectionButtons in the _Wave Game_ screen.  Are these sufficient?  Will the user know what the number means?  Should we show something instead of (or in addition to) the number, like 3 sine waves (or 3 sliders) for the level that involves 3 harmonics? 

<img width="692" alt="screenshot_960" src="https://user-images.githubusercontent.com/3046552/116164787-a573fc80-a6b7-11eb-86c5-769ab5eb0a1e.png">

**Comment by arouinfar** [comment]
Ideas discussed in the 5/20/21 design meeting, with N representing the level number:

1. N amplitude sliders
2. Iconized Harmonics graph displaying N non-zero harmonics
3. Iconized Sum graph, where the sum is composed of N non-zero harmonics

I'll mock up some options.

**Comment by pixelzoom** [comment]
@arouinfar this is ready for review.   Screenshot below.  The goal was to keep the text size the same, keep the x-axis in the same location, and (necessarily) scale down the sliders to fit the width.

Some deviations from the design requirments, and notes on the implementation:

* Contrary to our Slack discussion, I did include the level number in the icon.  An amplitude slider must have a symmetric range [-N,N], and its bounds extend for the full range, regardless of where the "filled in" part of the slider's track extends.  It made sense to stick to positive amplitude values for these icons, and there was consequently a lot of space below the x axis.  This was a nice place to put the level number, and it makes the icon look balanced.  I also think that since we're referring to level numbers in the Info dialog and status bar descriptions, it's clearer to have the buttons labeled - and that will facilitate lesson plans and classroom instructions like "go to Level 3".

* Having the level numbers was also a nice place to denote that Level 5 is "5 or more" harmonics.  If I put "+" or "..." to the right of the sliders, they would be scaled down even more than they currently are.  Labeling with "5+" solves that problem.

* The button color specified in the design doc did not work with the amplitude sliders. I switched to pink `rgb( 255, 214, 228 )` as a tie-in with "Match the pink waveform".  The color for the status bar also looked wrong, so I also changed the status bar color to the same pink.  Feel free to choose a different color via fourier-making-waves-colors.html.  I think it would be nice if we could retain the "pink" connection.

* If you'd prefer different amplitudes for these icons, let me know. The range is `[-1,1]` and the current values are `[ 1, 0.5, 0.75, 1, 0.85 ]`.

* Colors for the ampliitude sliders are identical to the colors for the harmonics that are used in both the Discrete and Wave Game screens.  Colors for the first 5 harmonics are used, in order.  If you want to use different colors for some reason, it will be considerable more work. And note that this icon code is currently share with the Discrete screen icon.

<img width="662" alt="screenshot_1026" src="https://user-images.githubusercontent.com/3046552/121954542-1d57be00-cd1c-11eb-9084-4f50af5a31b1.png">

**Comment by arouinfar** [comment]
These came out wonderfully @pixelzoom! 

> Contrary to our Slack discussion, I did include the level number in the icon

Great call. I think the numbers make the icons look more balanced and easier to interpret.

> The button color specified in the design doc did not work with the amplitude sliders. I switched to pink 

Looks great!

I'm happy with the amplitudes/bar colors, so I'll go ahead and close.
