### ISSUE TITLE
Revisit buttons for Wave Game 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#60]
I wonder if the Wave Game should have a button that is the equivalent of "I give up, show me the answer".   Pressing this button would set the sliders to the correct amplitudes.  The student could still play around with the challenge, but no points would be rewarded.

Especially for some of the more complex challenges, it seems like this might be better than just having to move on to another challenge without being able to see what the answer was. If you can show the answer, you can then play around with the sliders, and start to see how each harmonic contributes to the shape of the sum waveform - and potentially learn something that helps you solve subsequent challenges.

There's also a precedent for "Show Anwser" in other PhET games: Balancing Chemical  Equations, RPAL,  Graphing Lines, Graphing Slope-Intercept, ...

**Comment by pixelzoom** [comment]
This expanded to more than just a "Show Answer" button.  Here's what I recommend:

* Add a "Show Answer" button
* Combine "Next" and Refresh buttons into "New Game" button
* Add a Reset button for resetting amplitudes to zero

Screenshot below shows what this looks like in master.  For discussion at today's design meeting.

![screenshot_229](https://user-images.githubusercontent.com/3046552/119042527-31a2d800-b975-11eb-86c7-3ff01d1a7628.png)

**Comment by pixelzoom** [comment]
5/20/21 design meeting: @arouinfar @kathy-phet @pixelzoom 

* Disable "Show Answer" button until you've grabbed and move a slider N times.
* "New Game" button is always available.
*  Try eraser button instead of ResetButton, use on Discrete screen too.

**Comment by pixelzoom** [comment]
We had some discussion about whether "New Game" was the right label for the button.  How about "New Waveform"?  The instructions are to "match the pink waveform".   @arouinfar @kathy-phet ?

**Comment by pixelzoom** [comment]
@arouinfar @kathy-phet I replaced ResetButton with EraserButton, see screenshot below, test-drive in master.  Do you like this better?

![screenshot_230](https://user-images.githubusercontent.com/3046552/119055718-c19d4d80-b986-11eb-9dcb-15abbc227b9b.png)

**Comment by kathy-phet** [comment]
I have a preference for the eraser, but happy to be out voted too.

**Comment by arouinfar** [comment]
Thanks, @pixelzoom. I also prefer the eraser button. Yesterday we mentioned the possibility of using a gray erase button, but I actually prefer yellow. Gray would likely be overlooked, especially next to all of the white NumberDisplays. While it's not a primary control, it is very handy, so I definitely want users to find it.

As for the button label, I like "New Waveform". It uses the same language as the level description, and "New Game" could imply that you'd be resetting/restarting the level somehow.

**Comment by kathy-phet** [comment]
I also like "New Waveform"!

**Comment by pixelzoom** [comment]
- [ ] Rename 'New Game' to 'New Waveform'

**Comment by pixelzoom** [comment]
All of the change requests have been implemented.  Here's a summary:

* use EraserButton instead of RestButton
* add EraserButton to Discrete screen
* rename 'New Game' to 'New Waveform' button
* start each challenge with 'Show Answer' button disabled, enable after the user has interacted with the Amplitudes chart N times.  And interaction is a press on a Slider ro NumberDisplay.   N is currently 3.

Over to @arouinfar to review.    I'm also wondering if N=3 is appropriate, or whether it should be a different value, or whether it should be a function of the number of amplitude controls that are initially displayed for the challenge.

**Comment by pixelzoom** [comment]
Folding review for this issue into https://github.com/phetsims/fourier-making-waves/issues/69. Closing.
