### ISSUE TITLE
Discrete screen review

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#68]
The Discrete screen is feature-complete.  Please review at your earliest convenience, and specify any change requests.

**Comment by pixelzoom** [comment]
Please include keyboard navigation in your review.  Everything requested in https://github.com/phetsims/fourier-making-waves/issues/53 for this screen has been implemented.

**Comment by arouinfar** [comment]
@pixelzoom the Discrete screen is looking great. I noticed you moved the sound controls up into the Fourier Series section, and I think that was a good call.

One odd thing I noticed was that in my local copy (pulled all late evening 6/15) was that the focus on the round buttons on the Discrete screen was askew, but looked fine on the other two screens. For example:
<img width="57" alt="Screen Shot 2021-06-16 at 8 30 34 AM" src="https://user-images.githubusercontent.com/8419308/122334673-5304ce80-cef7-11eb-9e51-3a2cefd94f33.png">
<img width="100" alt="Screen Shot 2021-06-16 at 8 33 38 AM" src="https://user-images.githubusercontent.com/8419308/122334703-5d26cd00-cef7-11eb-9d1a-9b332894b401.png">

**Comment by pixelzoom** [comment]
>  ... One odd thing I noticed was that in my local copy (pulled all late evening 6/15) was that the focus on the round buttons on the Discrete screen was askew, but looked fine on the other two screens. ...

Tracking in https://github.com/phetsims/fourier-making-waves/issues/89. I cannot reproduce this.

Leaving this issue open and assigned to @kathy-phet for review.

**Comment by arouinfar** [comment]
@kathy-phet and I reviewed the Discrete screen in the 6/24/2021 design meeting. @kathy-phet suggested some pixel polishes, which I've documented in #95 linked above. 

Since everything's being tracked in separate issues, I'll close this one.
