### ISSUE TITLE
Wave Game screen review

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#69]
The Wave Game screen is feature-complete.  Please review at your earliest convenience, and specify any change requests. 

Requirements appear in the design doc, https://github.com/phetsims/fourier-making-waves/issues/50, and https://github.com/phetsims/fourier-making-waves/issues/60.

**Comment by pixelzoom** [comment]
Please include keyboard navigation in your review.  Everything requested in https://github.com/phetsims/fourier-making-waves/issues/53 for this screen has been implemented.

**Comment by arouinfar** [comment]
In general, the game is looking really nice. I don't have any visual design tweaks to suggest. The focus order is also good. I did notice a few oddities (bugs?) related to the Show Answer button, which I've tagged above.

In https://github.com/phetsims/fourier-making-waves/issues/60#issuecomment-847307404 @pixelzoom said:
> I'm also wondering if N=3 is appropriate, or whether it should be a different value, or whether it should be a function of the number of amplitude controls that are initially displayed for the challenge.

I had similar thoughts. N=3 seems fine for the first level, but it's inadequate for later levels with more non-zero harmonics. Perhaps we should instead set it to the number of non-zero harmonics + 1. What do you think @pixelzoom?

**Comment by pixelzoom** [comment]
@arouinfar said:
> ... N=3 seems fine for the first level, but it's inadequate for later levels with more non-zero harmonics. Perhaps we should instead set it to the number of non-zero harmonics + 1.  ...

Moving this to https://github.com/phetsims/fourier-making-waves/issues/90.

**Comment by pixelzoom** [comment]
Some additional requirements (and major changes) are noted in https://github.com/phetsims/fourier-making-waves/issues/91.

**Comment by arouinfar** [comment]
@kathy-phet and I reviewed the Wave Game in the 6/24/21 design meeting, and our only change request for this screen is #94 linked above.

Since all feedback is being tracked in other issues, I'm going to go ahead and close this one.
