### ISSUE TITLE
Requests for site visit?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#70]
There is a site visit for the grant on June 22 and 24.   @arouinfar and I were talking, and realized that we're each out a significant part of June, and our schedules do not overlap.   So we'll probably need to be ready for that visit by June 13 (in 1 week).  @kathy-phet If there's anything that you'd like for the site visit, please let us know asap.

**Comment by kathy-phet** [comment]
OK. Let me check on what is needed.

**Comment by kathy-phet** [comment]
Screen icons would be nice to have.

**Comment by kathy-phet** [comment]
I heard back, and the site visit was postponed until August so no immediate needs for this and continue working towards feature complete version.

**Comment by pixelzoom** [comment]
Do you have dates for August?

**Comment by kathy-phet** [comment]
Heard back. It's August 24.

**Comment by pixelzoom** [comment]
I'm going to close this issue.  I'll open a new issue (if needed) when we get closer to the new August date.
