### ISSUE TITLE
Is "Continuous" a good screen name?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#71]
For the HTML5 version, the 3rd screen name was shortened from "Discrete to Continuous" to "Continous".   While reading the [Java version design document](https://phet.unfuddle.com/a#/projects/9404/repositories/23262/file?path=%2Ftrunk%2Fsimulations-java%2Fsimulations%2Ffourier%2Fdoc%2FFourier_Design_Outline.pdf&commit=75224), I began to wonder if something has been lost with this name change.   The learning goals on page 20 are:

> * To develop an intuition for how decreasing the spacing between fourier components increases the spacing between wave packets, so that if you replace the sum with an integral, you have only one wave packet, and you can describe a non-periodic function with a continuous distribution of sines and cosines.
> * To understand that decreasing the width of a wave packet in real space increases the width in Fourier space and vice versa and to develop a qualitative intuition for the uncertainty principle Δx Δk≈1.

These goals both deal with mappings between Fourier (discrete) space and Wave Packet (continuous) space.  So is "Continuous" a good screen name?  Was "Discrete to Continuous" better? Would "Wave Packet" be better than either of those names, since this screen is about how a Fourier series is used to model a wave packet? 

High priority, since the screen name very quickly shows up throughout the code base (in class names, documentation, etc.) and will only become more costly to change.

**Comment by pixelzoom** [comment]
I see that I asked about this in design document comments:

> Christopher Malley
> Jul 18, 2020
> In the Java version, this screen is named "Discrete to Continuous". Is this name change intentional?
> 
> Amy Rouinfar Zohrabi
> Aug 6, 2020
> It was an intentional change. "Continuous" seems descriptive enough and would be more distinguishable from the "Discrete" screen. It's also a shorter string which is better for i18n.

But I still think this is worth discussing again, because "Continuous" doesn't really convey "mapping between Fourier and Wave Packet".

**Comment by arouinfar** [comment]
"Wave Packet" is great! Thanks for the suggestion @pixelzoom. Leaving tagged for design meeting to make sure @kathy-phet also likes it.

**Comment by pixelzoom** [comment]
6/10/21 design meeting:

Everyone likes "Wave Packet". I will make it so.

**Comment by pixelzoom** [comment]
Rename completed in the above commits. Closing.
