### ISSUE TITLE
Reorganize the control panel in Wave Packet screen.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#81]
From 6/10/21 design-meeting in https://github.com/phetsims/fourier-making-waves/issues/72#issuecomment-856223419:

> - [ ] The Java version labeled the top slider in the control panel as "Spacing between Fourier components". This was much too long to fit in the HTML5 version control panel. I shortened it to "Component Spacing", is that OK?
> 
> DECISIONS: 
> * Needs a stronger connection to "Fourier series". 
> * Reorganize the control panel into titled "Fourier Series" and "Wave Packet" subsections.

Here's what the control panel looked like in [1.0.0-dev.28](https://phet-dev.colorado.edu/html/fourier-making-waves/1.0.0-dev.28/phet/fourier-making-waves_en_phet.html):

<img width="1066" alt="screenshot_1052" src="https://user-images.githubusercontent.com/3046552/124840650-b3ac8780-df48-11eb-9c01-b3e6e7a32b6e.png">

**Comment by pixelzoom** [comment]
I made a first attempt at this, see below.  It's still a bit of a cramped mess, too much going on for the amount of vertical space available. I have some ideas for improving it.

<img width="786" alt="screenshot_1027" src="https://user-images.githubusercontent.com/3046552/121979371-48a3d280-cd47-11eb-8b53-8b5614127d46.png">

**Comment by pixelzoom** [comment]
This still feels like a bit of a crowded mess, and I'm at a loss for how to clean it up. Especially the "Width" section, with the 2 dependent sliders.  

@arouinfar thoughts?

**Comment by pixelzoom** [comment]
In #80, I converted the Sliders to NumberControls.  It doesn't make the layout of the control panel better or worse.  Noting here because it changes the look of the control panel. See screenshot below.

<img width="262" alt="screenshot_1054" src="https://user-images.githubusercontent.com/3046552/125359960-5a699d00-e328-11eb-8957-f4a50df3ad8e.png">

**Comment by pixelzoom** [comment]
We could provide some vertical space by moving the subtitles ("Component Spacing", "Center", "Width") to the left of their associated NumberDisplays.  See screenshot below.  

Problems with this:

* "Component Spacing" makes the panel too wide. We'd have to steal some width from the charts. Could this label be shortened to "Spacing"?
* "Width" is repeated twice.  And these values are not the width, they are values that determine the width.  Could we label these with what they really are? Do we really need both sliders? Will anyone figure out how the 2 sliders are related? (dx * dk = 1, dk = 1/dx)

<img width="283" alt="screenshot_1056" src="https://user-images.githubusercontent.com/3046552/125361691-e8df1e00-e32a-11eb-9ce9-eb884033f14b.png">

**Comment by pixelzoom** [comment]
Trying some of the suggestions in the previous comment, see the screenshot below.  "Component Spacing" is shortened to "Spacing".  "Width" is replaced with dk and dt.  dk and dx are specific to the space domain, and would need to change to dω and dt respectively for the time domain.

<img width="259" alt="screenshot_1058" src="https://user-images.githubusercontent.com/3046552/125362573-5b9cc900-e32c-11eb-8e8f-cf12d389dee6.png">

**Comment by pixelzoom** [comment]
I'm back to where we started with this, see screenshot below.  It seems clearer if all of the "Width" stuff needs to be separated from the "Center" control.  I'd like to change "Component Spacing" to "Fourier Component Spacing", but the info button is in the way. 

<img width="256" alt="screenshot_1061" src="https://user-images.githubusercontent.com/3046552/125478049-e550dc97-c140-401f-985c-cc124ad21845.png">

**Comment by pixelzoom** [comment]
Here's another possible improvement, making `dk = 1/dx` explicit.   Is this desirable, or is this something the student should discover?  (I'm doubting that anyone will discover the relationship.)

<img width="258" alt="screenshot_1062" src="https://user-images.githubusercontent.com/3046552/125493159-9d769fac-886b-44ca-b40f-9e0d0d511380.png">

**Comment by pixelzoom** [comment]
> Here's another possible improvement, making `dk = 1/dx` explicit.   Is this desirable, or is this something the student should discover?  

To be addressed in #105.

**Comment by pixelzoom** [comment]
Status: Waiting for feedback from @arouinfar on any of the above designs, and how she would like this control panel to look.

**Comment by pixelzoom** [comment]
Here's a screenshot of the current implementation, as of 7/29/21 and [1.0.0-dev.35](https://phet-dev.colorado.edu/html/fourier-making-waves/1.0.0-dev.35/phet/fourier-making-waves_en_phet.html):

<img width="255" alt="screenshot_1103" src="https://user-images.githubusercontent.com/3046552/127557081-3129a6df-8a5d-4e49-9e81-a7f3284289b1.png">

**Comment by pixelzoom** [comment]
Here's a screenshot of the current implementation, as of 7/29/21 and [1.0.0-dev.35](https://phet-dev.colorado.edu/html/fourier-making-waves/1.0.0-dev.35/phet/fourier-making-waves_en_phet.html).  I'm pretty happy with this, but I'd be happier if the word "Fourier" were somewhere in this control panel, or somewhere on the screen.

<img width="255" alt="screenshot_1103" src="https://user-images.githubusercontent.com/3046552/127557081-3129a6df-8a5d-4e49-9e81-a7f3284289b1.png">

**Comment by pixelzoom** [comment]
> I'm pretty happy with this. But I'd be happier if the word "Fourier" were somewhere in this control panel, or somewhere on the screen.
Discussed with @arouinfar via Zoom.  We like the current layout of this control panel, and are going to leave it as is.

**Comment by pixelzoom** [comment]
I said:
> I'm pretty happy with this. But I'd be happier if the word "Fourier" were somewhere in this control panel, or somewhere on the screen.

Discussed with @arouinfar via Zoom.  We like the current layout of this control panel, and are going to leave it as is.

To make the connection between "Components" and "Fourier Components", we're going to try:
(1) add a "Fourier Component Amplitudes" to the top chart
(2) change the title of the middle chart to "Fourier Components"

**Comment by pixelzoom** [comment]
I've change the chart titles, screenshot below.  @arouinfar please review, close if this looks OK.

<img width="1019" alt="screenshot_1125" src="https://user-images.githubusercontent.com/3046552/128247561-0b2b5e9e-37ba-4751-84a1-5bf544de3595.png">

**Comment by pixelzoom** [comment]
@arouinfar Here's an alternative title that I considered for the top chart, "Amplitudes of Fourier Components".  It puts the important word first, "Amplitudes".  Let me know which one you prefer.

<img width="1018" alt="screenshot_1124" src="https://user-images.githubusercontent.com/3046552/128247910-8565ca38-36d9-4efe-8c4c-f9c19af6aabe.png">

**Comment by pixelzoom** [comment]
Actually....  I think I prefer "Amplitudes of Fourier Components".  "Fourier Component Amplitudes" should (to be grammatically correct) be "Fourier-Component Amplitudes", since it's a compound adjective.  And that looks weird.

**Comment by pixelzoom** [comment]
@arouinfar After you decide which label you'd like here, please assign back to me.  I should make the code (class names, identifiers, etc.) and PhET-iO API (tandem names, etc.) match the labels.

**Comment by pixelzoom** [comment]
Raising priority to high. This is holding up naming of lots of things in the code and in PhET-iO.

**Comment by pixelzoom** [comment]
Another reason why I prefer "Amplitudes of Fourier Components" over "Fourier Component Amplitudes"...  It makes it easier and more natural to refer to this chart as the "Amplitudes" chart.   Having 2 charts that start with "Fourier..."  requires a bit more work to come up with unique names, and could be confusing when trying to describe in the classroom.

**Comment by pixelzoom** [comment]
I changed the title to "Amplitudes of Fourier Component",  and adjusted related PhET-iO tandems.

@arouinfar please review in master.

**Comment by arouinfar** [comment]
I think "Amplitudes of Fourier Components" was the way to go. I don't think there's anything else left for this issue, so closing.
