### ISSUE TITLE
Specify keyboard steps for sliders in the Wave Packet screen.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#83]
Related to https://github.com/phetsims/fourier-making-waves/issues/53.

Specify keyboard steps for sliders in the Wave Packet screen, document in https://docs.google.com/document/d/1wOdmPMD704u4OLl9avI9tl2jpTvsAAcZwMaNfnr0qSs/edit?pli=1#heading=h.qbkcpoz1vzlo.

**Comment by pixelzoom** [comment]
@arouinfar In the above commit, I implemented my best guess.  So you may want to just test-drive in master, and tell me what you'd like to change. 

The current values are:

```js
// Component Spacing (this is an index into the 5 possible values, not the actual value)
keyboardStep: 1,
shiftKeyboardStep: 1,
pageKeyboardStep: 1

// Center
keyboardStep: 1,
shiftKeyboardStep: 0.1,
pageKeyboardStep: Math.PI

// k Width
keyboardStep: 1,
shiftKeyboardStep: 0.01,
pageKeyboardStep: Math.PI

// x Width
keyboardStep: 0.01,
shiftKeyboardStep: 0.001,
pageKeyboardStep: 0.1
```

**Comment by pixelzoom** [comment]
After switching to NumberControl in #80, `shiftKeyboardStep` can no longer be set. It's controlled by NumberControl, and must be the same as `options.delta`, which is the delta per press of the arrow buttons. 

The current values are shown below.  In all cases, `pageKeyboardStep` moves to the min/max of the slider.

```
// Component Spacing (this is an index into the 5 possible values, not the actual value)
keyboardStep: 1,
delta: 1,

// Center
keyboardStep: 1,
delta: 0.1,

// dk
keyboardStep: 1,
delta: 0.01,

// dx
keyboardStep: 0.01,
delta: 0.001,
```

**Comment by pixelzoom** [comment]
In #108, the Center slider was changed. The new values are:

```
// Center
keyboardStep: Math.PI / 4,
delta: Math.PI / 4,
```

**Comment by arouinfar** [comment]
@pixelzoom a few tweaks

- [ ] Wave Packet Center: pageKeyboardStep appears to be pi/2 which is smaller than keyboardStep (pi). Either remove it or make it the same as keyboardStep.

- [ ] Wave Packet Width, σ<sub>k</sub> or σ<sub>ω</sub>: with the changes in #158, let's use keyboardStep = pi/4 and pageKeyboardStep = pi/2

**Comment by pixelzoom** [comment]
Done. @arouinfar please review in master.

**Comment by arouinfar** [comment]
👍🏻
