### ISSUE TITLE
Update a11y design doc?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#85]
From https://github.com/phetsims/fourier-making-waves/issues/53#issuecomment-849956718:

> - [ ] @arouinfar Is it worth the time to put this information in the design doc? #53 (comment)

I don't know how important it is to keep this design document up-to-date, but I think we've made a number of decisions/changes in https://github.com/phetsims/fourier-making-waves/issues/53 that are different. Will this be confusing when work on Interactive Descriptions is resumed in the future? Will this same document be used to continue that work?

**Comment by arouinfar** [comment]
There is a section at the top of the a11y doc for important issues, so I added #53. I also added the step sizes to the sliders and checked that the focus order is correct. I don't believe there's anything else to do for now, so closing.
