### ISSUE TITLE
Unable to reduce number of amplitude controls until pressing Show Answer

### ISSUE THREAD

**Issue by arouinfar** [phetsims/fourier-making-waves#88]
For #69 

Steps to reproduce:
1. Wave Game, any level
2. Notice the decrement button in the Amplitude Controls NumberSpinner is disabled
3. Adjust amplitude sliders until Show Answer is enabled (decrement button still disabled)
4. Show Answer then select New Waveform
5. Decrement button is now enabled

I can't remember if we decided that students need to attempt finding the solution before reducing the number of amplitude controls. Even so, "trying" should not include actually pressing Show Answer so this looks like a bug to me.

**Comment by pixelzoom** [comment]
The problem is that the spinner is initialized incorrectly.  Show Answers is not involved at all.  For example:

1. Wave Game, any level
2. Notice the decrement button in the Amplitude Controls NumberSpinner is disabled
3. Press New Waveform
4. Decrement button becomes enabled.

**Comment by pixelzoom** [comment]
This is likely the problem.  In WaveGameLevel, min for the range is incorrect:

```js
    // @public the number of amplitude controls (sliders) to show in the Amplitudes chart
    this.numberOfAmplitudeControlsProperty = new NumberProperty( config.defaultNumberOfAmplitudeControls, {
      range: new Range( config.defaultNumberOfAmplitudeControls, this.guessSeries.harmonics.length )
    } );
```

Instead of `config.defaultNumberOfAmplitudeControls`, I think it should be `config.getNumberOfNonZeroHarmonics()`.   I'll have to confirm that Level 5 behaves correctly, since the number of non-zero harmonics varies from 5-11.

**Comment by pixelzoom** [comment]
Fixed in the above commit. @arouinfar please verify in master.  Please close if it looks OK.

**Comment by arouinfar** [comment]
Looks good in master
