### ISSUE TITLE
Keyboard help content for hotkeys

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#93]
Related to #91 and #92...  We're adding some hotkeys to Fourier.  

**Wave Game** screen:
In #91, we're adding a hotkey for the "Check Answer" button in Wave Game.  Wave Game currently uses  `SliderAndGeneralKeyboardHelpContent`, which provides the layout and content shown in the screenshot below.  
* Where should we add the hotkey description? 
* What should the title be?  
* What should the description of this hotkey be? "Check your answer" ?
* Can I still use the `SliderAndGeneralKeyboardHelpContent`, should I use a diffferent common-code class, or should I roll my own Node subclass? 

<img width="724" alt="screenshot_1033" src="https://user-images.githubusercontent.com/3046552/123011856-7065ec80-d37e-11eb-838c-16783e98704f.png">

**Discrete** screen:
In #92, we'll eventually be adding hotkeys for TimeControlNode.  It current looks like the screenshot below, and uses SliderAndGeneralKeyboardHelpContent.  
* Will there be common-code support for adding keyboard help content for TimeControlNode?  
* Or will clients have to add (and duplicate) strings?  
* What should the title be?

<img width="721" alt="screenshot_1034" src="https://user-images.githubusercontent.com/3046552/123012197-19144c00-d37f-11eb-98f3-34b107103571.png">

**Comment by jessegreenberg** [comment]
The help content for the TimeControlNode hotkeys in MAL was
![tempsnip](https://user-images.githubusercontent.com/6396244/123147440-48c56180-d41c-11eb-8f03-09a17c04b065.png)

I think it would be great if we could have reusable strings for the TimeControlNode, but have been told we need unique strings for each sim. @arouinfar what do you think?

Even if we continue using unique strings we can make a common code component for the help content.

> Can I still use the SliderAndGeneralKeyboardHelpContent

Probably not, I am guessing we will create a new Node that extends TwoColumnKeyboardHelpContent, but lets see what the requested look of this dialog is for this sim first.

**Comment by pixelzoom** [comment]
Raising priority to high.  This issue has been open for 4 weeks, and this is where we're at:  

We are deferrring adding TimeControlNode hot keys to the Discrete screen's keyboard-help dialog.

We are adding Alt+C (for checking the user's guess) to the keyboard-help dialog for the Wave Game screen.  @arouinfar I need a mockup showing how you'd like this to look.  That includes layout and the description of Alt+C.

Here's the current dialog for Wave Game screen. 

<img width="899" alt="screenshot_1082" src="https://user-images.githubusercontent.com/3046552/126383854-fd062c40-8e89-46d5-a602-43d05a547f90.png">


Here's an example for MAL, where (I believe) Alt+K and Alt+L are the hotkeys:

<img width="954" alt="screenshot_1081" src="https://user-images.githubusercontent.com/3046552/126383804-5699f862-7abb-4596-9bf0-c6c9ab786e26.png">

**Comment by pixelzoom** [comment]
Raising priority to top.  There has been no progress in 6 weeks, this sim is approaching "feature complete", and I can't continue with out a mockup or design input.

**Comment by pixelzoom** [comment]
I went ahead and did something, see the screenshot below.  @arouinfar please review this in master, let me know what you'd like to change.

@jessegreenberg could you please review commit https://github.com/phetsims/fourier-making-waves/commit/f700fb5e342d61f22df833ec981a0727669bac9b, specifically how I added strings to Fourier-making-waves-strings_en.json.  I followed the structure used in molecules-and-light-strings_en.json, where descriptions are under `fourierMakingWavesStrings.a11y.keyboardHelpDialog` and other strings are under `fourierMakingWaves.keyboardHelpDialog`.   Is this the recommended pattern, or just the way it's done in MAL?

<img width="909" alt="screenshot_1163" src="https://user-images.githubusercontent.com/3046552/128947140-a45da13b-d0d0-4338-a4b7-42e3f69d5b57.png">

**Comment by arouinfar** [comment]
The Keyboard dialog contents look good to me. 

@jessegreenberg can you review?

**Comment by jessegreenberg** [comment]
The commit looks good!

> putting descriptions under fourierMakingWavesStrings.a11y.keyboardHelpDialog and other strings under fourierMakingWaves.keyboardHelpDialog. Is this the recommended pattern, or just the way it's done in MAL?

That is the pattern, you can find the description used in the a11y view
![image](https://user-images.githubusercontent.com/6396244/130694291-2d01510d-2479-4ac0-b3f8-2ea06e350ceb.png)

But nested under `a11y` in the strings file it will not be translatable.

**Comment by pixelzoom** [comment]
Looks like everyone who needed to review has signed off (thanks!) so closing.
