### ISSUE TITLE
Discrete Screen pixel polishing

### ISSUE THREAD

**Issue by arouinfar** [phetsims/fourier-making-waves#95]
For #68 

- [ ] The contents of the Measurement Tools NumberSpinners look off-centered due to the subscripts. Is it possible to center the contents while taking the subscripts into account? If not, could we manually shift the contents to the left a bit?
![image](https://user-images.githubusercontent.com/8419308/123734382-79f9c380-d85a-11eb-95f4-db0b9f541d83.png)

- [ ] The serif font tends to look smaller than the sans serif font. It's most obvious in the "Equation" ComboBox. If possible (and reasonable) can the serif font in the "Equation" and "Function of" ComboBoxes and Series RadioButtonGroup be bumped up a point to look more similar? 
![image](https://user-images.githubusercontent.com/8419308/123734976-95190300-d85b-11eb-9be3-3eca716d7769.png) ![image](https://user-images.githubusercontent.com/8419308/123734689-04dabe00-d85b-11eb-966b-05b0f0522d8e.png)

- [ ] The location period counter tool is vertically centered between the Harmonics and Sum graphs, but due to the x-axis labels looks off-center. Can it instead be centered in the space between the Harmonics graph x-axis labels and the top of the Sum graph? Here's a rough approximation:
![image](https://user-images.githubusercontent.com/8419308/123735199-035dc580-d85c-11eb-8f6a-a7a16cb68f8f.png)

**Comment by pixelzoom** [comment]
The 3 requests above each have unique solutions and challenges, and some will require more discussion.  So I've broken them out into 3 separate GitHub issues.  Closing this issue.
