### ISSUE TITLE
no-unmodified-loop-condition lint failure in AmplitudesGenerator.js

### ISSUE THREAD

**Issue by samreid** [phetsims/fourier-making-waves#96]
In https://github.com/phetsims/chipper/issues/814#issuecomment-838724968 we agreed to enable the `no-unmodified-loop-condition` linting rule.  I'll enable the rule, but there is an occurrence in Fourier that I'm not sure how the responsible developer will want to handle.  I'll disable the rule for the offending line for now, and leave up to @pixelzoom to determine how to proceed.

**Comment by pixelzoom** [comment]
> ...  I'll disable the rule for the offending line for now ...

This was done in https://github.com/phetsims/fourier-making-waves/commit/8bb53c73754d1c1d0497b18c2cdaa4e85bef2d51.

**Comment by pixelzoom** [comment]
Rule is described at https://eslint.org/docs/rules/no-unmodified-loop-condition

My loop:

```js
  createAmplitudes( previousAmplitudes ) {
...
    do {
      amplitudes = generateRandomAmplitudes( this.numberOfHarmonics, numberOfNonZeroHarmonics, this.maxAmplitude );
      attempts++;
    } while ( previousAmplitudes && ( attempts < maxAttempts ) && isSimilar( amplitudes, previousAmplitudes ) );
```

lint fails with:

>  error  'previousAmplitudes' is not modified in this loop

So I tried:

```js
  createAmplitudes( previousAmplitudes ) {
...
    const p = previousAmplitudes; 
    do {
      amplitudes = generateRandomAmplitudes( this.numberOfHarmonics, numberOfNonZeroHarmonics, this.maxAmplitude );
      attempts++;
    } while ( p && ( attempts < maxAttempts ) && isSimilar( amplitudes, p ) );
```

... then lint complains:

> error  'p' is not modified in this loop

Why on earth would I expect a constant to be modified in a loop ?!?!?

**Comment by pixelzoom** [comment]
Discussed with @samreid on Zoom.  Decided to disable `no-unmodified-loop-condition`.  This rule seems to have been written by someone who has no understanding of the difference between `while` and `do while`. The latter is used in situations where you want to excute the block _at least_ once, and including an expression that is NOT modified in the loop is a common technique for ensuring the the block is executed _exactly_ once.
