### ISSUE TITLE
Center choices in Measurement Tools spinners

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#98]
Requested by @arouinfar in https://github.com/phetsims/fourier-making-waves/issues/95

The contents of the Measurement Tools NumberSpinners look off-centered due to the subscripts. Is it possible to center the contents while taking the subscripts into account? If not, could we manually shift the contents to the left a bit?

![image](https://user-images.githubusercontent.com/8419308/123734382-79f9c380-d85a-11eb-95f4-db0b9f541d83.png)

**Comment by pixelzoom** [comment]
Done in the above commit, see screenshot below.  Please review in master.

<img width="307" alt="screenshot_1042" src="https://user-images.githubusercontent.com/3046552/124186515-a6d7f180-da79-11eb-8fa9-abefa83cb9cc.png">

**Comment by arouinfar** [comment]
Looks great!
