### ISSUE TITLE
Make size appear to be more uniform for serif and sans serif font.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#99]
Requested by @arouinfar in https://github.com/phetsims/fourier-making-waves/issues/95.

The serif font tends to look smaller than the sans serif font. It's most obvious in the "Equation" ComboBox. If possible (and reasonable) can the serif font in the "Equation" and "Function of" ComboBoxes and Series RadioButtonGroup be bumped up a point to look more similar? 

![image](https://user-images.githubusercontent.com/8419308/123734976-95190300-d85b-11eb-9be3-3eca716d7769.png) ![image](https://user-images.githubusercontent.com/8419308/123734689-04dabe00-d85b-11eb-966b-05b0f0522d8e.png)

**Comment by pixelzoom** [comment]
The font used for controls throughout the sim is 12-point.  I added a separate font for use with controls that involve the math font (serif), and it is 13-point.  Here are the defintions in FMWConstants.js:

```js
  CONTROL_FONT: new PhetFont( 12 ),
  MATH_CONTROL_FONT: new PhetFont( 13 ), // use a larger font for math symbols, see https://github.com/phetsims/fourier-making-waves/issues/99
```

MATH_CONTROL_FONT is now used in these places:
* Series radio buttons
* Equation combo box
* Measurement Tools spinners

The "Function of" combo box is problematic.  For translation, it is necessarily 1 string pattern that gets filled in with the proper symbol.  So it contains both serif and sans serif text.  And it must also be 1 RichText node, having 1 font.   So options are:
(1) leave as is
(2) uniformly increase the size of both the serif and sans serif font

@arouinfar please review and let me know how you'd like to proceed for the "Function of" combo box.

**Comment by arouinfar** [comment]
Thanks @pixelzoom. I think this already looks much better. We don't really have the room to uniformly increase the font sizes, so I am fine with leaving as-is. I think the units are more secondary in the "Function of" ComboBox, so the contents are still readable at the current size.
